export enum NormalizedCapability {
  // 1. Payments
  PAYMENT_CREATE_PAYMENT = 'PAYMENT_CREATE_PAYMENT',
  PAYMENT_CREATE_ORDER = 'PAYMENT_CREATE_ORDER',
  PAYMENT_AUTHORIZE = 'PAYMENT_AUTHORIZE',
  PAYMENT_CAPTURE = 'PAYMENT_CAPTURE',
  PAYMENT_REFUND = 'PAYMENT_REFUND',
  PAYMENT_PARTIAL_REFUND = 'PAYMENT_PARTIAL_REFUND',
  PAYMENT_VERIFY = 'PAYMENT_VERIFY',
  PAYMENT_PAYOUT = 'PAYMENT_PAYOUT',
  PAYMENT_RECURRING = 'PAYMENT_RECURRING',
  PAYMENT_TOKENIZATION = 'PAYMENT_TOKENIZATION',
  PAYMENT_SPLIT = 'PAYMENT_SPLIT',
  PAYMENT_WEBHOOK = 'PAYMENT_WEBHOOK',
  PAYMENT_SETTLEMENT_RECONCILIATION = 'PAYMENT_SETTLEMENT_RECONCILIATION',

  // 2. Messaging - WhatsApp
  WHATSAPP_SEND_TEXT = 'WHATSAPP_SEND_TEXT',
  WHATSAPP_SEND_TEMPLATE = 'WHATSAPP_SEND_TEMPLATE',
  WHATSAPP_SEND_MEDIA = 'WHATSAPP_SEND_MEDIA',
  WHATSAPP_OTP = 'WHATSAPP_OTP',
  WHATSAPP_DELIVERY_STATUS = 'WHATSAPP_DELIVERY_STATUS',
  WHATSAPP_WEBHOOK = 'WHATSAPP_WEBHOOK',

  // 3. Messaging - SMS
  SMS_TRANSACTIONAL = 'SMS_TRANSACTIONAL',
  SMS_PROMOTIONAL = 'SMS_PROMOTIONAL',
  SMS_OTP = 'SMS_OTP',
  SMS_DELIVERY_REPORT = 'SMS_DELIVERY_REPORT',
  SMS_DND_COMPLIANCE = 'SMS_DND_COMPLIANCE',

  // 4. Messaging - Email
  EMAIL_TRANSACTIONAL = 'EMAIL_TRANSACTIONAL',
  EMAIL_MARKETING = 'EMAIL_MARKETING',
  EMAIL_TEMPLATE_RENDER = 'EMAIL_TEMPLATE_RENDER',
  EMAIL_ATTACHMENT = 'EMAIL_ATTACHMENT',
  EMAIL_BOUNCE_TRACKING = 'EMAIL_BOUNCE_TRACKING',

  // 5. Messaging - Push
  PUSH_DEVICE = 'PUSH_DEVICE',
  PUSH_TOPIC = 'PUSH_TOPIC',
  PUSH_RICH_MEDIA = 'PUSH_RICH_MEDIA',
  PUSH_INTERACTIVE = 'PUSH_INTERACTIVE',

  // 6. Maps & Geolocation
  MAPS_GEOCODE = 'MAPS_GEOCODE',
  MAPS_REVERSE_GEOCODE = 'MAPS_REVERSE_GEOCODE',
  MAPS_DIRECTIONS_ROUTE = 'MAPS_DIRECTIONS_ROUTE',
  MAPS_DISTANCE_MATRIX = 'MAPS_DISTANCE_MATRIX',
  MAPS_PLACES_AUTOCOMPLETE = 'MAPS_PLACES_AUTOCOMPLETE',
  MAPS_GEOFENCING = 'MAPS_GEOFENCING',

  // 7. Identity & Verification (KYC)
  KYC_PAN_VERIFY = 'KYC_PAN_VERIFY',
  KYC_DL_VERIFY = 'KYC_DL_VERIFY',
  KYC_AADHAAR_OKYC = 'KYC_AADHAAR_OKYC',
  KYC_GST_VERIFY = 'KYC_GST_VERIFY',
  KYC_VEHICLE_RC_VERIFY = 'KYC_VEHICLE_RC_VERIFY',
  KYC_DOCUMENT_OCR = 'KYC_DOCUMENT_OCR',
  KYC_FACE_LIVENESS = 'KYC_FACE_LIVENESS',
  KYC_FRAUD_CHECK = 'KYC_FRAUD_CHECK',

  // 8. Vehicle Tracking & Telematics
  TELEMATICS_LIVE_GPS = 'TELEMATICS_LIVE_GPS',
  TELEMATICS_INGEST = 'TELEMATICS_INGEST',
  TELEMATICS_IMMOBILIZE = 'TELEMATICS_IMMOBILIZE',
  TELEMATICS_LOCK_UNLOCK = 'TELEMATICS_LOCK_UNLOCK',
  TELEMATICS_ODOMETER_SYNC = 'TELEMATICS_ODOMETER_SYNC',
  TELEMATICS_FUEL_EV_METRICS = 'TELEMATICS_FUEL_EV_METRICS',
  TELEMATICS_DIAGNOSTICS = 'TELEMATICS_DIAGNOSTICS',

  // 9. Storage & CDN
  STORAGE_UPLOAD = 'STORAGE_UPLOAD',
  STORAGE_DOWNLOAD = 'STORAGE_DOWNLOAD',
  STORAGE_PRESIGNED_URL = 'STORAGE_PRESIGNED_URL',
  STORAGE_MULTIPART = 'STORAGE_MULTIPART',
  STORAGE_DELETE = 'STORAGE_DELETE',

  // 10. Accounting & ERP
  ACCOUNTING_CREATE_INVOICE = 'ACCOUNTING_CREATE_INVOICE',
  ACCOUNTING_RECORD_PAYMENT = 'ACCOUNTING_RECORD_PAYMENT',
  ACCOUNTING_TAX_CALCULATION = 'ACCOUNTING_TAX_CALCULATION',
  ACCOUNTING_GST_RETURN_SYNC = 'ACCOUNTING_GST_RETURN_SYNC',
  ACCOUNTING_LEDGER_POSTING = 'ACCOUNTING_LEDGER_POSTING',

  // 11. Search
  SEARCH_FULL_TEXT = 'SEARCH_FULL_TEXT',
  SEARCH_SEMANTIC = 'SEARCH_SEMANTIC',
  SEARCH_GEO_FILTER = 'SEARCH_GEO_FILTER',

  // 12. AI & Document Intelligence
  AI_DOCUMENT_OCR = 'AI_DOCUMENT_OCR',
  AI_DAMAGE_INSPECTION = 'AI_DAMAGE_INSPECTION',
  AI_CONVERSATIONAL = 'AI_CONVERSATIONAL',
  AI_RISK_EVALUATION = 'AI_RISK_EVALUATION',
}

export interface CapabilityMatchRequest {
  category: string;
  requiredCapabilities: string[];
  preferredCapabilities?: string[];
  country?: string;
  currency?: string;
}

export interface CapabilityMatchResult {
  providerId: string;
  matchedRequired: string[];
  matchedPreferred: string[];
  missingRequired: string[];
  coveragePercent: number; // 0 to 100
  isFullyCapable: boolean;
}
