name: ui_kit
description: Shared UI components for the car rental platform.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  models:
    path: ../models
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  gap: ^3.0.1
