name: core
description: Shared core constants, utils and theme for the car rental platform.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^8.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
