import {
  CatalogProviderMetadata,
  ProviderActivationState,
  ProviderLifecycleState,
  ProviderCertificationLevel,
  ProviderImplementationStatus,
  ProviderEnvironment,
} from './provider-catalog.types';
import { IntegrationCategory } from '../registry/provider.types';

/**
 * DRIVEGO ENTERPRISE COMMUNICATIONS PROVIDER CATALOG (44 PROVIDERS)
 * Phase M: 8 WhatsApp, 19 SMS (11 India + 8 Global), 8 Email, 4 Push, 5 Voice providers.
 */
export const ENTERPRISE_COMMUNICATIONS_PROVIDERS: CatalogProviderMetadata[] = [
  // =========================================================================
  // 1. WHATSAPP PROVIDERS (8 PROVIDERS)
  // =========================================================================
  {
    providerId: 'meta',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Meta WhatsApp Cloud API',
    tagline: 'Official Meta Cloud API for WhatsApp Business messaging and verified templates',
    description: 'High-throughput verified WhatsApp messaging directly through Meta Cloud infrastructure with end-to-end encryption.',
    icon: 'chat',
    websiteUrl: 'https://business.whatsapp.com',
    documentation: {
      overview: 'Official Meta WhatsApp Business Cloud API with template approval, interactive buttons, and media messages.',
      docsUrl: 'https://developers.facebook.com/docs/whatsapp/cloud-api',
      setupGuide: 'Create a Meta Business Manager account, configure WhatsApp System User token, and register phone number.',
      webhookGuide: 'Configure webhook URL /integrations/webhooks/whatsapp with verify token and app secret.',
      supportEmail: 'support@meta.com',
    },
    version: 'v19.0',
    apiVersion: 'v19.0',
    author: 'Meta Platforms Inc.',
    tags: ['whatsapp', 'messaging', 'meta', 'templates', 'customer-service', 'otp'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'phoneNumberId', label: 'Phone Number ID', type: 'string', required: true, isSecret: false, description: 'Meta Phone Number ID' },
      { key: 'accessToken', label: 'System User Token', type: 'password', required: true, isSecret: true, description: 'Permanent Access Token' },
      { key: 'wabaId', label: 'WABA ID', type: 'string', required: true, isSecret: false, description: 'WhatsApp Business Account ID' },
      { key: 'webhookSecret', label: 'App Secret', type: 'password', required: true, isSecret: true, description: 'Meta App Secret for HMAC verification' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'SEND_MEDIA', 'SEND_DOCUMENT', 'SEND_OTP', 'DELIVERY_STATUS', 'DELIVERY_WEBHOOK', 'READ_STATUS'],
    supportedCurrencies: ['INR', 'USD', 'EUR', 'AED'],
    supportedCountries: ['IN', 'AE', 'US', 'GB', 'SG'],
    supportedWebhookEvents: ['messages', 'message_deliveries', 'message_reads'],
    webhookSignatureHeader: 'x-hub-signature-256',
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.45, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 150,
    priority: 1,
    fallbackProviderId: 'gupshup_whatsapp',
  },
  {
    providerId: 'gupshup_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Gupshup WhatsApp Enterprise',
    tagline: 'Leading Indian conversational messaging BSP with instant template syndication',
    description: 'Enterprise WhatsApp Business Solution Provider (BSP) offering guaranteed throughput, rich media, and 2-way conversational bots.',
    icon: 'forum',
    websiteUrl: 'https://gupshup.io',
    documentation: {
      overview: 'Enterprise WhatsApp messaging gateway with high-availability multi-channel fallback.',
      docsUrl: 'https://docs.gupshup.io/reference/whatsapp-api',
      setupGuide: 'Obtain Gupshup App Name and API Key from Gupshup Enterprise Portal.',
      webhookGuide: 'Set callback endpoint to /integrations/webhooks/gupshup.',
      supportEmail: 'enterprise@gupshup.io',
    },
    version: '2.4.0',
    apiVersion: 'v3',
    author: 'Gupshup Technology India Pvt Ltd',
    tags: ['whatsapp', 'bsp', 'gupshup', 'conversational', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'appName', label: 'App Name', type: 'string', required: true, isSecret: false, description: 'Gupshup WhatsApp App Name' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Gupshup API Key' },
      { key: 'sourceNumber', label: 'Source Phone Number', type: 'string', required: true, isSecret: false, description: 'Registered sender number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'SEND_MEDIA', 'SEND_DOCUMENT', 'SEND_OTP', 'DELIVERY_STATUS', 'DELIVERY_WEBHOOK'],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'AE', 'SG', 'ID'],
    supportedWebhookEvents: ['message.delivered', 'message.read', 'message.failed'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.ADAPTER_IMPLEMENTED,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.48, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 120,
    priority: 2,
    fallbackProviderId: 'twilio_whatsapp',
  },
  {
    providerId: 'twilio_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Twilio for WhatsApp',
    tagline: 'Global programmable WhatsApp messaging with unified Twilio Messaging API',
    description: 'Send WhatsApp messages globally using Twilio Programmable Messaging API with automatic formatting and failover.',
    icon: 'textsms',
    websiteUrl: 'https://www.twilio.com/whatsapp',
    documentation: {
      overview: 'Twilio Conversations and Messaging API for WhatsApp Business integration.',
      docsUrl: 'https://www.twilio.com/docs/whatsapp',
      setupGuide: 'Link WABA in Twilio Console and obtain Account SID and Auth Token.',
      webhookGuide: 'Configure Status Callback URL in Twilio WhatsApp Sandbox/Sender settings.',
      supportEmail: 'support@twilio.com',
    },
    version: '2024-04',
    apiVersion: '2010-04-01',
    author: 'Twilio Inc.',
    tags: ['whatsapp', 'twilio', 'global', 'programmable'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accountSid', label: 'Account SID', type: 'string', required: true, isSecret: false, description: 'Twilio Account SID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Twilio Auth Token' },
      { key: 'fromNumber', label: 'From WhatsApp Number', type: 'string', required: true, isSecret: false, description: 'Twilio WhatsApp sender (whatsapp:+1...)' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'SEND_MEDIA', 'DELIVERY_STATUS', 'DELIVERY_WEBHOOK'],
    supportedCurrencies: ['USD', 'EUR', 'INR'],
    supportedCountries: ['US', 'GB', 'IN', 'EU', 'AE'],
    supportedWebhookEvents: ['message-delivered', 'message-read', 'message-failed'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0075, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 3,
  },
  {
    providerId: 'infobip_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Infobip WhatsApp Business',
    tagline: 'Enterprise omni-channel cloud communications with direct WhatsApp telco routes',
    description: 'Enterprise-grade WhatsApp BSP with compliance routing, failover, and global telco relationships.',
    icon: 'support_agent',
    websiteUrl: 'https://www.infobip.com',
    documentation: { overview: 'Infobip WhatsApp Business Cloud API.', docsUrl: 'https://www.infobip.com/docs/whatsapp' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'Infobip Ltd.',
    tags: ['whatsapp', 'infobip', 'enterprise', 'europe', 'asia'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Infobip API Key' },
      { key: 'baseUrl', label: 'Base URL', type: 'string', required: true, isSecret: false, description: 'Custom Infobip Base URL' },
      { key: 'senderNumber', label: 'Sender Number', type: 'string', required: true, isSecret: false, description: 'Verified WhatsApp Number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'DELIVERY_STATUS'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['EU', 'US', 'GB', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.008, currency: 'EUR' },
    slaUptimePercent: 99.99,
    maxRps: 100,
    priority: 4,
  },
  {
    providerId: 'kaleyra_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Kaleyra (Tata Communications) WhatsApp',
    tagline: 'High-availability CPaaS WhatsApp gateway for banking and enterprise mobility',
    description: 'Tier-1 WhatsApp gateway by Tata Communications company, offering low-latency message delivery and deep Indian telco integration.',
    icon: 'business',
    websiteUrl: 'https://www.kaleyra.com',
    documentation: { overview: 'Kaleyra WhatsApp API documentation.', docsUrl: 'https://developers.kaleyra.io' },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'Kaleyra / Tata Communications',
    tags: ['whatsapp', 'kaleyra', 'tata', 'enterprise', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Kaleyra API Key' },
      { key: 'sid', label: 'Account SID', type: 'string', required: true, isSecret: false, description: 'Kaleyra Account SID' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'DELIVERY_STATUS'],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'IT', 'US'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.46, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 80,
    priority: 5,
  },
  {
    providerId: 'vonage_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Vonage (Nexmo) WhatsApp',
    tagline: 'Vonage Messages API for WhatsApp, Facebook Messenger, and Viber',
    description: 'Unified social messaging API connecting enterprise customer journeys to WhatsApp and omnichannel messaging.',
    icon: 'connect_without_contact',
    websiteUrl: 'https://www.vonage.com',
    documentation: { overview: 'Vonage Messages API.', docsUrl: 'https://developer.vonage.com/messages/overview' },
    version: '1.2.0',
    apiVersion: 'v1',
    author: 'Vonage / Ericsson',
    tags: ['whatsapp', 'vonage', 'nexmo', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'string', required: true, isSecret: false, description: 'Vonage API Key' },
      { key: 'apiSecret', label: 'API Secret', type: 'password', required: true, isSecret: true, description: 'Vonage API Secret' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD', 'EUR'],
    supportedCountries: ['US', 'GB', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.007, currency: 'EUR' },
    slaUptimePercent: 99.9,
    maxRps: 80,
    priority: 6,
  },
  {
    providerId: 'bird_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Bird (MessageBird) WhatsApp',
    tagline: 'Next-generation AI communications CRM and WhatsApp gateway',
    description: 'European omnichannel communications platform offering WhatsApp automation, conversation threads, and template management.',
    icon: 'flutter_dash',
    websiteUrl: 'https://bird.com',
    documentation: { overview: 'Bird Conversations API.', docsUrl: 'https://docs.bird.com' },
    version: '3.0.0',
    apiVersion: 'v1',
    author: 'Bird Inc.',
    tags: ['whatsapp', 'bird', 'messagebird', 'europe'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKey', label: 'Access Key', type: 'password', required: true, isSecret: true, description: 'Bird Access Key' },
      { key: 'channelId', label: 'Channel ID', type: 'string', required: true, isSecret: false, description: 'WhatsApp Channel UUID' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE', 'DELIVERY_STATUS'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['NL', 'GB', 'DE', 'US'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0078, currency: 'EUR' },
    slaUptimePercent: 99.9,
    maxRps: 60,
    priority: 7,
  },
  {
    providerId: '360dialog',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: '360dialog WhatsApp BSP',
    tagline: 'Direct WhatsApp Cloud API infrastructure provider for high-scale enterprise apps',
    description: 'Specialist BSP focusing exclusively on WhatsApp Business API with high-volume throughput and zero markup on Meta fees.',
    icon: 'speed',
    websiteUrl: 'https://www.360dialog.com',
    documentation: { overview: '360dialog WhatsApp API.', docsUrl: 'https://docs.360dialog.com' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: '360dialog GmbH',
    tags: ['whatsapp', 'bsp', 'direct', 'meta-partner'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: '360dialog API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_TEMPLATE'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['DE', 'EU', 'US', 'IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.005, currency: 'EUR' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 8,
  },

  // =========================================================================
  // 2. SMS PROVIDERS (19 PROVIDERS: 11 INDIA + 8 GLOBAL)
  // =========================================================================
  // --- India-Focused SMS ---
  {
    providerId: 'msg91',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'MSG91',
    tagline: 'Leading Indian enterprise SMS, DLT compliance, and high-speed OTP gateway',
    description: 'Enterprise bulk SMS and transactional OTP platform engineered for India with deep TRAI DLT registry integration.',
    icon: 'sms',
    websiteUrl: 'https://msg91.com',
    documentation: {
      overview: 'MSG91 Send SMS and OTP APIs with Flow campaign builder and DLT verification.',
      docsUrl: 'https://docs.msg91.com',
      setupGuide: 'Obtain AuthKey from MSG91 panel and register DLT Entity ID & Sender ID with telecom operators.',
      supportEmail: 'support@msg91.com',
    },
    version: '5.0',
    apiVersion: 'v5',
    author: 'Walkover Technologies (MSG91)',
    tags: ['sms', 'india', 'dlt', 'otp', 'transactional'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'authKey', label: 'AuthKey', type: 'password', required: true, isSecret: true, description: 'MSG91 AuthKey' },
      { key: 'senderId', label: 'Sender ID / Header', type: 'string', required: true, isSecret: false, description: '6-character DLT approved Sender ID (e.g. DRIVGO)' },
      { key: 'dltEntityId', label: 'DLT Entity ID', type: 'string', required: true, isSecret: false, description: 'Telecom DLT Entity Registration Number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP', 'VERIFY_OTP', 'SEND_TEMPLATE', 'DELIVERY_STATUS'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.14, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 200,
    priority: 1,
    fallbackProviderId: 'twilio_sms',
  },
  {
    providerId: 'twilio_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Twilio India SMS',
    tagline: 'High-reliability programmable SMS with direct operator connectivity in India',
    description: 'Carrier-grade SMS infrastructure with automated number pooling, smart routing, and Indian regulatory compliance.',
    icon: 'textsms',
    websiteUrl: 'https://www.twilio.com',
    documentation: { overview: 'Twilio Programmable SMS API.', docsUrl: 'https://www.twilio.com/docs/sms' },
    version: '2024-05',
    apiVersion: '2010-04-01',
    author: 'Twilio Inc.',
    tags: ['sms', 'india', 'global', 'carrier-grade'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accountSid', label: 'Account SID', type: 'string', required: true, isSecret: false, description: 'Twilio Account SID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Twilio Auth Token' },
      { key: 'fromNumber', label: 'Sender ID / Number', type: 'string', required: true, isSecret: false, description: 'Sender ID or Twilio phone number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP', 'DELIVERY_STATUS'],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'US', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.18, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 150,
    priority: 2,
    fallbackProviderId: 'gupshup_sms',
  },
  {
    providerId: 'gupshup_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Gupshup India SMS',
    tagline: 'High-throughput enterprise SMS gateway with smart DLT scrubbing in India',
    description: 'Full-stack enterprise Indian SMS gateway processing billions of monthly transactions with smart fallback.',
    icon: 'forum',
    websiteUrl: 'https://gupshup.io',
    documentation: { overview: 'Gupshup SMS API.', docsUrl: 'https://docs.gupshup.io/reference/sms-api' },
    version: '2.1.0',
    apiVersion: 'v2',
    author: 'Gupshup Technology India Pvt Ltd',
    tags: ['sms', 'india', 'dlt', 'gupshup'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'userId', label: 'Gupshup User ID', type: 'string', required: true, isSecret: false, description: 'Account User ID' },
      { key: 'password', label: 'Password', type: 'password', required: true, isSecret: true, description: 'Account Password' },
      { key: 'senderId', label: 'Sender ID', type: 'string', required: true, isSecret: false, description: 'TRAI approved 6-char Header' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP', 'DELIVERY_STATUS'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.ADAPTER_IMPLEMENTED,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.15, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 150,
    priority: 3,
    fallbackProviderId: 'exotel_sms',
  },
  {
    providerId: 'exotel_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Exotel SMS',
    tagline: 'Indian cloud telephony and mission-critical OTP SMS gateway',
    description: 'Enterprise communication provider built for Indian logistics, car rentals, and high-priority OTP notifications.',
    icon: 'phone_in_talk',
    websiteUrl: 'https://exotel.com',
    documentation: { overview: 'Exotel SMS API.', docsUrl: 'https://developer.exotel.com/api' },
    version: '1.4.0',
    apiVersion: 'v1',
    author: 'Exotel Techcom Pvt Ltd',
    tags: ['sms', 'exotel', 'india', 'otp'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'string', required: true, isSecret: false, description: 'Exotel API Key' },
      { key: 'apiToken', label: 'API Token', type: 'password', required: true, isSecret: true, description: 'Exotel API Token' },
      { key: 'subDomain', label: 'Account Subdomain', type: 'string', required: true, isSecret: false, description: 'e.g. api.exotel.com' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP', 'DELIVERY_STATUS'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.16, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 4,
  },
  {
    providerId: 'karix_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Karix Mobile SMS',
    tagline: 'Tier-1 enterprise SMS gateway powering Indian banking and mobility infrastructure',
    description: 'High-volume carrier-integrated messaging engine by Tanla, powering OTPs and alerts across tier-1 banks and enterprises.',
    icon: 'account_balance',
    websiteUrl: 'https://www.karix.com',
    documentation: { overview: 'Karix Developer Hub.', docsUrl: 'https://developer.karix.com' },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'Karix Mobile / Tanla Platforms',
    tags: ['sms', 'karix', 'tanla', 'banking', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'authKey', label: 'Auth Key', type: 'password', required: true, isSecret: true, description: 'Karix Auth Key' },
      { key: 'senderId', label: 'Sender ID', type: 'string', required: true, isSecret: false, description: 'DLT Header' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.15, currency: 'INR' },
    slaUptimePercent: 99.99,
    maxRps: 200,
    priority: 5,
  },
  {
    providerId: 'routemobile_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Route Mobile SMS',
    tagline: 'Global cloud communications provider with extensive Indian telco connectivity',
    description: 'Tier-1 SMS routing with intelligent firewall bypass, high-availability data centers, and dynamic load balancing.',
    icon: 'alt_route',
    websiteUrl: 'https://routemobile.com',
    documentation: { overview: 'Route Mobile SMS API.', docsUrl: 'https://routemobile.com/developers' },
    version: '3.1.0',
    apiVersion: 'v3',
    author: 'Route Mobile Ltd.',
    tags: ['sms', 'routemobile', 'india', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'username', label: 'Username', type: 'string', required: true, isSecret: false, description: 'Account Username' },
      { key: 'password', label: 'Password', type: 'password', required: true, isSecret: true, description: 'Account Password' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP'],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'AE', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.15, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 120,
    priority: 6,
  },
  {
    providerId: 'valuefirst_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'ValueFirst (Twilio) SMS',
    tagline: 'Leading Indian enterprise messaging aggregator with high-speed delivery pipelines',
    description: 'Part of Twilio group, providing robust domestic Indian transactional and promotional SMS with DLT compliance.',
    icon: 'mark_chat_read',
    websiteUrl: 'https://www.vfirst.com',
    documentation: { overview: 'ValueFirst HTTP API.', docsUrl: 'https://www.vfirst.com/api' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'ValueFirst Digital Media',
    tags: ['sms', 'valuefirst', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'username', label: 'Username', type: 'string', required: true, isSecret: false, description: 'ValueFirst User' },
      { key: 'password', label: 'Password', type: 'password', required: true, isSecret: true, description: 'ValueFirst Password' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.14, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 100,
    priority: 7,
  },
  {
    providerId: 'tanla_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Tanla Platforms Wisely',
    tagline: 'Blockchain-enabled CPaaS platform ensuring cryptographic SMS security and compliance',
    description: 'Wisely platform by Tanla ensures end-to-end data privacy, cryptographic proof of delivery, and zero-spam compliance.',
    icon: 'security',
    websiteUrl: 'https://www.tanla.com',
    documentation: { overview: 'Tanla Wisely CPaaS API.', docsUrl: 'https://tanla.com/developers' },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'Tanla Platforms Ltd.',
    tags: ['sms', 'tanla', 'wisely', 'blockchain', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Wisely API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.16, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 150,
    priority: 8,
  },
  {
    providerId: 'textlocal_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Textlocal India',
    tagline: 'Reliable business SMS platform for transactional alerts and customer campaigns',
    description: 'Simple and fast Indian SMS gateway with instant DLT template approval, detailed reporting, and inbox features.',
    icon: 'forward_to_inbox',
    websiteUrl: 'https://www.textlocal.in',
    documentation: { overview: 'Textlocal API docs.', docsUrl: 'https://api.textlocal.in/docs' },
    version: '1.2.0',
    apiVersion: 'v1',
    author: 'IMI Mobile / Textlocal',
    tags: ['sms', 'textlocal', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Textlocal API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.16, currency: 'INR' },
    slaUptimePercent: 99.8,
    maxRps: 50,
    priority: 9,
  },
  {
    providerId: 'twofactor_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: '2Factor Dedicated SMS OTP',
    tagline: 'Dedicated Indian OTP delivery gateway with sub-5-second SLA guarantee',
    description: 'Specialized 2FA and OTP infrastructure guaranteeing high delivery speed through private telecom routing lanes.',
    icon: 'pin',
    websiteUrl: 'https://2factor.in',
    documentation: { overview: '2Factor OTP API.', docsUrl: 'https://2factor.in/v3' },
    version: '3.0.0',
    apiVersion: 'v3',
    author: '2Factor Networks',
    tags: ['sms', 'otp', '2factor', 'india', 'fast-otp'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: '2Factor API Key' },
    ],
    supportedCapabilities: ['SEND_OTP', 'VERIFY_OTP'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.18, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 10,
  },
  {
    providerId: 'fast2sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Fast2SMS',
    tagline: 'Quick onboarding transactional and OTP SMS gateway for startups in India',
    description: 'Developer-friendly Indian SMS gateway with instant wallet recharges, quick DLT configuration, and test sandboxes.',
    icon: 'electric_bolt',
    websiteUrl: 'https://www.fast2sms.com',
    documentation: { overview: 'Fast2SMS API documentation.', docsUrl: 'https://docs.fast2sms.com' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'Fast2SMS Media',
    tags: ['sms', 'fast2sms', 'india', 'low-cost'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'authorization', label: 'Authorization Key', type: 'password', required: true, isSecret: true, description: 'API Secret' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.12, currency: 'INR' },
    slaUptimePercent: 99.5,
    maxRps: 50,
    priority: 11,
  },

  // --- Global SMS ---
  {
    providerId: 'twilio_global_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Twilio Global Programmable SMS',
    tagline: 'World-leading programmable SMS reaching 180+ countries with carrier intelligence',
    description: 'Scalable cloud messaging platform with Alphanumeric Sender IDs, global number pool, and automatic short-code failovers.',
    icon: 'public',
    websiteUrl: 'https://www.twilio.com',
    documentation: { overview: 'Twilio Programmable SMS API.', docsUrl: 'https://www.twilio.com/docs/sms' },
    version: '2024-05',
    apiVersion: '2010-04-01',
    author: 'Twilio Inc.',
    tags: ['sms', 'global', 'twilio', 'programmable'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accountSid', label: 'Account SID', type: 'string', required: true, isSecret: false, description: 'Twilio Account SID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Twilio Auth Token' },
      { key: 'fromNumber', label: 'Sender ID / Phone', type: 'string', required: true, isSecret: false, description: 'Twilio Phone Number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP', 'DELIVERY_STATUS', 'DELIVERY_WEBHOOK'],
    supportedCurrencies: ['USD', 'EUR', 'GBP'],
    supportedCountries: ['US', 'GB', 'EU', 'AE', 'SG', 'AU', 'CA'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.ADAPTER_IMPLEMENTED,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0079, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 200,
    priority: 1,
    fallbackProviderId: 'vonage_sms',
  },
  {
    providerId: 'vonage_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Vonage Global SMS',
    tagline: 'Global communications API with adaptive routing and carrier relationships',
    description: 'High-availability SMS platform connecting over 1,600 telecom networks worldwide with intelligent queueing.',
    icon: 'travel_explore',
    websiteUrl: 'https://www.vonage.com',
    documentation: { overview: 'Vonage SMS API.', docsUrl: 'https://developer.vonage.com/messaging/sms/overview' },
    version: '1.1.0',
    apiVersion: 'v1',
    author: 'Vonage',
    tags: ['sms', 'vonage', 'nexmo', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'string', required: true, isSecret: false, description: 'Vonage API Key' },
      { key: 'apiSecret', label: 'API Secret', type: 'password', required: true, isSecret: true, description: 'Vonage API Secret' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD', 'EUR'],
    supportedCountries: ['US', 'GB', 'EU', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0072, currency: 'EUR' },
    slaUptimePercent: 99.9,
    maxRps: 150,
    priority: 2,
    fallbackProviderId: 'sinch_sms',
  },
  {
    providerId: 'sinch_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Sinch Global SMS',
    tagline: 'Cloud communications leader with direct super-network carrier connections',
    description: 'Sinch direct super-network connects to mobile operators worldwide for low-latency OTP and transactional alerts.',
    icon: 'hub',
    websiteUrl: 'https://sinch.com',
    documentation: { overview: 'Sinch SMS REST API.', docsUrl: 'https://developers.sinch.com' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'Sinch AB',
    tags: ['sms', 'sinch', 'global', 'carrier-direct'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'servicePlanId', label: 'Service Plan ID', type: 'string', required: true, isSecret: false, description: 'Sinch Service Plan ID' },
      { key: 'apiToken', label: 'API Token', type: 'password', required: true, isSecret: true, description: 'Sinch API Token' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'SEND_OTP'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['EU', 'US', 'GB', 'SG', 'AU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0075, currency: 'EUR' },
    slaUptimePercent: 99.95,
    maxRps: 150,
    priority: 3,
  },
  {
    providerId: 'infobip_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Infobip Global SMS',
    tagline: 'Global enterprise SMS network with 800+ direct operator connections',
    description: 'Enterprise CPaaS providing guaranteed delivery, compliance adherence, and real-time delivery insights.',
    icon: 'cell_tower',
    websiteUrl: 'https://www.infobip.com',
    documentation: { overview: 'Infobip SMS API.', docsUrl: 'https://www.infobip.com/docs/sms' },
    version: '2.0.0',
    apiVersion: 'v1',
    author: 'Infobip Ltd.',
    tags: ['sms', 'infobip', 'global', 'enterprise'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Infobip API Key' },
      { key: 'baseUrl', label: 'Base URL', type: 'string', required: true, isSecret: false, description: 'Infobip Base URL' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'DELIVERY_STATUS'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['EU', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0074, currency: 'EUR' },
    slaUptimePercent: 99.99,
    maxRps: 150,
    priority: 4,
  },
  {
    providerId: 'plivo_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Plivo SMS',
    tagline: 'Cost-effective global cloud messaging platform with high API reliability',
    description: 'Plivo SMS platform offering low latency, multi-carrier redundancy, and automated number management.',
    icon: 'phonelink_ring',
    websiteUrl: 'https://www.plivo.com',
    documentation: { overview: 'Plivo SMS API.', docsUrl: 'https://www.plivo.com/docs/sms' },
    version: '1.5.0',
    apiVersion: 'v1',
    author: 'Plivo Inc.',
    tags: ['sms', 'plivo', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'authId', label: 'Auth ID', type: 'string', required: true, isSecret: false, description: 'Plivo Auth ID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Plivo Auth Token' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'CA', 'GB', 'AU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0065, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 100,
    priority: 5,
  },
  {
    providerId: 'telnyx_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Telnyx Global SMS',
    tagline: 'Private global IP network and multi-carrier wireless messaging platform',
    description: 'Telnyx owns and operates a private, multi-cloud IP network for unparalleled control, low latency, and security.',
    icon: 'router',
    websiteUrl: 'https://telnyx.com',
    documentation: { overview: 'Telnyx Messaging API v2.', docsUrl: 'https://developers.telnyx.com/docs/v2/messaging' },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'Telnyx LLC',
    tags: ['sms', 'telnyx', 'private-network'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Telnyx API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'CA', 'GB', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0055, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 6,
  },
  {
    providerId: 'bird_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Bird (MessageBird) SMS',
    tagline: 'Global SMS delivery infrastructure with smart queue management',
    description: 'Global SMS delivery through direct operator relationships across Europe, Latin America, and Asia-Pacific.',
    icon: 'send_to_mobile',
    websiteUrl: 'https://bird.com',
    documentation: { overview: 'Bird SMS API.', docsUrl: 'https://docs.bird.com' },
    version: '2.0.0',
    apiVersion: 'v1',
    author: 'Bird Inc.',
    tags: ['sms', 'bird', 'messagebird', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKey', label: 'Access Key', type: 'password', required: true, isSecret: true, description: 'Bird Access Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['EU', 'US', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0075, currency: 'EUR' },
    slaUptimePercent: 99.9,
    maxRps: 80,
    priority: 7,
  },
  {
    providerId: 'clicksend_sms',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'ClickSend Global SMS',
    tagline: 'Multi-channel communications platform with reliable SMS delivery in APAC',
    description: 'Australian and global SMS gateway supporting transactional notifications, two-way SMS, and rich RCS messages.',
    icon: 'mark_email_read',
    websiteUrl: 'https://www.clicksend.com',
    documentation: { overview: 'ClickSend SMS API.', docsUrl: 'https://developers.clicksend.com' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'ClickSend Ltd.',
    tags: ['sms', 'clicksend', 'apac', 'australia'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'username', label: 'Username', type: 'string', required: true, isSecret: false, description: 'ClickSend Username' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'ClickSend API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_SMS'],
    supportedCurrencies: ['AUD', 'USD'],
    supportedCountries: ['AU', 'NZ', 'US', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.008, currency: 'AUD' },
    slaUptimePercent: 99.8,
    maxRps: 50,
    priority: 8,
  },

  // =========================================================================
  // 3. EMAIL PROVIDERS (8 PROVIDERS)
  // =========================================================================
  {
    providerId: 'resend',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'Resend',
    tagline: 'Next-generation modern email platform designed for high developer productivity',
    description: 'Ultra-fast email delivery with built-in React Email support, domain verification, and high deliverability scores.',
    icon: 'mail',
    websiteUrl: 'https://resend.com',
    documentation: {
      overview: 'Resend modern transactional email API.',
      docsUrl: 'https://resend.com/docs',
      setupGuide: 'Generate an API key in Resend Dashboard and verify custom sending domain DKIM/SPF.',
      supportEmail: 'support@resend.com',
    },
    version: '3.2.0',
    apiVersion: 'v1',
    author: 'Resend Inc.',
    tags: ['email', 'resend', 'developer-friendly', 'transactional'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Resend API Key (re_...)' },
      { key: 'fromEmail', label: 'From Email Address', type: 'string', required: false, isSecret: false, description: 'Verified sender email (e.g. bookings@drivego.in)' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'EMAIL_ATTACHMENT', 'EMAIL_HTML', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'IN', 'EU', 'GB', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0006, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 1,
    fallbackProviderId: 'sendgrid',
  },
  {
    providerId: 'sendgrid',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'SendGrid (Twilio)',
    tagline: 'Industry-standard cloud email delivery infrastructure processing 100B+ emails monthly',
    description: 'Trusted email platform for mission-critical transactional notifications, invoices, and automated lifecycle marketing.',
    icon: 'outgoing_mail',
    websiteUrl: 'https://sendgrid.com',
    documentation: { overview: 'SendGrid v3 Mail Send API.', docsUrl: 'https://docs.sendgrid.com/api-reference/mail-send' },
    version: '3.0.0',
    apiVersion: 'v3',
    author: 'Twilio SendGrid',
    tags: ['email', 'sendgrid', 'twilio', 'transactional', 'high-volume'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'SendGrid API Key (SG....)' },
      { key: 'fromEmail', label: 'From Email', type: 'string', required: true, isSecret: false, description: 'Verified Sender Email' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'EMAIL_ATTACHMENT', 'EMAIL_HTML', 'EMAIL_TEMPLATE', 'DELIVERY_STATUS', 'DELIVERY_WEBHOOK'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'IN', 'EU', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.ADAPTER_IMPLEMENTED,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0007, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 200,
    priority: 2,
    fallbackProviderId: 'amazon_ses',
  },
  {
    providerId: 'amazon_ses',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'Amazon Simple Email Service (SES)',
    tagline: 'High-scale, cost-effective transactional and marketing email service on AWS',
    description: 'Reliable, cost-efficient cloud email service built on Amazon AWS infrastructure with dedicated IP pool capabilities.',
    icon: 'cloud',
    websiteUrl: 'https://aws.amazon.com/ses',
    documentation: { overview: 'AWS SES v2 API.', docsUrl: 'https://docs.aws.amazon.com/ses' },
    version: '2.0.0',
    apiVersion: '2019-09-27',
    author: 'Amazon Web Services',
    tags: ['email', 'aws', 'ses', 'cost-effective', 'cloud'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKeyId', label: 'AWS Access Key ID', type: 'string', required: true, isSecret: false, description: 'IAM User Access Key' },
      { key: 'secretAccessKey', label: 'AWS Secret Access Key', type: 'password', required: true, isSecret: true, description: 'IAM User Secret' },
      { key: 'region', label: 'AWS Region', type: 'string', required: true, isSecret: false, description: 'e.g. ap-south-1' },
      { key: 'fromEmail', label: 'From Email', type: 'string', required: true, isSecret: false, description: 'Verified SES Identity' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'EMAIL_ATTACHMENT', 'EMAIL_HTML', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'IN', 'EU', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0001, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 300,
    priority: 3,
  },
  {
    providerId: 'mailgun',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'Mailgun',
    tagline: 'Transactional email API built for software development teams with powerful deliverability tools',
    description: 'Advanced email automation service offering email validation, intelligent routing, and suppression lists.',
    icon: 'forward_to_inbox',
    websiteUrl: 'https://www.mailgun.com',
    documentation: { overview: 'Mailgun v3 API.', docsUrl: 'https://documentation.mailgun.com' },
    version: '3.0.0',
    apiVersion: 'v3',
    author: 'Sinch / Mailgun',
    tags: ['email', 'mailgun', 'transactional'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Mailgun Private Key' },
      { key: 'domain', label: 'Domain', type: 'string', required: true, isSecret: false, description: 'Sending Domain (e.g. mail.drivego.in)' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'EMAIL_ATTACHMENT', 'EMAIL_HTML', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'EU', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0008, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 150,
    priority: 4,
  },
  {
    providerId: 'postmark',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'Postmark',
    tagline: 'Ultra-fast transactional email with distinct servers for transactional and promotional traffic',
    description: 'Industry benchmark for transactional delivery speed, boasting 99%+ inbox arrival within seconds.',
    icon: 'speed',
    websiteUrl: 'https://postmarkapp.com',
    documentation: { overview: 'Postmark API.', docsUrl: 'https://postmarkapp.com/developer' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'ActiveCampaign / Postmark',
    tags: ['email', 'postmark', 'fastest-inbox', 'transactional'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'serverToken', label: 'Server API Token', type: 'password', required: true, isSecret: true, description: 'Postmark Server Token' },
      { key: 'fromEmail', label: 'From Email', type: 'string', required: true, isSecret: false, description: 'Sender Signature Email' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'EMAIL_ATTACHMENT', 'EMAIL_HTML', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'EU', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0012, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 100,
    priority: 5,
  },
  {
    providerId: 'sparkpost',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'SparkPost',
    tagline: 'Enterprise email sending and analytics platform for high-volume corporate senders',
    description: 'Enterprise email delivery engine powering 37% of the world’s B2C email with deep deliverability analytics.',
    icon: 'analytics',
    websiteUrl: 'https://www.sparkpost.com',
    documentation: { overview: 'SparkPost API.', docsUrl: 'https://developers.sparkpost.com' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'MessageBird / SparkPost',
    tags: ['email', 'sparkpost', 'enterprise', 'high-volume'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'SparkPost API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0009, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 150,
    priority: 6,
  },
  {
    providerId: 'brevo',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'Brevo (Sendinblue)',
    tagline: 'Unified European CRM and transactional email suite with GDPR compliance',
    description: 'European-hosted email delivery platform with strict GDPR compliance and drag-and-drop template editors.',
    icon: 'mark_email_unread',
    websiteUrl: 'https://www.brevo.com',
    documentation: { overview: 'Brevo API v3.', docsUrl: 'https://developers.brevo.com' },
    version: '3.0.0',
    apiVersion: 'v3',
    author: 'Brevo SAS',
    tags: ['email', 'brevo', 'sendinblue', 'gdpr', 'europe'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Brevo v3 API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL', 'EMAIL_HTML', 'DELIVERY_STATUS'],
    supportedCurrencies: ['EUR', 'USD'],
    supportedCountries: ['FR', 'EU', 'DE', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0007, currency: 'EUR' },
    slaUptimePercent: 99.9,
    maxRps: 100,
    priority: 7,
  },
  {
    providerId: 'mailersend',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'MailerSend',
    tagline: 'Modern transactional email service for cloud applications and developers',
    description: 'Clean REST API for transactional emails, SMS, and inbound webhooks by the creators of MailerLite.',
    icon: 'mail_outline',
    websiteUrl: 'https://www.mailersend.com',
    documentation: { overview: 'MailerSend API.', docsUrl: 'https://developers.mailersend.com' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'MailerSend Inc.',
    tags: ['email', 'mailersend', 'transactional'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiToken', label: 'API Token', type: 'password', required: true, isSecret: true, description: 'MailerSend API Token' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_EMAIL'],
    supportedCurrencies: ['USD', 'EUR'],
    supportedCountries: ['US', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0006, currency: 'USD' },
    slaUptimePercent: 99.8,
    maxRps: 80,
    priority: 8,
  },

  // =========================================================================
  // 4. PUSH NOTIFICATION PROVIDERS (4 PROVIDERS)
  // =========================================================================
  {
    providerId: 'fcm',
    category: IntegrationCategory.MESSAGING_PUSH,
    name: 'Firebase Cloud Messaging (FCM)',
    tagline: 'Cross-platform push notifications for Android, iOS, and Web by Google',
    description: 'Industry standard for real-time mobile push notifications with device token management, topic broadcasting, and priority queues.',
    icon: 'notifications_active',
    websiteUrl: 'https://firebase.google.com/docs/cloud-messaging',
    documentation: {
      overview: 'FCM HTTP v1 API with service account credentials.',
      docsUrl: 'https://firebase.google.com/docs/cloud-messaging',
      setupGuide: 'Download Firebase Service Account JSON key from Google Cloud Console.',
      supportEmail: 'firebase-support@google.com',
    },
    version: 'v1',
    apiVersion: 'v1',
    author: 'Google LLC',
    tags: ['push', 'fcm', 'firebase', 'android', 'ios', 'web'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'projectId', label: 'Project ID', type: 'string', required: true, isSecret: false, description: 'Google Cloud Project ID' },
      { key: 'clientEmail', label: 'Client Email', type: 'string', required: true, isSecret: false, description: 'Service Account Email' },
      { key: 'privateKey', label: 'Private Key', type: 'password', required: true, isSecret: true, description: 'Service Account RSA Private Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_PUSH', 'SEND_UNICAST', 'SEND_MULTICAST', 'SEND_TOPIC', 'DATA_PAYLOAD'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['GLOBAL'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 500,
    priority: 1,
    fallbackProviderId: 'onesignal',
  },
  {
    providerId: 'onesignal',
    category: IntegrationCategory.MESSAGING_PUSH,
    name: 'OneSignal',
    tagline: 'Omnichannel customer engagement platform with intelligent push notification routing',
    description: 'High-scale push notification platform supporting intelligent delivery scheduling, automated segments, and rich media push.',
    icon: 'campaign',
    websiteUrl: 'https://onesignal.com',
    documentation: { overview: 'OneSignal REST API.', docsUrl: 'https://documentation.onesignal.com/reference' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'OneSignal Inc.',
    tags: ['push', 'onesignal', 'mobile', 'web', 'rich-push'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'appId', label: 'App ID', type: 'string', required: true, isSecret: false, description: 'OneSignal App ID' },
      { key: 'restApiKey', label: 'REST API Key', type: 'password', required: true, isSecret: true, description: 'OneSignal REST API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_PUSH', 'SEND_UNICAST', 'SEND_MULTICAST', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['GLOBAL'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.ADAPTER_IMPLEMENTED,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.0001, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 200,
    priority: 2,
    fallbackProviderId: 'amazon_sns',
  },
  {
    providerId: 'amazon_sns',
    category: IntegrationCategory.MESSAGING_PUSH,
    name: 'Amazon SNS Mobile Push',
    tagline: 'High-throughput publish/subscribe mobile push notification service on AWS',
    description: 'Fully managed pub/sub messaging service directly routing to APNs, FCM, and Baidu for enterprise mobile fleets.',
    icon: 'sensors',
    websiteUrl: 'https://aws.amazon.com/sns',
    documentation: { overview: 'AWS SNS Mobile Push documentation.', docsUrl: 'https://docs.aws.amazon.com/sns' },
    version: '2.0.0',
    apiVersion: '2010-03-31',
    author: 'Amazon Web Services',
    tags: ['push', 'aws', 'sns', 'pubsub'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKeyId', label: 'AWS Access Key ID', type: 'string', required: true, isSecret: false, description: 'IAM Access Key' },
      { key: 'secretAccessKey', label: 'AWS Secret Access Key', type: 'password', required: true, isSecret: true, description: 'IAM Secret' },
      { key: 'region', label: 'AWS Region', type: 'string', required: true, isSecret: false, description: 'e.g. ap-south-1' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_PUSH', 'SEND_UNICAST', 'SEND_TOPIC'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['GLOBAL'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.00005, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 500,
    priority: 3,
  },
  {
    providerId: 'airship',
    category: IntegrationCategory.MESSAGING_PUSH,
    name: 'Airship (Urban Airship)',
    tagline: 'Enterprise customer engagement mobile platform with deep behavioral triggers',
    description: 'Pioneer in mobile app push notifications with predictive send times, in-app automation, and deep geofence triggers.',
    icon: 'flight',
    websiteUrl: 'https://www.airship.com',
    documentation: { overview: 'Airship API docs.', docsUrl: 'https://docs.airship.com' },
    version: '1.0.0',
    apiVersion: 'v3',
    author: 'Airship Group Inc.',
    tags: ['push', 'airship', 'enterprise', 'geofence'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'appKey', label: 'App Key', type: 'string', required: true, isSecret: false, description: 'Airship App Key' },
      { key: 'masterSecret', label: 'Master Secret', type: 'password', required: true, isSecret: true, description: 'Airship Master Secret' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'SEND_PUSH', 'DELIVERY_STATUS'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['GLOBAL'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.0002, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 4,
  },

  // =========================================================================
  // 5. VOICE & VOICE OTP PROVIDERS (5 PROVIDERS)
  // =========================================================================
  {
    providerId: 'twilio_voice',
    category: IntegrationCategory.VOICE_IVR,
    name: 'Twilio Programmable Voice & Voice OTP',
    tagline: 'Global cloud telephony with automated voice calling, IVR, and speech synthesis',
    description: 'Carrier-grade programmable voice calls with automated text-to-speech, fallback OTP playback, and DTMF gathering.',
    icon: 'record_voice_over',
    websiteUrl: 'https://www.twilio.com/voice',
    documentation: {
      overview: 'Twilio Programmable Voice API with TwiML instructions.',
      docsUrl: 'https://www.twilio.com/docs/voice',
      setupGuide: 'Provision voice-enabled phone number and set webhook callback URL for call progress events.',
      supportEmail: 'support@twilio.com',
    },
    version: '2024-05',
    apiVersion: '2010-04-01',
    author: 'Twilio Inc.',
    tags: ['voice', 'twilio', 'voice-otp', 'ivr', 'speech'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accountSid', label: 'Account SID', type: 'string', required: true, isSecret: false, description: 'Twilio Account SID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Twilio Auth Token' },
      { key: 'fromNumber', label: 'Caller ID Phone Number', type: 'string', required: true, isSecret: false, description: 'Verified Voice Phone Number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'VOICE_CALL', 'VOICE_OTP', 'SEND_OTP', 'DELIVERY_STATUS', 'DELIVERY_WEBHOOK'],
    supportedCurrencies: ['USD', 'INR', 'EUR'],
    supportedCountries: ['US', 'IN', 'GB', 'EU', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.ADAPTER_IMPLEMENTED,
    adapterImplemented: true,
    costModel: { percentageFee: 0, fixedFee: 0.015, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 1,
    fallbackProviderId: 'exotel_voice',
  },
  {
    providerId: 'exotel_voice',
    category: IntegrationCategory.VOICE_IVR,
    name: 'Exotel Voice & Telephony',
    tagline: 'Leading Indian cloud telephony platform with automated outbound calling and masked calls',
    description: 'High-availability voice infrastructure powering customer-vendor number masking, automated pickup alerts, and voice OTP.',
    icon: 'phone_in_talk',
    websiteUrl: 'https://exotel.com',
    documentation: { overview: 'Exotel Voice API.', docsUrl: 'https://developer.exotel.com/api' },
    version: '2.0.0',
    apiVersion: 'v1',
    author: 'Exotel Techcom Pvt Ltd',
    tags: ['voice', 'exotel', 'india', 'number-masking', 'voice-otp'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'string', required: true, isSecret: false, description: 'Exotel API Key' },
      { key: 'apiToken', label: 'API Token', type: 'password', required: true, isSecret: true, description: 'Exotel API Token' },
      { key: 'subDomain', label: 'Subdomain', type: 'string', required: true, isSecret: false, description: 'Exotel Subdomain' },
      { key: 'callerId', label: 'ExoPhone Caller ID', type: 'string', required: true, isSecret: false, description: 'Virtual Caller Phone Number' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'VOICE_CALL', 'VOICE_OTP', 'SEND_OTP'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.75, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 100,
    priority: 2,
    fallbackProviderId: 'vonage_voice',
  },
  {
    providerId: 'vonage_voice',
    category: IntegrationCategory.VOICE_IVR,
    name: 'Vonage Voice API',
    tagline: 'Global Voice API with text-to-speech in 40+ languages and call control objects',
    description: 'High-definition voice calling with NCCO control objects, automated call recording, and global PSTN termination.',
    icon: 'voicemail',
    websiteUrl: 'https://www.vonage.com',
    documentation: { overview: 'Vonage Voice API.', docsUrl: 'https://developer.vonage.com/voice/voice-api/overview' },
    version: '1.2.0',
    apiVersion: 'v1',
    author: 'Vonage',
    tags: ['voice', 'vonage', 'global', 'tts'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'applicationId', label: 'Application ID', type: 'string', required: true, isSecret: false, description: 'Vonage Application UUID' },
      { key: 'privateKey', label: 'Private Key', type: 'password', required: true, isSecret: true, description: 'Vonage RSA Private Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'VOICE_CALL', 'VOICE_OTP'],
    supportedCurrencies: ['USD', 'EUR'],
    supportedCountries: ['US', 'EU', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.014, currency: 'EUR' },
    slaUptimePercent: 99.9,
    maxRps: 80,
    priority: 3,
  },
  {
    providerId: 'plivo_voice',
    category: IntegrationCategory.VOICE_IVR,
    name: 'Plivo Voice API',
    tagline: 'Scalable and economical programmable voice calling across global telecom carriers',
    description: 'Plivo Voice API with XML-based call flow logic, dynamic conference calls, and high-clarity voice alerts.',
    icon: 'hearing',
    websiteUrl: 'https://www.plivo.com',
    documentation: { overview: 'Plivo Voice API.', docsUrl: 'https://www.plivo.com/docs/voice' },
    version: '1.0.0',
    apiVersion: 'v1',
    author: 'Plivo Inc.',
    tags: ['voice', 'plivo', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'authId', label: 'Auth ID', type: 'string', required: true, isSecret: false, description: 'Plivo Auth ID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Plivo Auth Token' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'VOICE_CALL', 'VOICE_OTP'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'CA', 'GB'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CONTRACT_VALIDATED,
    implementationStatus: ProviderImplementationStatus.CONTRACT_READY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.012, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 80,
    priority: 4,
  },
  {
    providerId: 'telnyx_voice',
    category: IntegrationCategory.VOICE_IVR,
    name: 'Telnyx Programmable Voice',
    tagline: 'Private IP network carrier-grade voice calling and TeXML call control',
    description: 'Direct global voice termination with real-time audio streaming, speech-to-text, and automated notification playback.',
    icon: 'phone_forwarded',
    websiteUrl: 'https://telnyx.com',
    documentation: { overview: 'Telnyx Voice API.', docsUrl: 'https://developers.telnyx.com/docs/v2/voice' },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'Telnyx LLC',
    tags: ['voice', 'telnyx', 'carrier-direct'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Telnyx API Key' },
    ],
    supportedCapabilities: ['SEND_MESSAGE', 'VOICE_CALL'],
    supportedCurrencies: ['USD'],
    supportedCountries: ['US', 'CA', 'GB', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    costModel: { percentageFee: 0, fixedFee: 0.010, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 100,
    priority: 5,
  },
];
