import { IntegrationCategory } from '../registry/provider.types';
import {
  CatalogProviderMetadata,
  ProviderActivationState,
  ProviderEnvironment,
  ProviderLifecycleState,
  ProviderCertificationLevel,
  ProviderImplementationStatus,
} from './provider-catalog.types';

export const ENTERPRISE_EXPANDED_PROVIDERS: CatalogProviderMetadata[] = [
  // =========================================================================
  // INDIAN PAYMENT GATEWAYS
  // =========================================================================
  {
    providerId: 'ccavenue',
    category: IntegrationCategory.PAYMENT,
    name: 'CCAvenue',
    tagline: 'Pioneer multi-currency payment gateway for Indian commerce',
    description:
      'Robust payment gateway featuring 200+ payment options, netbanking across 55+ Indian banks, and dynamic multi-currency processing.',
    icon: 'payment',
    websiteUrl: 'https://ccavenue.com',
    documentation: {
      overview: 'Enterprise payment routing with extensive net banking and card coverage.',
      docsUrl: 'https://dashboard.ccavenue.com/documentation',
      setupGuide: 'Configure Merchant ID, Access Code, and Working Key from CCAvenue dashboard.',
      supportEmail: 'service@ccavenue.com',
    },
    version: '2.4.0',
    apiVersion: 'v2',
    author: 'Infibeam Avenues Ltd.',
    tags: ['payments', 'netbanking', 'india', 'cards'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'CCAvenue Merchant ID' },
      { key: 'accessCode', label: 'Access Code', type: 'string', required: true, isSecret: false, description: 'CCAvenue Access Code' },
      { key: 'workingKey', label: 'Working Key', type: 'password', required: true, isSecret: true, description: 'CCAvenue Working Encryption Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'NET_BANKING',
      'CARD',
      'UPI',
      'EMI',
    ],
    supportedCurrencies: ['INR', 'USD', 'AED', 'SGD', 'EUR'],
    supportedCountries: ['IN', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 85,
    supportedPaymentMethods: ['NET_BANKING', 'CREDIT_CARD', 'DEBIT_CARD', 'UPI', 'WALLET'],
    costModel: { percentageFee: 1.95, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.85,
    maxRps: 100,
  },
  {
    providerId: 'billdesk',
    category: IntegrationCategory.PAYMENT,
    name: 'BillDesk',
    tagline: 'Tier-1 enterprise banking aggregation & recurring mandate infrastructure',
    description:
      'Deep integration with major public and private sector banks in India, optimizing large-ticket and enterprise fleet corporate accounts.',
    icon: 'account_balance',
    websiteUrl: 'https://billdesk.com',
    documentation: {
      overview: 'High-throughput enterprise payment orchestration.',
      docsUrl: 'https://developer.billdesk.com',
      setupGuide: 'Obtain Client ID, Secret, and HMAC Signing Keys from BillDesk onboarding.',
    },
    version: '1.9.2',
    apiVersion: 'v1.2',
    author: 'IndiaIdeas.com Ltd.',
    tags: ['payments', 'mandates', 'india', 'banking'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'clientId', label: 'Client ID', type: 'string', required: true, isSecret: false, description: 'BillDesk Client ID' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'BillDesk HMAC Secret' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'RECURRING_PAYMENTS',
      'NET_BANKING',
      'UPI',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 88,
    supportedPaymentMethods: ['NET_BANKING', 'UPI', 'DEBIT_CARD', 'MANDATES'],
    costModel: { percentageFee: 1.85, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'juspay',
    category: IntegrationCategory.PAYMENT,
    name: 'Juspay HyperSDK',
    tagline: 'Unified payment orchestration and intelligent 1-click UPI router',
    description:
      'High-performance payment gateway switch optimizing payment success rates via dynamic gateway routing and native mobile checkout flows.',
    icon: 'bolt',
    websiteUrl: 'https://juspay.in',
    documentation: {
      overview: 'Smart payment routing layer and SDK for seamless mobile checkout.',
      docsUrl: 'https://developer.juspay.in',
      setupGuide: 'Configure Merchant ID and API Key in Juspay dashboard.',
    },
    version: '3.1.0',
    apiVersion: 'v2',
    author: 'Juspay Technologies Pvt Ltd',
    tags: ['payments', 'orchestration', 'upi', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Juspay Merchant ID' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Juspay API Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'UPI_INTENT',
      'UPI_COLLECT',
      'TOKENIZATION',
      'ROUTE_SPLIT',
      'RECONCILIATION',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 82,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING'],
    costModel: { percentageFee: 1.75, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.98,
    maxRps: 250,
  },
  {
    providerId: 'easebuzz',
    category: IntegrationCategory.PAYMENT,
    name: 'Easebuzz',
    tagline: 'API-first payment gateway & virtual account automated collection suite',
    description:
      'Specialized payment processor providing seamless split payments, instant vendor onboarding, and automated security deposit escrow.',
    icon: 'flash_on',
    websiteUrl: 'https://easebuzz.in',
    documentation: {
      overview: 'API-driven payment gateway with sub-merchant collections.',
      docsUrl: 'https://docs.easebuzz.in',
      setupGuide: 'Enter Merchant Key and Salt from Easebuzz dashboard.',
    },
    version: '2.0.0',
    apiVersion: 'v1',
    author: 'Easebuzz Pvt Ltd',
    tags: ['payments', 'escrow', 'split', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantKey', label: 'Merchant Key', type: 'string', required: true, isSecret: false, description: 'Easebuzz Key' },
      { key: 'merchantSalt', label: 'Merchant Salt', type: 'password', required: true, isSecret: true, description: 'Easebuzz Salt' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'SPLIT_PAYMENTS',
      'UPI',
      'INSTANT_REFUND',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 86,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'WALLET'],
    costModel: { percentageFee: 1.89, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 120,
  },
  {
    providerId: 'paytm_pg',
    category: IntegrationCategory.PAYMENT,
    name: 'Paytm Payment Gateway',
    tagline: 'Consumer wallet and high-trust UPI checkout in India',
    description:
      'Seamless checkout experience leveraging Paytm Wallet, Postpaid BNPL, and Paytm UPI payments.',
    icon: 'wallet',
    websiteUrl: 'https://business.paytm.com',
    documentation: {
      overview: 'Paytm payment processing with high brand recall in India.',
      docsUrl: 'https://developer.paytm.com/docs',
      setupGuide: 'Obtain Merchant ID (MID) and Merchant Key from Paytm for Business portal.',
    },
    version: '3.0.1',
    apiVersion: 'v2',
    author: 'One97 Communications Ltd.',
    tags: ['payments', 'wallet', 'bnpl', 'upi', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID (MID)', type: 'string', required: true, isSecret: false, description: 'Paytm MID' },
      { key: 'merchantKey', label: 'Merchant Key', type: 'password', required: true, isSecret: true, description: 'Paytm Secret Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'WALLET',
      'BNPL',
      'UPI',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 84,
    supportedPaymentMethods: ['WALLET', 'UPI', 'BNPL', 'CREDIT_CARD', 'DEBIT_CARD'],
    costModel: { percentageFee: 1.99, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.88,
    maxRps: 150,
  },
  {
    providerId: 'worldline',
    category: IntegrationCategory.PAYMENT,
    name: 'Worldline India',
    tagline: 'Global enterprise payment leader with domestic acquiring capabilities',
    description:
      'Unified enterprise checkout platform supporting physical terminal integration, POS, and digital payment rails.',
    icon: 'point_of_sale',
    websiteUrl: 'https://worldline.com',
    documentation: {
      overview: 'Enterprise payment processing for vehicle rental hubs.',
      docsUrl: 'https://docs.worldline.com',
      setupGuide: 'Configure Terminal ID and Merchant Key from Worldline back-office.',
    },
    version: '4.2.0',
    apiVersion: 'v2',
    author: 'Worldline Global',
    tags: ['payments', 'enterprise', 'pos', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantCode', label: 'Merchant Code', type: 'string', required: true, isSecret: false, description: 'Worldline Merchant Code' },
      { key: 'encryptionKey', label: 'Encryption Key', type: 'password', required: true, isSecret: true, description: 'Worldline AES Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'CARD'],
    supportedCurrencies: ['INR', 'USD', 'EUR'],
    supportedCountries: ['IN', 'FR', 'DE'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 92,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING'],
    costModel: { percentageFee: 2.1, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 100,
  },
  {
    providerId: 'pinelabs',
    category: IntegrationCategory.PAYMENT,
    name: 'Pine Labs Plural',
    tagline: 'Multi-tender payment gateway with integrated EMI & brand offers',
    description:
      'Omni-channel payment gateway enabling high-value vehicle security deposit pre-authorization and low-cost EMI plans.',
    icon: 'credit_card',
    websiteUrl: 'https://pinelabs.com',
    documentation: {
      overview: 'Plural Gateway by Pine Labs for enterprise automotive & mobility.',
      docsUrl: 'https://pluralonline.com/docs',
      setupGuide: 'Configure Merchant ID and API Key from Plural Dashboard.',
    },
    version: '2.1.0',
    apiVersion: 'v1',
    author: 'Pine Labs Pvt Ltd',
    tags: ['payments', 'emi', 'preauth', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Pine Labs Merchant ID' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Plural API Secret Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'EMI',
      'CAPTURE',
      'CARD',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN', 'MY', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 91,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'EMI', 'UPI'],
    costModel: { percentageFee: 1.95, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.92,
    maxRps: 120,
  },
  {
    providerId: 'zaakpay',
    category: IntegrationCategory.PAYMENT,
    name: 'Zaakpay',
    tagline: 'Reliable checkout solutions by MobiKwik',
    description:
      'Domestic payment gateway emphasizing mobile wallet checkout and high-availability UPI conversion.',
    icon: 'payment',
    websiteUrl: 'https://zaakpay.com',
    documentation: {
      overview: 'Zaakpay online payment integration.',
      docsUrl: 'https://zaakpay.com/developers',
      setupGuide: 'Enter Merchant Identifier and Secret Key.',
    },
    version: '1.5.0',
    apiVersion: 'v1',
    author: 'One Mobikwik Systems Ltd.',
    tags: ['payments', 'wallet', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantIdentifier', label: 'Merchant Identifier', type: 'string', required: true, isSecret: false, description: 'Zaakpay ID' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Zaakpay Secret' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'UPI', 'WALLET'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 95,
    supportedPaymentMethods: ['WALLET', 'UPI', 'CARD'],
    costModel: { percentageFee: 1.9, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.8,
    maxRps: 80,
  },
  {
    providerId: 'openmoney',
    category: IntegrationCategory.PAYMENT,
    name: 'Open Money',
    tagline: 'Connected neo-banking and automated vendor payouts',
    description:
      'Seamless business financial infrastructure offering integrated payment gateway and automated vendor payout disbursals.',
    icon: 'account_balance_wallet',
    websiteUrl: 'https://open.money',
    documentation: {
      overview: 'Connected banking and payment gateway for mobility operators.',
      docsUrl: 'https://open.money/developers',
      setupGuide: 'Enter API Key and Secret from Open dashboard.',
    },
    version: '1.2.0',
    apiVersion: 'v1',
    author: 'Open Financial Technologies Pvt Ltd',
    tags: ['payments', 'neobank', 'payouts', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'string', required: true, isSecret: false, description: 'Open API Key' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Open Secret' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'PAYOUTS'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 94,
    supportedPaymentMethods: ['UPI', 'NET_BANKING', 'CARD', 'PAYOUTS'],
    costModel: { percentageFee: 1.85, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.85,
    maxRps: 100,
  },
  {
    providerId: 'stripe_india',
    category: IntegrationCategory.PAYMENT,
    name: 'Stripe India',
    tagline: 'Localized Stripe processing with domestic INR card & UPI support',
    description:
      'Stripe dedicated Indian entity offering compliance with RBI recurring mandate guidelines and local domestic acquiring.',
    icon: 'payment',
    websiteUrl: 'https://stripe.com/en-in',
    documentation: {
      overview: 'Localized Stripe payment infrastructure for Indian businesses.',
      docsUrl: 'https://stripe.com/docs/india-accept-international-payments',
      setupGuide: 'Use Indian Stripe account credentials.',
    },
    version: '2024-06-20',
    apiVersion: '2024-06-20',
    author: 'Stripe India Pvt Ltd',
    tags: ['payments', 'global-standard', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'publishableKey', label: 'Publishable Key', type: 'string', required: true, isSecret: false, description: 'pk_live_...' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'sk_live_...' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'RECURRING_PAYMENTS',
      'TOKENIZATION',
      'INTERNATIONAL_CARD',
    ],
    supportedCurrencies: ['INR', 'USD', 'EUR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 95,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'INTERNATIONAL_CARD'],
    costModel: { percentageFee: 2.0, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.99,
    maxRps: 200,
  },

  // =========================================================================
  // INTERNATIONAL PAYMENT GATEWAYS
  // =========================================================================
  {
    providerId: 'checkout_com',
    category: IntegrationCategory.PAYMENT,
    name: 'Checkout.com',
    tagline: 'High-performance global payment platform with deep modular acquiring',
    description:
      'Direct acquiring and payment processing across North America, Europe, MENA, and APAC with sub-second tokenization and fraud detection.',
    icon: 'credit_card',
    websiteUrl: 'https://checkout.com',
    documentation: {
      overview: 'Enterprise payment infrastructure with direct scheme integration.',
      docsUrl: 'https://www.checkout.com/docs',
      setupGuide: 'Obtain Public Key and Secret Key from Checkout.com Hub.',
    },
    version: '4.0.0',
    apiVersion: 'v2',
    author: 'Checkout.com',
    tags: ['payments', 'global', 'mena', 'cards'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'publicKey', label: 'Public Key', type: 'string', required: true, isSecret: false, description: 'pk_...' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'sk_...' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'CAPTURE',
      '3DS_SECURE',
      'TOKENIZATION',
    ],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AED', 'SAR', 'SGD'],
    supportedCountries: ['US', 'GB', 'AE', 'SA', 'SG', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 72,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'APPLE_PAY', 'GOOGLE_PAY'],
    costModel: { percentageFee: 2.4, fixedFee: 0.25, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 300,
  },
  {
    providerId: 'paypal',
    category: IntegrationCategory.PAYMENT,
    name: 'PayPal',
    tagline: 'World-renowned consumer wallet and trusted global digital payments',
    description:
      'Global payment platform with 400M+ active accounts across 200 markets, providing trusted international tourist car rental payments.',
    icon: 'payment',
    websiteUrl: 'https://paypal.com',
    documentation: {
      overview: 'PayPal standard checkout and wallet integration.',
      docsUrl: 'https://developer.paypal.com/docs',
      setupGuide: 'Create REST API app in PayPal Developer Dashboard to obtain Client ID and Secret.',
    },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'PayPal Holdings Inc.',
    tags: ['payments', 'global', 'wallet', 'tourist'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'clientId', label: 'Client ID', type: 'string', required: true, isSecret: false, description: 'PayPal Client ID' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, isSecret: true, description: 'PayPal Secret' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'WALLET'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'JPY'],
    supportedCountries: ['US', 'GB', 'EU', 'AU', 'CA', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 74,
    supportedPaymentMethods: ['WALLET', 'CREDIT_CARD', 'PAY_LATER'],
    costModel: { percentageFee: 3.49, fixedFee: 0.49, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 200,
  },
  {
    providerId: 'braintree',
    category: IntegrationCategory.PAYMENT,
    name: 'Braintree',
    tagline: 'PayPal-backed developer-first mobile checkout and vaulting platform',
    description:
      'Seamless full-stack payments covering cards, PayPal, Apple Pay, and Google Pay with advanced credit card tokenization.',
    icon: 'credit_card',
    websiteUrl: 'https://braintreepayments.com',
    documentation: {
      overview: 'Braintree payment gateway documentation.',
      docsUrl: 'https://developer.paypal.com/braintree/docs',
      setupGuide: 'Enter Merchant ID, Public Key, and Private Key from Braintree control panel.',
    },
    version: '3.15.0',
    apiVersion: 'v1',
    author: 'PayPal / Braintree',
    tags: ['payments', 'vaulting', 'mobile', 'cards'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Braintree Merchant ID' },
      { key: 'publicKey', label: 'Public Key', type: 'string', required: true, isSecret: false, description: 'Braintree Public Key' },
      { key: 'privateKey', label: 'Private Key', type: 'password', required: true, isSecret: true, description: 'Braintree Private Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'TOKENIZATION',
      'CARD',
    ],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD'],
    supportedCountries: ['US', 'CA', 'GB', 'EU', 'AU'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 76,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'APPLE_PAY'],
    costModel: { percentageFee: 2.59, fixedFee: 0.49, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 200,
  },
  {
    providerId: 'authorizenet',
    category: IntegrationCategory.PAYMENT,
    name: 'Authorize.Net',
    tagline: 'Visa solution for trusted credit card and eCheck processing',
    description:
      'Long-standing payment gateway standard in North America for secure payment processing, fraud prevention, and recurring billing.',
    icon: 'security',
    websiteUrl: 'https://authorize.net',
    documentation: {
      overview: 'Authorize.Net payment API.',
      docsUrl: 'https://developer.authorize.net',
      setupGuide: 'Enter API Login ID and Transaction Key.',
    },
    version: '2.0.2',
    apiVersion: 'v1',
    author: 'Visa Inc.',
    tags: ['payments', 'visa', 'north-america'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiLoginId', label: 'API Login ID', type: 'string', required: true, isSecret: false, description: 'Login ID' },
      { key: 'transactionKey', label: 'Transaction Key', type: 'password', required: true, isSecret: true, description: 'Transaction Secret' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'CARD'],
    supportedCurrencies: ['USD', 'CAD'],
    supportedCountries: ['US', 'CA'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 87,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'ECHECK'],
    costModel: { percentageFee: 2.9, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'square',
    category: IntegrationCategory.PAYMENT,
    name: 'Square Payments',
    tagline: 'Omni-channel payment gateway and contactless terminal integration',
    description:
      'Integrated in-person hub payments and online reservation processing for modern fleet branches.',
    icon: 'store',
    websiteUrl: 'https://squareup.com',
    documentation: {
      overview: 'Square developer platform.',
      docsUrl: 'https://developer.squareup.com/docs',
      setupGuide: 'Configure Application ID and Access Token from Square Developer Portal.',
    },
    version: '3.0.0',
    apiVersion: '2024-01-18',
    author: 'Block Inc.',
    tags: ['payments', 'in-person', 'terminal', 'cards'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'applicationId', label: 'Application ID', type: 'string', required: true, isSecret: false, description: 'sq0idp-...' },
      { key: 'accessToken', label: 'Access Token', type: 'password', required: true, isSecret: true, description: 'EAAA...' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'CARD'],
    supportedCurrencies: ['USD', 'CAD', 'GBP', 'AUD', 'EUR', 'JPY'],
    supportedCountries: ['US', 'CA', 'GB', 'AU', 'FR', 'JP'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 78,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'APPLE_PAY', 'GOOGLE_PAY'],
    costModel: { percentageFee: 2.6, fixedFee: 0.10, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 180,
  },
  {
    providerId: 'worldpay',
    category: IntegrationCategory.PAYMENT,
    name: 'Worldpay (FIS)',
    tagline: 'Massive global scale acquiring and clearing infrastructure',
    description:
      'Global merchant acquiring supporting 146 countries and 126 currencies with direct card network rails.',
    icon: 'public',
    websiteUrl: 'https://worldpay.com',
    documentation: {
      overview: 'Enterprise multi-currency payment platform.',
      docsUrl: 'https://developer.worldpay.com',
      setupGuide: 'Configure Merchant Code and Service Key.',
    },
    version: '5.0.0',
    apiVersion: 'v1',
    author: 'FIS Worldpay',
    tags: ['payments', 'enterprise', 'multi-currency'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantCode', label: 'Merchant Code', type: 'string', required: true, isSecret: false, description: 'Worldpay Merchant Code' },
      { key: 'serviceKey', label: 'Service Key', type: 'password', required: true, isSecret: true, description: 'Worldpay Secret Service Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'CARD',
      'INTERNATIONAL_CARD',
    ],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AED', 'SGD', 'CAD'],
    supportedCountries: ['US', 'GB', 'EU', 'AE', 'SG', 'CA'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 89,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'INTERNATIONAL_CARD'],
    costModel: { percentageFee: 2.2, fixedFee: 0.20, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 250,
  },
  {
    providerId: 'mollie',
    category: IntegrationCategory.PAYMENT,
    name: 'Mollie',
    tagline: 'Leading European payments platform with high conversion localized checkouts',
    description:
      'Seamless localized checkout across Europe supporting iDEAL, Bancontact, SOFORT, Cartes Bancaires, and SEPA direct debit.',
    icon: 'euro',
    websiteUrl: 'https://mollie.com',
    documentation: {
      overview: 'European payments powerhouse.',
      docsUrl: 'https://docs.mollie.com',
      setupGuide: 'Obtain API Key (test_... or live_...) from Mollie dashboard.',
    },
    version: '2.8.0',
    apiVersion: 'v2',
    author: 'Mollie B.V.',
    tags: ['payments', 'europe', 'ideal', 'sepa'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Mollie API Key (live_...)' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'CARD'],
    supportedCurrencies: ['EUR', 'GBP', 'USD', 'CHF'],
    supportedCountries: ['NL', 'BE', 'DE', 'FR', 'GB', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 83,
    supportedPaymentMethods: ['IDEAL', 'BANCONTACT', 'CREDIT_CARD', 'SOFORT'],
    costModel: { percentageFee: 1.8, fixedFee: 0.25, currency: 'EUR' },
    slaUptimePercent: 99.95,
    maxRps: 150,
  },
  {
    providerId: 'paystack',
    category: IntegrationCategory.PAYMENT,
    name: 'Paystack',
    tagline: 'Modern payment gateway for African commerce and international cards',
    description:
      'High-conversion checkout supporting cards, bank transfers, USSD, and mobile money across Nigeria, Ghana, South Africa, and Kenya.',
    icon: 'payments',
    websiteUrl: 'https://paystack.com',
    documentation: {
      overview: 'Paystack payments platform documentation.',
      docsUrl: 'https://paystack.com/docs',
      setupGuide: 'Obtain Secret Key and Public Key from Paystack Dashboard.',
    },
    version: '2.0.0',
    apiVersion: 'v1',
    author: 'Paystack / Stripe',
    tags: ['payments', 'africa', 'nigeria', 'south-africa', 'kenya', 'cards', 'bank-transfer'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'sk_live_... / sk_test_...' },
      { key: 'publicKey', label: 'Public Key', type: 'string', required: true, isSecret: false, description: 'pk_live_... / pk_test_...' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'CARD', 'BANK_TRANSFER'],
    supportedCurrencies: ['NGN', 'GHS', 'ZAR', 'KES', 'USD'],
    supportedCountries: ['NG', 'GH', 'ZA', 'KE'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 81,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'USSD'],
    costModel: { percentageFee: 1.5, fixedFee: 100, currency: 'NGN' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'airwallex',
    category: IntegrationCategory.PAYMENT,
    name: 'Airwallex',
    tagline: 'Global multi-currency financial infrastructure and cross-border payment acceptance',
    description:
      'Global treasury, zero-markup foreign exchange conversion, and localized checkout for multinational mobility platforms.',
    icon: 'swap_horiz',
    websiteUrl: 'https://airwallex.com',
    documentation: {
      overview: 'Multi-currency payment acceptance and global payout rails.',
      docsUrl: 'https://www.airwallex.com/docs',
      setupGuide: 'Obtain Client ID and API Key from Airwallex developer portal.',
    },
    version: '3.0.0',
    apiVersion: 'v1',
    author: 'Airwallex Pty Ltd',
    tags: ['payments', 'fx', 'global', 'treasury'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'clientId', label: 'Client ID', type: 'string', required: true, isSecret: false, description: 'Airwallex Client ID' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Airwallex API Key' },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'REFUND_PAYMENT',
      'PAYOUTS',
      'MULTI_CURRENCY',
    ],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'SGD', 'HKD', 'AED'],
    supportedCountries: ['US', 'GB', 'AU', 'SG', 'HK', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 79,
    supportedPaymentMethods: ['CREDIT_CARD', 'WECHAT_PAY', 'ALIPAY', 'BANK_TRANSFER'],
    costModel: { percentageFee: 2.3, fixedFee: 0.20, currency: 'USD' },
    slaUptimePercent: 99.98,
    maxRps: 200,
  },
  {
    providerId: 'rapyd',
    category: IntegrationCategory.PAYMENT,
    name: 'Rapyd',
    tagline: 'Fintech-as-a-service powering 900+ local payment methods across 100+ countries',
    description:
      'Extensive localized payment collection, e-wallets, bank transfers, and cash payout networks globally.',
    icon: 'language',
    websiteUrl: 'https://rapyd.net',
    documentation: {
      overview: 'Global payments network and payout orchestrator.',
      docsUrl: 'https://docs.rapyd.net',
      setupGuide: 'Enter Access Key and Secret Key from Rapyd Client Portal.',
    },
    version: '2.5.0',
    apiVersion: 'v1',
    author: 'Rapyd Financial Network',
    tags: ['payments', 'fintech', 'local-methods', 'global'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKey', label: 'Access Key', type: 'string', required: true, isSecret: false, description: 'Rapyd Access Key' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Rapyd Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'PAYOUTS'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'SGD', 'INR', 'BRL', 'MXN'],
    supportedCountries: ['US', 'GB', 'SG', 'BR', 'MX', 'IN'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 80,
    supportedPaymentMethods: ['E_WALLET', 'BANK_TRANSFER', 'LOCAL_CARD'],
    costModel: { percentageFee: 2.5, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'dlocal',
    category: IntegrationCategory.PAYMENT,
    name: 'dLocal',
    tagline: 'Emerging markets payment specialist connecting global enterprise to local rails',
    description:
      'Seamless payment acceptance and cross-border disbursements in emerging markets across LATAM, APAC, and Africa.',
    icon: 'south_america',
    websiteUrl: 'https://dlocal.com',
    documentation: {
      overview: 'One dLocal single API for cross-border emerging market payments.',
      docsUrl: 'https://docs.dlocal.com',
      setupGuide: 'Configure Login ID and Secret Key in dLocal merchant dashboard.',
    },
    version: '3.1.0',
    apiVersion: 'v1',
    author: 'dLocal Group Ltd',
    tags: ['payments', 'emerging-markets', 'latam', 'africa'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'loginId', label: 'Login ID', type: 'string', required: true, isSecret: false, description: 'dLocal Login ID' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'dLocal Secret' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'PAYOUTS'],
    supportedCurrencies: ['USD', 'BRL', 'MXN', 'INR', 'NGN', 'ZAR'],
    supportedCountries: ['BR', 'MX', 'AR', 'CO', 'IN', 'NG', 'ZA'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 82,
    supportedPaymentMethods: ['PIX', 'BOLETO', 'LOCAL_CARD', 'OXXO'],
    costModel: { percentageFee: 2.8, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },

  // --- ADDITIONAL INDIAN PAYMENT GATEWAYS ---
  {
    providerId: 'instamojo',
    category: IntegrationCategory.PAYMENT,
    name: 'Instamojo',
    tagline: 'Micro-merchant & digital rental checkout links with instant UPI collection',
    description: 'Instant payment link generation, UPI intent, and digital invoices for car rental deposits and trip extensions.',
    icon: 'link',
    websiteUrl: 'https://instamojo.com',
    documentation: {
      overview: 'Instamojo payment link and checkout API.',
      docsUrl: 'https://docs.instamojo.com',
      setupGuide: 'Obtain Client ID and Client Secret from Instamojo developer portal.',
    },
    version: '1.8.0',
    apiVersion: 'v1.1',
    author: 'Instamojo Technologies Pvt Ltd',
    tags: ['payments', 'links', 'upi', 'india', 'invoices'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'clientId', label: 'Client ID', type: 'string', required: true, isSecret: false, description: 'Instamojo Client ID' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, isSecret: true, description: 'Instamojo Client Secret' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'PAYMENT_LINK', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'UPI_INTENT'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 88,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET'],
    costModel: { percentageFee: 2.0, fixedFee: 3, currency: 'INR' },
    slaUptimePercent: 99.8,
    maxRps: 100,
  },
  {
    providerId: 'safexpay',
    category: IntegrationCategory.PAYMENT,
    name: 'Safexpay',
    tagline: 'White-label omnichannel payment gateway with multi-bank acquiring',
    description: 'Integrated digital checkout supporting cards, UPI 2.0 mandate auto-debit, and BharatQR for roadside car rentals.',
    icon: 'security',
    websiteUrl: 'https://safexpay.com',
    documentation: {
      overview: 'Omnichannel B2B payment gateway.',
      docsUrl: 'https://docs.safexpay.com',
      setupGuide: 'Configure Merchant ID, Merchant Key, and Aggregator Key in settings.',
    },
    version: '2.1.0',
    apiVersion: 'v2',
    author: 'SafexPay Global',
    tags: ['payments', 'white-label', 'upi', 'mandates'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Safexpay Merchant ID' },
      { key: 'merchantKey', label: 'Merchant Key', type: 'password', required: true, isSecret: true, description: 'Safexpay Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'TOKENIZATION', 'RECURRING_PAYMENTS'],
    supportedCurrencies: ['INR', 'AED', 'USD'],
    supportedCountries: ['IN', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 89,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET'],
    costModel: { percentageFee: 1.85, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.85,
    maxRps: 120,
  },
  {
    providerId: 'paykun',
    category: IntegrationCategory.PAYMENT,
    name: 'Paykun',
    tagline: 'Simple, fast, and secure payment gateway for domestic Indian merchants',
    description: 'Fast checkout redirection, UPI intent, and credit/debit card acceptance with instant settlement capabilities.',
    icon: 'payments',
    websiteUrl: 'https://paykun.com',
    documentation: {
      overview: 'Paykun Payment Gateway API integration.',
      docsUrl: 'https://paykun.com/developer',
      setupGuide: 'Provide Merchant ID and Access Token from Paykun account.',
    },
    version: '1.4.0',
    apiVersion: 'v1',
    author: 'Paykun Payment Solutions',
    tags: ['payments', 'india', 'upi', 'cards'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Paykun Merchant ID' },
      { key: 'accessToken', label: 'Access Token', type: 'password', required: true, isSecret: true, description: 'Paykun Access Token' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'UPI_INTENT'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 91,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING'],
    costModel: { percentageFee: 1.75, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.8,
    maxRps: 100,
  },
  {
    providerId: 'atom',
    category: IntegrationCategory.PAYMENT,
    name: 'Atom Technologies (NTT DATA)',
    tagline: 'Institutional multi-bank payment infrastructure for enterprise fleet operations',
    description: 'Direct banking switches with 50+ Indian banks, institutional card processing, and point-of-sale terminal sync.',
    icon: 'account_balance',
    websiteUrl: 'https://atomtech.in',
    documentation: {
      overview: 'Atom / NTT DATA Enterprise Payment Gateway.',
      docsUrl: 'https://atomtech.in/developers',
      setupGuide: 'Configure Login, Password, Product ID, and Hash Keys.',
    },
    version: '3.0.0',
    apiVersion: 'v3',
    author: 'NTT DATA Payment Services India',
    tags: ['payments', 'banking', 'netbanking', 'enterprise'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'login', label: 'Merchant Login', type: 'string', required: true, isSecret: false, description: 'Atom Login ID' },
      { key: 'password', label: 'Merchant Password', type: 'password', required: true, isSecret: true, description: 'Atom Password' },
      { key: 'productId', label: 'Product ID', type: 'string', required: true, isSecret: false, description: 'Atom Product ID' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'NET_BANKING'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 92,
    supportedPaymentMethods: ['NET_BANKING', 'CREDIT_CARD', 'DEBIT_CARD', 'UPI'],
    costModel: { percentageFee: 1.9, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'airpay',
    category: IntegrationCategory.PAYMENT,
    name: 'Airpay Payment Services',
    tagline: 'Integrated financial technology platform offering UPI, QR, and POS terminals',
    description: 'Unified payment collection for vehicle pickup hubs, roadside booking handovers, and in-app trip settlements.',
    icon: 'point_of_sale',
    websiteUrl: 'https://airpay.co.in',
    documentation: {
      overview: 'Airpay unified payment and POS platform.',
      docsUrl: 'https://airpay.co.in/developer',
      setupGuide: 'Enter Merchant ID, Username, and Secret Key.',
    },
    version: '2.3.0',
    apiVersion: 'v2',
    author: 'Airpay Payment Services Pvt Ltd',
    tags: ['payments', 'pos', 'upi', 'qr', 'mobility'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Airpay Merchant ID' },
      { key: 'username', label: 'API Username', type: 'string', required: true, isSecret: false, description: 'Airpay Username' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Airpay Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'UPI_COLLECT', 'QR_CODE'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 93,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET'],
    costModel: { percentageFee: 1.9, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.85,
    maxRps: 120,
  },
  {
    providerId: 'fibe',
    category: IntegrationCategory.PAYMENT,
    name: 'Fibe (EarlySalary)',
    tagline: 'Digital credit line and Buy-Now-Pay-Later for rental mobility bookings',
    description: 'Instant customer credit assessment and flexible installment plans for high-value long-duration vehicle rentals.',
    icon: 'credit_score',
    websiteUrl: 'https://fibe.in',
    documentation: {
      overview: 'Fibe checkout installment financing API.',
      docsUrl: 'https://developer.fibe.in',
      setupGuide: 'Configure Partner Code and Private API Key.',
    },
    version: '1.2.0',
    apiVersion: 'v1',
    author: 'Social Worth Technologies Pvt Ltd',
    tags: ['payments', 'bnpl', 'credit', 'india', 'financing'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'partnerCode', label: 'Partner Code', type: 'string', required: true, isSecret: false, description: 'Fibe Partner Code' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Fibe API Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'EMI'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 94,
    supportedPaymentMethods: ['BNPL', 'EMI'],
    costModel: { percentageFee: 2.5, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.8,
    maxRps: 80,
  },
  {
    providerId: 'zestmoney',
    category: IntegrationCategory.PAYMENT,
    name: 'ZestMoney',
    tagline: 'Cardless EMI and checkout financing for self-drive car reservations',
    description: 'Enable customers without credit cards to book luxury and multi-week rental cars using paperless digital EMIs.',
    icon: 'price_check',
    websiteUrl: 'https://zestmoney.in',
    documentation: {
      overview: 'ZestMoney digital EMI checkout gateway.',
      docsUrl: 'https://developer.zestmoney.in',
      setupGuide: 'Configure Merchant Token and Secret from Zest portal.',
    },
    version: '2.0.0',
    apiVersion: 'v2',
    author: 'Camden Town Technologies Pvt Ltd',
    tags: ['payments', 'emi', 'bnpl', 'cardless-emi'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantToken', label: 'Merchant Token', type: 'string', required: true, isSecret: false, description: 'ZestMerchant Token' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, isSecret: true, description: 'Zest Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'EMI'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    implementationStatus: ProviderImplementationStatus.CATALOG_ONLY,
    adapterImplemented: false,
    priority: 95,
    supportedPaymentMethods: ['BNPL', 'EMI'],
    costModel: { percentageFee: 2.2, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.75,
    maxRps: 80,
  },
  {
    providerId: 'simpl',
    category: IntegrationCategory.PAYMENT,
    name: 'Simpl 1-Tap Checkout',
    tagline: 'Frictionless 1-tap checkout & Pay Later for frequent city car rentals',
    description: 'Underwrites micro-bookings and hourly rentals in 1-tap without OTP delays, settling balances twice monthly.',
    icon: 'touch_app',
    websiteUrl: 'https://getsimpl.com',
    documentation: {
      overview: 'Simpl 1-tap mobile payment gateway integration.',
      docsUrl: 'https://docs.getsimpl.com',
      setupGuide: 'Enter Public Merchant Key and Secret API Key.',
    },
    version: '2.1.0',
    apiVersion: 'v1',
    author: 'One Sigma Technologies Pvt Ltd',
    tags: ['payments', '1-tap', 'bnpl', 'mobility', 'instant'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'publicKey', label: 'Public Key', type: 'string', required: true, isSecret: false, description: 'Simpl Public Key' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Simpl Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'REFUND_PAYMENT'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 96,
    supportedPaymentMethods: ['BNPL', 'WALLET'],
    costModel: { percentageFee: 2.0, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 200,
  },
  {
    providerId: 'lazypay',
    category: IntegrationCategory.PAYMENT,
    name: 'LazyPay (PayU Finance)',
    tagline: 'Instant credit checkout and flexible repayments for urban commuters',
    description: 'Fast credit-backed checkout for quick vehicle handovers with high authorization success and built-in dispute resolution.',
    icon: 'flash_on',
    websiteUrl: 'https://lazypay.in',
    documentation: {
      overview: 'LazyPay PayU credit checkout integration.',
      docsUrl: 'https://developer.lazypay.in',
      setupGuide: 'Configure Merchant Key and Secret Salt.',
    },
    version: '1.9.0',
    apiVersion: 'v2',
    author: 'PayU Payments Private Limited',
    tags: ['payments', 'credit-line', 'bnpl', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantKey', label: 'Merchant Key', type: 'string', required: true, isSecret: false, description: 'LazyPay Merchant Key' },
      { key: 'secretSalt', label: 'Secret Salt', type: 'password', required: true, isSecret: true, description: 'LazyPay Salt' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'REFUND_PAYMENT'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 97,
    supportedPaymentMethods: ['BNPL', 'CREDIT_LINE'],
    costModel: { percentageFee: 2.1, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.85,
    maxRps: 150,
  },

  // --- ADDITIONAL INTERNATIONAL PAYMENT GATEWAYS ---
  {
    providerId: 'klarna',
    category: IntegrationCategory.PAYMENT,
    name: 'Klarna Global',
    tagline: 'Global Buy-Now-Pay-Later and flexible installment platform for travel & automotive',
    description: 'Global checkout integration allowing international tourists to pay in 3 or 4 interest-free installments or 30 days later.',
    icon: 'shopping_bag',
    websiteUrl: 'https://klarna.com',
    documentation: {
      overview: 'Klarna Payments API for travel and rental checkout.',
      docsUrl: 'https://docs.klarna.com',
      setupGuide: 'Obtain API Username and API Password from Klarna Merchant Portal.',
    },
    version: '3.4.0',
    apiVersion: 'v1',
    author: 'Klarna Bank AB',
    tags: ['payments', 'bnpl', 'installments', 'global', 'travel'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiUsername', label: 'API Username', type: 'string', required: true, isSecret: false, description: 'Klarna API Username' },
      { key: 'apiPassword', label: 'API Password', type: 'password', required: true, isSecret: true, description: 'Klarna API Password' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'REFUND_PAYMENT'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'SEK', 'NOK', 'DKK'],
    supportedCountries: ['US', 'GB', 'DE', 'FR', 'ES', 'IT', 'AU', 'NL', 'SE'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 78,
    supportedPaymentMethods: ['BNPL', 'PAY_IN_3', 'PAY_IN_4', 'DIRECT_DEBIT'],
    costModel: { percentageFee: 3.29, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.95,
    maxRps: 200,
  },
  {
    providerId: 'afterpay',
    category: IntegrationCategory.PAYMENT,
    name: 'Afterpay / Clearpay',
    tagline: 'Leading installment payment network across US, UK, Australia, and New Zealand',
    description: 'Splits booking totals into 4 equal bi-weekly payments while DriveGo receives the full trip fare upfront.',
    icon: 'schedule',
    websiteUrl: 'https://afterpay.com',
    documentation: {
      overview: 'Afterpay / Clearpay API integration.',
      docsUrl: 'https://developers.afterpay.com',
      setupGuide: 'Configure Merchant ID and Secret Key in dashboard.',
    },
    version: '2.2.0',
    apiVersion: 'v2',
    author: 'Afterpay / Block, Inc.',
    tags: ['payments', 'installments', 'bnpl', 'australia', 'us', 'uk'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'Afterpay Merchant ID' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Afterpay Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'REFUND_PAYMENT'],
    supportedCurrencies: ['USD', 'AUD', 'GBP', 'CAD', 'NZD'],
    supportedCountries: ['US', 'AU', 'GB', 'CA', 'NZ'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 79,
    supportedPaymentMethods: ['BNPL', 'INSTALLMENTS'],
    costModel: { percentageFee: 4.0, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'affirm',
    category: IntegrationCategory.PAYMENT,
    name: 'Affirm',
    tagline: 'Adaptive checkout and transparent monthly financing for premium vehicle rentals',
    description: 'Offers 3, 6, or 12 month payment terms for high-end luxury vehicle rentals with zero hidden fees or compounding interest.',
    icon: 'account_balance_wallet',
    websiteUrl: 'https://affirm.com',
    documentation: {
      overview: 'Affirm financing checkout platform.',
      docsUrl: 'https://docs.affirm.com',
      setupGuide: 'Configure Public API Key and Private API Key.',
    },
    version: '2.5.0',
    apiVersion: 'v1',
    author: 'Affirm, Inc.',
    tags: ['payments', 'financing', 'monthly-installments', 'luxury-fleet'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'publicKey', label: 'Public API Key', type: 'string', required: true, isSecret: false, description: 'Affirm Public Key' },
      { key: 'privateKey', label: 'Private API Key', type: 'password', required: true, isSecret: true, description: 'Affirm Private Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'CHECKOUT', 'VERIFY_PAYMENT', 'BNPL', 'REFUND_PAYMENT'],
    supportedCurrencies: ['USD', 'CAD'],
    supportedCountries: ['US', 'CA'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 81,
    supportedPaymentMethods: ['BNPL', 'MONTHLY_INSTALLMENTS'],
    costModel: { percentageFee: 3.5, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 150,
  },
  {
    providerId: 'skrill',
    category: IntegrationCategory.PAYMENT,
    name: 'Skrill Digital Wallet',
    tagline: 'Global digital wallet supporting 40+ currencies and instant multicurrency transactions',
    description: 'Trusted e-wallet solution for international car renters in Europe and the Middle East, with rapid deposit holds and refunds.',
    icon: 'account_balance_wallet',
    websiteUrl: 'https://skrill.com',
    documentation: {
      overview: 'Skrill Quick Checkout & Digital Wallet API.',
      docsUrl: 'https://docs.skrill.com',
      setupGuide: 'Enter Merchant Email and Secret Word.',
    },
    version: '2.0.0',
    apiVersion: 'v1',
    author: 'Paysafe Group',
    tags: ['payments', 'wallet', 'europe', 'multicurrency'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantEmail', label: 'Merchant Email', type: 'string', required: true, isSecret: false, description: 'Skrill Merchant Email' },
      { key: 'secretWord', label: 'Secret Word', type: 'password', required: true, isSecret: true, description: 'Skrill Secret Word for MD5/SHA256 signature' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'WALLET'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AED', 'SGD', 'CAD'],
    supportedCountries: ['US', 'GB', 'DE', 'FR', 'ES', 'IT', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 83,
    supportedPaymentMethods: ['WALLET', 'RAPID_TRANSFER', 'INTERNATIONAL_CARD'],
    costModel: { percentageFee: 2.9, fixedFee: 0.29, currency: 'EUR' },
    slaUptimePercent: 99.85,
    maxRps: 120,
  },
  {
    providerId: 'neteller',
    category: IntegrationCategory.PAYMENT,
    name: 'Neteller',
    tagline: 'High-volume international digital wallet and cross-border payment processor',
    description: 'Global payments and stored-value digital wallet preferred by cross-border international tourists and expatriate renters.',
    icon: 'savings',
    websiteUrl: 'https://neteller.com',
    documentation: {
      overview: 'Neteller Merchant API.',
      docsUrl: 'https://developer.neteller.com',
      setupGuide: 'Configure Merchant Account ID and Secure ID.',
    },
    version: '1.9.0',
    apiVersion: 'v1',
    author: 'Paysafe Group',
    tags: ['payments', 'wallet', 'international', 'paysafe'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantAccountId', label: 'Merchant Account ID', type: 'string', required: true, isSecret: false, description: 'Neteller Account ID' },
      { key: 'secureId', label: 'Secure ID', type: 'password', required: true, isSecret: true, description: 'Neteller Secure ID' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'WALLET'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD'],
    supportedCountries: ['GB', 'DE', 'FR', 'ES', 'IT', 'AE', 'SG', 'AU'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 84,
    supportedPaymentMethods: ['WALLET', 'LOCAL_PAYMENTS'],
    costModel: { percentageFee: 2.9, fixedFee: 0.29, currency: 'EUR' },
    slaUptimePercent: 99.85,
    maxRps: 120,
  },
  {
    providerId: 'twocheckout',
    category: IntegrationCategory.PAYMENT,
    name: '2Checkout (Verifone)',
    tagline: 'Global localized digital commerce processing across 200+ countries and territories',
    description: 'All-in-one payment gateway with localized checkout in 30+ languages, 130+ currencies, and multi-tax compliance for car rentals.',
    icon: 'public',
    websiteUrl: 'https://2checkout.com',
    documentation: {
      overview: 'Verifone 2Checkout Global Payments API.',
      docsUrl: 'https://verifone.cloud/docs/2checkout',
      setupGuide: 'Enter Merchant Code and Secret Key from 2Checkout Integration page.',
    },
    version: '4.0.0',
    apiVersion: 'v4',
    author: 'Verifone Holdings',
    tags: ['payments', 'global', 'verifone', 'currencies', 'compliance'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantCode', label: 'Merchant Code', type: 'string', required: true, isSecret: false, description: '2Checkout Merchant Code' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: '2Checkout Secret Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'MULTI_CURRENCY'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'INR', 'AED', 'SGD', 'CAD', 'JPY'],
    supportedCountries: ['US', 'GB', 'DE', 'FR', 'AE', 'SG', 'IN', 'AU', 'JP'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    implementationStatus: ProviderImplementationStatus.LIVE_READY,
    adapterImplemented: true,
    priority: 86,
    supportedPaymentMethods: ['INTERNATIONAL_CARD', 'PAYPAL', 'LOCAL_CARDS'],
    costModel: { percentageFee: 3.5, fixedFee: 0.35, currency: 'USD' },
    slaUptimePercent: 99.9,
    maxRps: 180,
  },

  // =========================================================================
  // MOBILITY & FLEET INFRASTRUCTURE PROVIDERS
  // =========================================================================
  {
    providerId: 'netc_fastag',
    category: IntegrationCategory.TOLL_FASTAG,
    name: 'NETC FASTag Gateway',
    tagline: 'Automated electronic toll collection & highway plaza debit tracking',
    description:
      'National Electronic Toll Collection infrastructure integration for automated toll debits, vehicle barrier exits, and customer toll billing.',
    icon: 'toll',
    websiteUrl: 'https://www.npci.org.in/what-we-do/netc-fastag/product-overview',
    documentation: {
      overview: 'NPCI NETC FASTag API for automated toll charge reconciliation on rental fleets.',
      docsUrl: 'https://npci.org.in/netc-api',
      setupGuide: 'Configure Acquiring Bank FASTag credentials and Vehicle VRN sync.',
    },
    version: '1.4.0',
    apiVersion: 'v1',
    author: 'National Payments Corporation of India (NPCI)',
    tags: ['toll', 'fastag', 'rfid', 'india', 'fleet'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'bankCode', label: 'Bank Code', type: 'string', required: true, isSecret: false, description: 'FASTag Issuer/Acquirer Bank Code' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'NPCI NETC API Key' },
    ],
    supportedCapabilities: [
      'TOLL_DEBIT',
      'VEHICLE_TAG_STATUS',
      'TRANSACTION_RECONCILIATION',
      'BALANCE_CHECK',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 10,
    costModel: { percentageFee: 0, fixedFee: 5, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 100,
  },
  {
    providerId: 'tata_power_ev',
    category: IntegrationCategory.FUEL_CHARGING,
    name: 'Tata Power EZ Charge',
    tagline: 'Commercial EV fast-charging network and fleet billing integration',
    description:
      'Live charging session monitoring, battery SoC tracking, and automated kWh consumption billing for electric rental fleets.',
    icon: 'ev_station',
    websiteUrl: 'https://tatapower.com',
    documentation: {
      overview: 'OCPI-compliant EV charging station network integration.',
      docsUrl: 'https://tatapower.com/ezcharge/developers',
      setupGuide: 'Enter Enterprise CPO Token and Operator ID.',
    },
    version: '2.1.0',
    apiVersion: 'v2.2',
    author: 'Tata Power Company Ltd.',
    tags: ['ev', 'charging', 'ocpi', 'india', 'green-mobility'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'operatorId', label: 'Operator ID', type: 'string', required: true, isSecret: false, description: 'Tata Power CPO ID' },
      { key: 'authToken', label: 'Authorization Token', type: 'password', required: true, isSecret: true, description: 'OCPI Token' },
    ],
    supportedCapabilities: [
      'CHARGING_SESSION_START',
      'CHARGING_SESSION_STOP',
      'STATION_STATUS',
      'KWH_RECONCILIATION',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 15,
    costModel: { percentageFee: 0, fixedFee: 0.15, perRequestCost: 1, currency: 'INR' },
    slaUptimePercent: 99.8,
    maxRps: 60,
  },
  {
    providerId: 'park_plus',
    category: IntegrationCategory.PARKING,
    name: 'Park+',
    tagline: 'Smart parking barrier automation and airport hub valet management',
    description:
      'Automated RFID barrier lift, airport rental counter reserved parking spot management, and FASTag parking billing.',
    icon: 'local_parking',
    websiteUrl: 'https://parkplus.io',
    documentation: {
      overview: 'Automated barrier access and hub parking telemetry.',
      docsUrl: 'https://developer.parkplus.io',
      setupGuide: 'Configure Hub API Key and Plaza ID.',
    },
    version: '1.2.0',
    apiVersion: 'v1',
    author: 'Parviom Technologies Pvt Ltd',
    tags: ['parking', 'barrier-lift', 'fastag-parking', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'plazaId', label: 'Plaza ID', type: 'string', required: true, isSecret: false, description: 'Park+ Plaza ID' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Hub Secret Key' },
    ],
    supportedCapabilities: [
      'BARRIER_OPEN',
      'BARRIER_STATUS',
      'PARKING_SLOT_ASSIGNMENT',
      'EXIT_VALIDATION',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 20,
    costModel: { percentageFee: 0, fixedFee: 10, currency: 'INR' },
    slaUptimePercent: 99.85,
    maxRps: 50,
  },
  {
    providerId: 'hyperverge_ocr',
    category: IntegrationCategory.OCR,
    name: 'HyperVerge AI Document Engine',
    tagline: 'Sub-second AI OCR for driving licenses, Aadhar cards, and passports',
    description:
      'High-precision optical character recognition and fraud tampered-image detection for customer driver onboarding.',
    icon: 'document_scanner',
    websiteUrl: 'https://hyperverge.co',
    documentation: {
      overview: 'Deep learning OCR for international IDs and driving licenses.',
      docsUrl: 'https://hyperverge.co/docs',
      setupGuide: 'Configure App ID and App Key from HyperVerge Portal.',
    },
    version: '3.5.0',
    apiVersion: 'v2',
    author: 'HyperVerge Inc.',
    tags: ['ocr', 'ai', 'license-extraction', 'kyc'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'appId', label: 'App ID', type: 'string', required: true, isSecret: false, description: 'HyperVerge App ID' },
      { key: 'appKey', label: 'App Key', type: 'password', required: true, isSecret: true, description: 'HyperVerge Secret Key' },
    ],
    supportedCapabilities: [
      'EXTRACT_DL_METADATA',
      'EXTRACT_PASSPORT_METADATA',
      'FORGERY_DETECTION',
      'FACE_MATCH',
    ],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'US', 'AE', 'GB', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 5,
    costModel: { percentageFee: 0, fixedFee: 0, perRequestCost: 3.5, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 150,
  },
  {
    providerId: 'signzy_kyc',
    category: IntegrationCategory.IDENTITY_VERIFICATION,
    name: 'Signzy Identity Fabric',
    tagline: 'Comprehensive government registry check, court record search & Video KYC',
    description:
      'Instant real-time verification against Sarathi (MoRTH DL Registry), UIDAI Aadhaar, PAN, and international passport databases.',
    icon: 'verified_user',
    websiteUrl: 'https://signzy.com',
    documentation: {
      overview: 'Automated customer background screening and license verification.',
      docsUrl: 'https://docs.signzy.com',
      setupGuide: 'Enter Client ID and Token from Signzy console.',
    },
    version: '4.0.0',
    apiVersion: 'v3',
    author: 'Signzy Technologies Pvt Ltd',
    tags: ['identity', 'sarathi', 'dl-verification', 'court-check'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'clientId', label: 'Client ID', type: 'string', required: true, isSecret: false, description: 'Signzy Client ID' },
      { key: 'token', label: 'Token', type: 'password', required: true, isSecret: true, description: 'Signzy Secret Token' },
    ],
    supportedCapabilities: [
      'DL_AUTHENTICATION',
      'AADHAAR_VERIFICATION',
      'CHALLAN_HISTORY_CHECK',
      'CRIMINAL_RECORD_SEARCH',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 6,
    costModel: { percentageFee: 0, fixedFee: 0, perRequestCost: 6.0, currency: 'INR' },
    slaUptimePercent: 99.92,
    maxRps: 100,
  },
  {
    providerId: 'cleartax_gst',
    category: IntegrationCategory.TAX_GST,
    name: 'ClearTax GST & E-Invoicing',
    tagline: 'Automated government IRN invoice clearance and GST compliance',
    description:
      'Real-time automated generation of Invoice Reference Numbers (IRN), digital signature clearance, and B2B GST compliance for rental bookings.',
    icon: 'receipt_long',
    websiteUrl: 'https://cleartax.in',
    documentation: {
      overview: 'ClearTax E-Invoicing API for automatic tax compliance.',
      docsUrl: 'https://developer.cleartax.in',
      setupGuide: 'Obtain GSTIN, Client ID, and Client Secret from ClearTax Portal.',
    },
    version: '2.3.0',
    apiVersion: 'v1',
    author: 'Defmacro Software Pvt Ltd',
    tags: ['gst', 'tax', 'e-invoice', 'irn', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'gstin', label: 'GSTIN', type: 'string', required: true, isSecret: false, description: 'Enterprise GSTIN' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, isSecret: true, description: 'ClearTax Secret' },
    ],
    supportedCapabilities: [
      'GENERATE_IRN',
      'CANCEL_IRN',
      'EWAY_BILL_GENERATE',
      'GST_TAX_CALCULATION',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 8,
    costModel: { percentageFee: 0, fixedFee: 0, perRequestCost: 1.2, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 100,
  },
  {
    providerId: 'razorpayx_payout',
    category: IntegrationCategory.PAYOUTS,
    name: 'RazorpayX Instant Payouts',
    tagline: 'Automated vendor earnings disbursement and instant bank account validation',
    description:
      'High-throughput banking operations engine powering 24/7 instant vendor wallet withdrawals, security deposit refunds, and IMPS/UPI bank verification.',
    icon: 'payments',
    websiteUrl: 'https://razorpay.com/x',
    documentation: {
      overview: 'Business banking and programmatic payout API.',
      docsUrl: 'https://razorpay.com/docs/x',
      setupGuide: 'Obtain RazorpayX Account Number, Key ID, and Secret from RazorpayX Dashboard.',
    },
    version: '2.5.0',
    apiVersion: 'v1',
    author: 'Razorpay Software Pvt Ltd',
    tags: ['payouts', 'vendor-settlements', 'instant-refund', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accountNumber', label: 'Account Number', type: 'string', required: true, isSecret: false, description: 'RazorpayX Virtual Account' },
      { key: 'keyId', label: 'Key ID', type: 'string', required: true, isSecret: false, description: 'RazorpayX Key ID' },
      { key: 'keySecret', label: 'Key Secret', type: 'password', required: true, isSecret: true, description: 'RazorpayX Key Secret' },
    ],
    supportedCapabilities: [
      'INSTANT_PAYOUT',
      'BANK_ACCOUNT_VALIDATION',
      'UPI_ID_VALIDATION',
      'PAYOUT_STATUS',
      'BULK_PAYOUTS',
    ],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.CONFIGURABLE,
    certificationLevel: ProviderCertificationLevel.CATALOG,
    adapterImplemented: false,
    priority: 5,
    costModel: { percentageFee: 0, fixedFee: 4.5, perRequestCost: 0, currency: 'INR' },
    slaUptimePercent: 99.98,
    maxRps: 150,
  },
];
