import { IntegrationCategory } from '../registry/provider.types';

export interface EcosystemCategoryAudit {
  categoryNumber: number;
  categoryName: string;
  categoryKey: IntegrationCategory;
  description: string;
  coreCapabilities: string[];
  supportedRegions: string[];
  providersCount: number;
  realAdaptersCount: number;
  mockAdaptersCount: number;
  catalogOnlyCount: number;
}

export const ECOSYSTEM_35_CATEGORIES: EcosystemCategoryAudit[] = [
  {
    categoryNumber: 1,
    categoryName: 'Payments & Financial Gateways',
    categoryKey: IntegrationCategory.PAYMENT,
    description: 'Enterprise multi-gateway processing, order creation, capture, refunds, UPI, cards, and payouts.',
    coreCapabilities: ['CREATE_ORDER', 'CREATE_PAYMENT', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD', 'NET_BANKING', 'PAYOUT'],
    supportedRegions: ['IN', 'US', 'EU', 'GB', 'SG', 'AE', 'GLOBAL'],
    providersCount: 47,
    realAdaptersCount: 47,
    mockAdaptersCount: 1,
    catalogOnlyCount: 0,
  },
  {
    categoryNumber: 2,
    categoryName: 'WhatsApp Business Messaging',
    categoryKey: IntegrationCategory.MESSAGING_WHATSAPP,
    description: 'Official WhatsApp Business APIs, interactive templates, media messages, two-way conversational flows.',
    coreCapabilities: ['SEND_TEMPLATE', 'SEND_INTERACTIVE', 'SEND_MEDIA', 'WEBHOOK_INBOUND', 'READ_RECEIPTS'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 8,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 5,
  },
  {
    categoryNumber: 3,
    categoryName: 'SMS Gateway & Delivery',
    categoryKey: IntegrationCategory.MESSAGING_SMS,
    description: 'High-throughput transactional and promotional SMS with DLT compliance and international routing.',
    coreCapabilities: ['SEND_SMS', 'SEND_TRANSACTIONAL', 'SEND_PROMOTIONAL', 'DLT_ROUTING', 'DELIVERY_RECEIPTS'],
    supportedRegions: ['IN', 'US', 'GLOBAL'],
    providersCount: 34,
    realAdaptersCount: 34,
    mockAdaptersCount: 1,
    catalogOnlyCount: 0,
  },
  {
    categoryNumber: 4,
    categoryName: 'Email Delivery & Inbound',
    categoryKey: IntegrationCategory.MESSAGING_EMAIL,
    description: 'Transactional email, booking confirmations, invoices, domain reputation management, DKIM/SPF.',
    coreCapabilities: ['SEND_EMAIL', 'SEND_TEMPLATE_EMAIL', 'ATTACHMENTS', 'BOUNCE_HANDLING', 'OPEN_TRACKING'],
    supportedRegions: ['GLOBAL'],
    providersCount: 7,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 4,
  },
  {
    categoryNumber: 5,
    categoryName: 'Push Notifications',
    categoryKey: IntegrationCategory.MESSAGING_PUSH,
    description: 'Mobile and web push notifications, background data sync, critical alarms, device token lifecycle.',
    coreCapabilities: ['SEND_PUSH', 'SEND_TOPIC_PUSH', 'SILENT_DATA_PUSH', 'TOKEN_VALIDATION'],
    supportedRegions: ['GLOBAL'],
    providersCount: 5,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 6,
    categoryName: 'Cloud Object Storage',
    categoryKey: IntegrationCategory.STORAGE,
    description: 'S3-compatible secure object storage, pre-signed upload URLs, encrypted document storage, CDN delivery.',
    coreCapabilities: ['UPLOAD', 'GET_SIGNED_URL', 'DELETE_FILE', 'STREAM_DOWNLOAD', 'MIME_VALIDATION'],
    supportedRegions: ['IN', 'US', 'EU', 'GLOBAL'],
    providersCount: 5,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 7,
    categoryName: 'Maps & Geospatial Services',
    categoryKey: IntegrationCategory.MAPS,
    description: 'Map visualization, vector tiles, static map rendering, point-of-interest markers.',
    coreCapabilities: ['MAP_TILES', 'STATIC_MAP', 'GEOCODE', 'REVERSE_GEOCODE', 'BOUNDS_CALCULATION'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 5,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 8,
    categoryName: 'Geocoding & Location Normalization',
    categoryKey: IntegrationCategory.MAPS,
    description: 'Forward street-to-coordinate and reverse coordinate-to-address geocoding with confidence scoring.',
    coreCapabilities: ['GEOCODE', 'REVERSE_GEOCODE', 'BATCH_GEOCODE', 'BOUNDS_GEOCODE'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 5,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 9,
    categoryName: 'Routing & Navigation',
    categoryKey: IntegrationCategory.ROUTING_DISTANCE,
    description: 'Real-time turn-by-turn routing, polyline generation, toll avoidance, multimodal waypoints.',
    coreCapabilities: ['ROUTE', 'AVOID_TOLLS', 'WAYPOINT_OPTIMIZATION', 'POLYLINE_EXTRACTION'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 5,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 10,
    categoryName: 'Distance Matrix & ETA',
    categoryKey: IntegrationCategory.ROUTING_DISTANCE,
    description: 'Many-to-many distance and travel time computation under live and historical traffic profiles.',
    coreCapabilities: ['DISTANCE_MATRIX', 'ETA_PREDICTION', 'TRAFFIC_MODELING'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 4,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 11,
    categoryName: 'Places & Search Autocomplete',
    categoryKey: IntegrationCategory.PLACES_POI,
    description: 'Predictive address search, airport/hub lookup, geo-fenced autocomplete, place details.',
    coreCapabilities: ['PLACE_SEARCH', 'PLACE_DETAILS', 'AUTOCOMPLETE', 'NEARBY_SEARCH'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 4,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 12,
    categoryName: 'Identity & KYC Verification',
    categoryKey: IntegrationCategory.IDENTITY_VERIFICATION,
    description: 'Government ID verification (PAN, Aadhaar, DL, RC), selfie liveness, face matching, anti-spoofing.',
    coreCapabilities: ['PAN_VERIFICATION', 'AADHAAR_VERIFICATION', 'DRIVING_LICENCE_VERIFICATION', 'VEHICLE_RC_VERIFICATION', 'FACE_MATCH', 'LIVENESS'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 8,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 5,
  },
  {
    categoryNumber: 13,
    categoryName: 'Vehicle GPS & Fleet Telematics',
    categoryKey: IntegrationCategory.VEHICLE_TRACKING,
    description: 'Hardware GPS tracker integration, live telemetry ingestion, trip replay, remote engine cutoff.',
    coreCapabilities: ['GPS_POSITION', 'LIVE_LOCATION', 'TRIP_TRACKING', 'IMMOBILIZE', 'RESTORE_ENGINE', 'GEOFENCE_CHECK'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 6,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 4,
  },
  {
    categoryNumber: 14,
    categoryName: 'Accounting & ERP Synchronization',
    categoryKey: IntegrationCategory.ACCOUNTING,
    description: 'Automated invoice generation, payment reconciliation, chart of accounts, credit notes, customer sync.',
    coreCapabilities: ['CREATE_INVOICE', 'SYNC_CUSTOMER', 'SYNC_PAYMENT', 'CANCEL_INVOICE', 'RECONCILE', 'EXPORT_LEDGER'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 5,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 3,
  },
  {
    categoryNumber: 15,
    categoryName: 'Tax & GST Computation',
    categoryKey: IntegrationCategory.TAX_GST,
    description: 'Automated GST calculation (CGST/SGST/IGST), SAC code determination, e-invoicing compliance.',
    coreCapabilities: ['TAX_CALCULATION', 'E_INVOICE_GENERATION', 'GSTIN_VERIFICATION'],
    supportedRegions: ['IN', 'US', 'EU'],
    providersCount: 4,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 16,
    categoryName: 'Full-Text & Faceted Search',
    categoryKey: IntegrationCategory.SEARCH,
    description: 'Instant vehicle, location, and amenity search, typo tolerance, multi-criteria filtering, geo-radius ranking.',
    coreCapabilities: ['INDEX_DOCUMENT', 'BATCH_INDEX', 'SEARCH_QUERY', 'AUTOCOMPLETE'],
    supportedRegions: ['GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 17,
    categoryName: 'Product & Fleet Analytics',
    categoryKey: IntegrationCategory.ANALYTICS,
    description: 'Server-side product telemetry, user behavioral funnel analysis, cohort tracking, conversion attribution.',
    coreCapabilities: ['TRACK_EVENT', 'IDENTIFY_USER', 'BATCH_EVENTS'],
    supportedRegions: ['GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 18,
    categoryName: 'AI & Large Language Models',
    categoryKey: IntegrationCategory.AI,
    description: 'GenAI chat assistance, damage report summarization, customer sentiment analysis, automated extraction.',
    coreCapabilities: ['CHAT', 'TEXT_GENERATION', 'SUMMARIZATION', 'CLASSIFICATION', 'EXTRACTION', 'EMBEDDINGS'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 6,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 4,
  },
  {
    categoryNumber: 19,
    categoryName: 'Optical Character Recognition (OCR)',
    categoryKey: IntegrationCategory.OCR,
    description: 'Extraction of text, license numbers, RC details, meter readings, and damage inspection stamps.',
    coreCapabilities: ['OCR', 'DOCUMENT_EXTRACTION', 'BOUNDING_BOX_DETECTION'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 4,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 20,
    categoryName: 'Document Verification',
    categoryKey: IntegrationCategory.DOCUMENT_VERIFICATION,
    description: 'Automated authenticity verification for driver licenses, vehicle titles, registration certs, insurance.',
    coreCapabilities: ['VERIFY_DOCUMENT', 'DOCUMENT_EXTRACTION', 'TAMPER_DETECTION'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 21,
    categoryName: 'Electronic Signature & Rental Agreements',
    categoryKey: IntegrationCategory.ESIGNATURE,
    description: 'Legally binding digital signing of rental terms, handover forms, and vehicle lease contracts.',
    coreCapabilities: ['CREATE_SIGNING_REQUEST', 'CHECK_STATUS', 'DOWNLOAD_SIGNED_PDF'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 0,
    mockAdaptersCount: 1,
    catalogOnlyCount: 3,
  },
  {
    categoryNumber: 22,
    categoryName: 'Cloud Messaging & Webhooks',
    categoryKey: IntegrationCategory.NOTIFICATION_ORCHESTRATION,
    description: 'Cross-channel event routing, message queues, webhook dispatching, unified notification pipes.',
    coreCapabilities: ['SEND_NOTIFICATION', 'DISPATCH_WEBHOOK', 'TOPIC_PUBLISH'],
    supportedRegions: ['GLOBAL'],
    providersCount: 5,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 23,
    categoryName: 'Customer Support & Helpdesk',
    categoryKey: IntegrationCategory.CUSTOMER_SUPPORT,
    description: 'Support ticket creation, conversation history sync, agent escalation, emergency roadside assistance sync.',
    coreCapabilities: ['CREATE_TICKET', 'SYNC_CONVERSATION', 'UPDATE_TICKET_STATUS'],
    supportedRegions: ['GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 0,
    mockAdaptersCount: 1,
    catalogOnlyCount: 3,
  },
  {
    categoryNumber: 24,
    categoryName: 'Voice & Automated Calling',
    categoryKey: IntegrationCategory.VOICE_IVR,
    description: 'Automated outbound voice calls, audio OTP reading, driver phone masking / number proxying.',
    coreCapabilities: ['VOICE_CALL', 'VOICE_OTP', 'NUMBER_MASKING', 'CALL_RECORDING'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 25,
    categoryName: 'Language Translation',
    categoryKey: IntegrationCategory.TRANSLATION,
    description: 'Real-time multi-language translation for rental contracts, customer chat, and regional UI localization.',
    coreCapabilities: ['TRANSLATE_TEXT', 'DETECT_LANGUAGE', 'LOCALIZE_DOC'],
    supportedRegions: ['GLOBAL'],
    providersCount: 3,
    realAdaptersCount: 0,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 26,
    categoryName: 'Image & Media Processing',
    categoryKey: IntegrationCategory.CDN_IMAGE,
    description: 'Vehicle damage photo optimization, thumbnail generation, watermark stamping, blur detection.',
    coreCapabilities: ['COMPRESS_IMAGE', 'GENERATE_THUMBNAIL', 'WATERMARK_IMAGE', 'DETECT_BLUR'],
    supportedRegions: ['GLOBAL'],
    providersCount: 3,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 27,
    categoryName: 'Fraud & Risk Detection',
    categoryKey: IntegrationCategory.FRAUD_RISK,
    description: 'Booking fraud scoring, card-testing mitigation, identity velocity checks, suspicious device fingerprinting.',
    coreCapabilities: ['ASSESS_RISK', 'DEVICE_FINGERPRINT', 'BEHAVIORAL_SCORE'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 3,
    realAdaptersCount: 0,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 28,
    categoryName: 'Address Validation & Normalization',
    categoryKey: IntegrationCategory.ADDRESS_VALIDATION,
    description: 'Postal address validation, PIN code matching, doorstep delivery serviceability confirmation.',
    coreCapabilities: ['VALIDATE_ADDRESS', 'FORMAT_POSTAL_ADDRESS', 'CHECK_DELIVERY_ZONE'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 3,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 29,
    categoryName: 'Currency & Foreign Exchange (FX)',
    categoryKey: IntegrationCategory.PAYMENT,
    description: 'Real-time FX rates, multi-currency conversion, cross-border booking price locks.',
    coreCapabilities: ['GET_LATEST_RATES', 'CONVERT_CURRENCY', 'HISTORICAL_RATES'],
    supportedRegions: ['GLOBAL'],
    providersCount: 3,
    realAdaptersCount: 0,
    mockAdaptersCount: 1,
    catalogOnlyCount: 2,
  },
  {
    categoryNumber: 30,
    categoryName: 'Business & Vendor Verification',
    categoryKey: IntegrationCategory.IDENTITY_VERIFICATION,
    description: 'Company registration check (MCA/CIN in India, corporate registries globally), GSTIN tax validation.',
    coreCapabilities: ['VERIFY_BUSINESS', 'VERIFY_GSTIN', 'DIRECTOR_CHECK'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 3,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 31,
    categoryName: 'Email Delivery & Inbound SMTP',
    categoryKey: IntegrationCategory.MESSAGING_EMAIL,
    description: 'Direct high-availability SMTP & API delivery for critical transactional notifications.',
    coreCapabilities: ['SEND_EMAIL', 'SEND_SMTP', 'DELIVERY_STATUS'],
    supportedRegions: ['GLOBAL'],
    providersCount: 6,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 3,
  },
  {
    categoryNumber: 32,
    categoryName: 'SMS OTP Authentication',
    categoryKey: IntegrationCategory.OTP,
    description: 'Sub-second SMS one-time password challenge and verification with operator bypass failover.',
    coreCapabilities: ['SEND_OTP', 'VERIFY_OTP', 'RESEND_OTP'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 6,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 3,
  },
  {
    categoryNumber: 33,
    categoryName: 'WhatsApp OTP Authentication',
    categoryKey: IntegrationCategory.OTP,
    description: 'WhatsApp-native one-tap OTP authentication codes with high read and delivery rates.',
    coreCapabilities: ['SEND_OTP', 'VERIFY_OTP', 'RESEND_OTP'],
    supportedRegions: ['IN', 'GLOBAL'],
    providersCount: 4,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 34,
    categoryName: 'Maps & Live Navigation',
    categoryKey: IntegrationCategory.MAPS,
    description: 'Turn-by-turn guidance, re-routing, traffic incident overlays for car renters.',
    coreCapabilities: ['ROUTE', 'NAVIGATION', 'TRAFFIC_INCIDENTS'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 4,
    realAdaptersCount: 2,
    mockAdaptersCount: 1,
    catalogOnlyCount: 1,
  },
  {
    categoryNumber: 35,
    categoryName: 'Vehicle Telemetry & IoT Hub',
    categoryKey: IntegrationCategory.FLEET_IOT,
    description: 'Unified CAN-bus telemetry hub, fuel consumption tracking, battery health monitoring, crash telemetry.',
    coreCapabilities: ['GPS_POSITION', 'DIAGNOSTICS', 'BATTERY_HEALTH', 'FUEL_REPORT', 'CRASH_ALERT'],
    supportedRegions: ['GLOBAL', 'IN'],
    providersCount: 5,
    realAdaptersCount: 1,
    mockAdaptersCount: 1,
    catalogOnlyCount: 3,
  },
];

export const ENTERPRISE_PAYMENT_PROVIDERS_MASTER: Array<{
  id: string;
  name: string;
  region: string;
  currencies: string[];
  capabilities: string[];
  status: 'REAL_ADAPTER' | 'SIMULATION_MOCK' | 'CATALOG_ONLY';
  pricing: string;
  supportsUpi: boolean;
  supportsCards: boolean;
  supportsRefunds: boolean;
}> = [
  // India (Real Adapters)
  { id: 'razorpay', name: 'Razorpay', region: 'IN', currencies: ['INR', 'USD', 'EUR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD', 'NET_BANKING', 'PAYMENT_LINK'], status: 'REAL_ADAPTER', pricing: '2% standard', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'cashfree', name: 'Cashfree Payments', region: 'IN', currencies: ['INR', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD', 'NET_BANKING', 'PAYOUT'], status: 'REAL_ADAPTER', pricing: '1.9% + Rs.0', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'payu', name: 'PayU India', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD', 'NET_BANKING'], status: 'REAL_ADAPTER', pricing: '2% + GST', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'phonepe', name: 'PhonePe Payment Gateway', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD'], status: 'REAL_ADAPTER', pricing: '0% UPI / 1.85% Cards', supportsUpi: true, supportsCards: true, supportsRefunds: true },

  // Global (Real Adapters)
  { id: 'stripe', name: 'Stripe', region: 'GLOBAL', currencies: ['USD', 'EUR', 'GBP', 'INR', 'AUD', 'SGD', 'CAD'], capabilities: ['CREATE_ORDER', 'CREATE_PAYMENT', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'CARD', 'WALLET', 'PAYMENT_LINK'], status: 'REAL_ADAPTER', pricing: '2.9% + $0.30', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'adyen', name: 'Adyen', region: 'GLOBAL', currencies: ['EUR', 'USD', 'GBP', 'INR', 'SGD', 'AED'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'CARD', 'UPI', 'WALLET'], status: 'REAL_ADAPTER', pricing: 'Interchange++ + 0.12 EUR', supportsUpi: true, supportsCards: true, supportsRefunds: true },

  // Simulation Mock
  { id: 'mock_payment', name: 'DriveGo Mock Financial Gateway', region: 'GLOBAL', currencies: ['INR', 'USD', 'EUR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD', 'NET_BANKING', 'PAYOUT'], status: 'SIMULATION_MOCK', pricing: 'Free simulation', supportsUpi: true, supportsCards: true, supportsRefunds: true },

  // India (Catalog-Only Providers)
  { id: 'paytm', name: 'Paytm Payment Gateway', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'UPI', 'CARD', 'WALLET'], status: 'REAL_ADAPTER', pricing: '1.99% + GST', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'instamojo', name: 'Instamojo', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'UPI', 'CARD', 'PAYMENT_LINK'], status: 'REAL_ADAPTER', pricing: '2% + Rs.3', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'billdesk', name: 'BillDesk', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'NET_BANKING', 'CARD', 'UPI'], status: 'REAL_ADAPTER', pricing: 'Enterprise negotiated', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'ccavenue', name: 'CCAvenue', region: 'IN', currencies: ['INR', 'USD', 'EUR', 'GBP'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'CARD', 'NET_BANKING', 'UPI'], status: 'REAL_ADAPTER', pricing: '2% standard', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'easebuzz', name: 'Easebuzz', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'UPI', 'CARD', 'PAYMENT_LINK'], status: 'REAL_ADAPTER', pricing: '1.85% + GST', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'juspay', name: 'Juspay HyperCheckout', region: 'IN', currencies: ['INR', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'UPI_INTENT', 'CARD', 'PAYOUT'], status: 'REAL_ADAPTER', pricing: 'Platform fee + per txn', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'openmoney', name: 'OpenMoney (Open Financial)', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'PAYOUT', 'UPI', 'CARD'], status: 'CATALOG_ONLY', pricing: '2% flat', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'pinelabs', name: 'Pine Labs Online', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'CARD', 'UPI', 'BNPL'], status: 'CATALOG_ONLY', pricing: '1.9% + GST', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'bharatpe', name: 'BharatPe Merchant Services', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'UPI_QR', 'PAYOUT'], status: 'CATALOG_ONLY', pricing: '0% UPI MDR', supportsUpi: true, supportsCards: false, supportsRefunds: false },
  { id: 'payg', name: 'PayG Payment Gateway', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'UPI', 'CARD'], status: 'CATALOG_ONLY', pricing: '1.9% flat', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'airpay', name: 'Airpay Payment Services', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'CARD', 'NET_BANKING', 'UPI'], status: 'CATALOG_ONLY', pricing: '1.8% standard', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'zaakpay', name: 'Zaakpay (MobiKwik)', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'WALLET', 'UPI', 'CARD'], status: 'CATALOG_ONLY', pricing: '1.9% + GST', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'sabpaisa', name: 'SabPaisa Payment Gateway', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'NET_BANKING', 'UPI', 'CARD'], status: 'CATALOG_ONLY', pricing: 'Custom enterprise', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'hdfc_smartgateway', name: 'HDFC SmartGateway', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'CARD', 'UPI', 'NET_BANKING'], status: 'CATALOG_ONLY', pricing: 'Direct merchant rates', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'icici_payseal', name: 'ICICI Payseal', region: 'IN', currencies: ['INR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'CARD', 'NET_BANKING'], status: 'CATALOG_ONLY', pricing: 'Bank merchant rates', supportsUpi: false, supportsCards: true, supportsRefunds: true },

  // Global (Catalog-Only Providers)
  { id: 'paypal', name: 'PayPal Braintree', region: 'GLOBAL', currencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'JPY'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD', 'WALLET'], status: 'REAL_ADAPTER', pricing: '2.59% + $0.49', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'checkout_com', name: 'Checkout.com', region: 'GLOBAL', currencies: ['USD', 'EUR', 'GBP', 'AED', 'SAR', 'SGD'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD', 'WALLET', 'PAYOUT'], status: 'REAL_ADAPTER', pricing: 'Interchange++ or flat', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'square', name: 'Square Payments', region: 'US', currencies: ['USD', 'CAD', 'GBP', 'EUR', 'AUD', 'JPY'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD'], status: 'REAL_ADAPTER', pricing: '2.9% + $0.30', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'mollie', name: 'Mollie Payments', region: 'EU', currencies: ['EUR', 'GBP', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'CARD', 'IDEAL', 'SOFORT'], status: 'REAL_ADAPTER', pricing: '0.29 EUR + 1.8%', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'authorizenet', name: 'Authorize.Net (Visa)', region: 'US', currencies: ['USD', 'CAD', 'GBP', 'EUR'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'VOID', 'CARD'], status: 'REAL_ADAPTER', pricing: '2.9% + $0.30 + $25/mo', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'paddle', name: 'Paddle Billing', region: 'GLOBAL', currencies: ['USD', 'EUR', 'GBP'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD', 'PAYPAL', 'SUBSCRIPTIONS'], status: 'CATALOG_ONLY', pricing: '5% + $0.50', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'mercadopago', name: 'Mercado Pago', region: 'LATAM', currencies: ['BRL', 'ARS', 'MXN', 'CLP', 'COP'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'PIX', 'CARD'], status: 'REAL_ADAPTER', pricing: '3.99% + tax', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'paystack', name: 'Paystack (Stripe)', region: 'AFRICA', currencies: ['NGN', 'GHS', 'ZAR', 'KES', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER'], status: 'REAL_ADAPTER', pricing: '1.5% + NGN 100', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'flutterwave', name: 'Flutterwave', region: 'AFRICA', currencies: ['NGN', 'KES', 'GHS', 'USD', 'EUR', 'GBP'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'CARD', 'MOBILE_MONEY', 'PAYOUT'], status: 'REAL_ADAPTER', pricing: '1.4% local / 3.8% intl', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'xendit', name: 'Xendit', region: 'SEA', currencies: ['IDR', 'PHP', 'VND', 'THB', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'EWALLET', 'CARD', 'VIRTUAL_ACCOUNT'], status: 'REAL_ADAPTER', pricing: 'IDR 4,500 + 2.9%', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'midtrans', name: 'Midtrans (GoTo)', region: 'SEA', currencies: ['IDR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'GOPAY', 'QRIS', 'CARD'], status: 'REAL_ADAPTER', pricing: '2% - 2.9%', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'paymongo', name: 'PayMongo', region: 'SEA', currencies: ['PHP'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'GCASH', 'MAYA', 'CARD'], status: 'CATALOG_ONLY', pricing: '3.5% + PHP 15', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'tap', name: 'Tap Payments', region: 'MENA', currencies: ['KWD', 'SAR', 'AED', 'BHD', 'QAR', 'OMR', 'EGP', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'CAPTURE', 'REFUND', 'KNET', 'MADA', 'CARD'], status: 'REAL_ADAPTER', pricing: '2.5% + fixed', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'paytabs', name: 'PayTabs', region: 'MENA', currencies: ['SAR', 'AED', 'EGP', 'USD'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'MADA', 'CARD', 'APPLE_PAY'], status: 'REAL_ADAPTER', pricing: '2.7% + 1 SAR', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'worldpay', name: 'FIS Worldpay', region: 'GLOBAL', currencies: ['USD', 'GBP', 'EUR'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD'], status: 'CATALOG_ONLY', pricing: 'Interchange++', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'dlocal', name: 'dLocal', region: 'GLOBAL', currencies: ['BRL', 'MXN', 'INR', 'NGN', 'ZAR', 'IDR'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'PAYOUT', 'LOCAL_PAYMENT_METHODS'], status: 'CATALOG_ONLY', pricing: 'Custom enterprise', supportsUpi: true, supportsCards: true, supportsRefunds: true },
  { id: 'klarna', name: 'Klarna BNPL', region: 'EU', currencies: ['EUR', 'USD', 'GBP', 'SEK'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'BNPL'], status: 'CATALOG_ONLY', pricing: '3.29% + $0.30', supportsUpi: false, supportsCards: false, supportsRefunds: true },
  { id: 'twocheckout', name: '2Checkout (Verifone)', region: 'GLOBAL', currencies: ['USD', 'EUR', 'GBP'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD', 'PAYPAL'], status: 'CATALOG_ONLY', pricing: '3.5% + $0.35', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'moneris', name: 'Moneris Solutions', region: 'CA', currencies: ['CAD', 'USD'], capabilities: ['CREATE_ORDER', 'CAPTURE', 'REFUND', 'CARD', 'INTERAC'], status: 'CATALOG_ONLY', pricing: 'Interchange + 0.15%', supportsUpi: false, supportsCards: true, supportsRefunds: true },
  { id: 'fawry', name: 'Fawry Payments', region: 'EG', currencies: ['EGP'], capabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND', 'CASH_COLLECTION', 'CARD', 'WALLET'], status: 'CATALOG_ONLY', pricing: '2.5% + EGP 2', supportsUpi: false, supportsCards: true, supportsRefunds: true },
];

export interface MasterEcosystemProviderRecord {
  providerId: string;
  displayName: string;
  category: string;
  supportedCountries: string[];
  supportedCurrencies: string[];
  status: 'REAL_ADAPTER' | 'SIMULATION_MOCK' | 'CATALOG_ONLY';
  credentialRequirements: string[];
  capabilities: string[];
}

// Convert payment master into standard ecosystem provider records
const paymentEcosystemRecords: MasterEcosystemProviderRecord[] = ENTERPRISE_PAYMENT_PROVIDERS_MASTER.map(p => ({
  providerId: p.id,
  displayName: p.name,
  category: 'payments',
  supportedCountries: p.region === 'GLOBAL' ? ['US', 'IN', 'EU', 'GB', 'SG'] : [p.region],
  supportedCurrencies: p.currencies,
  status: p.status,
  credentialRequirements: p.status === 'REAL_ADAPTER' ? ['apiKey', 'apiSecret'] : ['apiKey'],
  capabilities: p.capabilities,
}));

export const MASTER_PROVIDER_ECOSYSTEM: Record<string, MasterEcosystemProviderRecord[]> = {
  payments: paymentEcosystemRecords,
  whatsapp: [
    { providerId: 'meta_whatsapp', displayName: 'Meta WhatsApp Cloud API', category: 'whatsapp', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['systemUserToken', 'phoneNumberId'], capabilities: ['SEND_TEMPLATE', 'SEND_MEDIA'] },
    { providerId: 'gupshup', displayName: 'Gupshup Enterprise BSP', category: 'whatsapp', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey', 'appId'], capabilities: ['SEND_TEMPLATE', 'SEND_INTERACTIVE'] },
    { providerId: 'mock_whatsapp', displayName: 'Mock WhatsApp Adapter', category: 'whatsapp', supportedCountries: ['GLOBAL'], supportedCurrencies: ['INR'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['SEND_TEMPLATE'] },
    { providerId: 'interakt', displayName: 'Interakt (Jio Haptik)', category: 'whatsapp', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['SEND_TEMPLATE'] },
    { providerId: 'aisensy', displayName: 'AiSensy WhatsApp Suite', category: 'whatsapp', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['SEND_TEMPLATE'] },
    { providerId: 'twilio_whatsapp', displayName: 'Twilio WhatsApp API', category: 'whatsapp', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['accountSid', 'authToken'], capabilities: ['SEND_TEMPLATE'] },
  ],
  sms: [
    { providerId: 'msg91', displayName: 'MSG91 Enterprise SMS', category: 'sms', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['authKey'], capabilities: ['SEND_SMS', 'SEND_TRANSACTIONAL'] },
    { providerId: 'twilio_sms', displayName: 'Twilio Programmable SMS', category: 'sms', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['accountSid', 'authToken'], capabilities: ['SEND_SMS'] },
    { providerId: 'mock_sms', displayName: 'Mock SMS Provider', category: 'sms', supportedCountries: ['GLOBAL'], supportedCurrencies: ['INR'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['SEND_SMS'] },
    { providerId: 'exotel', displayName: 'Exotel Communications', category: 'sms', supportedCountries: ['IN', 'SEA'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey', 'apiToken'], capabilities: ['SEND_SMS'] },
    { providerId: 'route_mobile', displayName: 'Route Mobile', category: 'sms', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['username', 'password'], capabilities: ['SEND_SMS'] },
  ],
  email: [
    { providerId: 'resend', displayName: 'Resend Modern Email API', category: 'email', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['SEND_EMAIL', 'SEND_TEMPLATE_EMAIL'] },
    { providerId: 'sendgrid', displayName: 'Twilio SendGrid Email', category: 'email', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['SEND_EMAIL'] },
    { providerId: 'mock_email', displayName: 'Mock Email Service', category: 'email', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['SEND_EMAIL'] },
    { providerId: 'aws_ses', displayName: 'Amazon Simple Email Service (SES)', category: 'email', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['accessKey', 'secretKey', 'region'], capabilities: ['SEND_EMAIL'] },
    { providerId: 'postmark', displayName: 'Postmark (ActiveCampaign)', category: 'email', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['serverToken'], capabilities: ['SEND_EMAIL'] },
  ],
  push_notifications: [
    { providerId: 'fcm', displayName: 'Firebase Cloud Messaging (FCM)', category: 'push_notifications', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['serviceAccountJson'], capabilities: ['SEND_PUSH', 'SEND_TOPIC_PUSH'] },
    { providerId: 'onesignal', displayName: 'OneSignal Push Messaging', category: 'push_notifications', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['appId', 'restApiKey'], capabilities: ['SEND_PUSH'] },
    { providerId: 'mock_push', displayName: 'Mock Push Engine', category: 'push_notifications', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['SEND_PUSH'] },
    { providerId: 'aws_sns', displayName: 'Amazon Simple Notification Service', category: 'push_notifications', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['accessKey', 'secretKey'], capabilities: ['SEND_PUSH'] },
  ],
  cloud_storage: [
    { providerId: 'r2', displayName: 'Cloudflare R2 Object Storage', category: 'cloud_storage', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['accountId', 'accessKeyId', 'secretAccessKey'], capabilities: ['UPLOAD', 'GET_SIGNED_URL'] },
    { providerId: 's3', displayName: 'Amazon Simple Storage Service (S3)', category: 'cloud_storage', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['accessKeyId', 'secretAccessKey', 'region'], capabilities: ['UPLOAD', 'GET_SIGNED_URL'] },
    { providerId: 'mock_storage', displayName: 'Mock Local Storage', category: 'cloud_storage', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['UPLOAD'] },
    { providerId: 'google_cloud_storage', displayName: 'Google Cloud Storage', category: 'cloud_storage', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['serviceAccountKey'], capabilities: ['UPLOAD', 'GET_SIGNED_URL'] },
  ],
  maps: [
    { providerId: 'mapbox', displayName: 'Mapbox Vector Maps & Navigation', category: 'maps', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['accessToken'], capabilities: ['GEOCODE', 'REVERSE_GEOCODE', 'ROUTE', 'DISTANCE_MATRIX'] },
    { providerId: 'google_maps', displayName: 'Google Maps Platform', category: 'maps', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['GEOCODE', 'REVERSE_GEOCODE', 'ROUTE', 'DISTANCE_MATRIX'] },
    { providerId: 'mock_maps', displayName: 'Mock Maps Simulation', category: 'maps', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['GEOCODE', 'ROUTE'] },
    { providerId: 'here_maps', displayName: 'HERE Technologies Maps', category: 'maps', supportedCountries: ['GLOBAL', 'EU'], supportedCurrencies: ['EUR', 'USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['GEOCODE', 'ROUTE'] },
    { providerId: 'tomtom', displayName: 'TomTom Traffic & Maps', category: 'maps', supportedCountries: ['GLOBAL', 'EU'], supportedCurrencies: ['EUR', 'USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['GEOCODE', 'ROUTE'] },
  ],
  geocoding: [
    { providerId: 'mapbox', displayName: 'Mapbox Geocoding v5', category: 'geocoding', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['accessToken'], capabilities: ['GEOCODE', 'REVERSE_GEOCODE'] },
    { providerId: 'google_maps', displayName: 'Google Maps Geocoding', category: 'geocoding', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['GEOCODE', 'REVERSE_GEOCODE'] },
    { providerId: 'nominatim', displayName: 'OpenStreetMap Nominatim', category: 'geocoding', supportedCountries: ['GLOBAL'], supportedCurrencies: ['EUR'], status: 'CATALOG_ONLY', credentialRequirements: ['userAgent'], capabilities: ['GEOCODE', 'REVERSE_GEOCODE'] },
  ],
  routing: [
    { providerId: 'mapbox', displayName: 'Mapbox Directions', category: 'routing', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['accessToken'], capabilities: ['ROUTE', 'AVOID_TOLLS'] },
    { providerId: 'google_maps', displayName: 'Google Routes API', category: 'routing', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['ROUTE'] },
    { providerId: 'graphhopper', displayName: 'GraphHopper Routing Engine', category: 'routing', supportedCountries: ['GLOBAL'], supportedCurrencies: ['EUR'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['ROUTE'] },
  ],
  distance_matrix: [
    { providerId: 'mapbox', displayName: 'Mapbox Distance Matrix', category: 'distance_matrix', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['accessToken'], capabilities: ['DISTANCE_MATRIX'] },
    { providerId: 'google_maps', displayName: 'Google Distance Matrix', category: 'distance_matrix', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['DISTANCE_MATRIX'] },
    { providerId: 'osrm', displayName: 'Open Source Routing Machine (OSRM)', category: 'distance_matrix', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['endpointUrl'], capabilities: ['DISTANCE_MATRIX'] },
  ],
  places_search: [
    { providerId: 'google_places', displayName: 'Google Places API', category: 'places_search', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['PLACE_SEARCH', 'PLACE_DETAILS'] },
    { providerId: 'foursquare', displayName: 'Foursquare Places API', category: 'places_search', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['PLACE_SEARCH'] },
  ],
  identity_kyc: [
    { providerId: 'hyperverge', displayName: 'HyperVerge AI Verification', category: 'identity_kyc', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['appId', 'appKey'], capabilities: ['DL_VERIFICATION', 'RC_VERIFICATION', 'PAN_VERIFY', 'FACE_MATCH'] },
    { providerId: 'surepass', displayName: 'Surepass India KYC', category: 'identity_kyc', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiToken'], capabilities: ['PAN_VERIFY', 'AADHAAR_VERIFY', 'DL_VERIFICATION', 'RC_VERIFICATION'] },
    { providerId: 'mock_kyc', displayName: 'Mock Identity Verification', category: 'identity_kyc', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['PAN_VERIFY'] },
    { providerId: 'signzy', displayName: 'Signzy Enterprise KYC', category: 'identity_kyc', supportedCountries: ['IN', 'US'], supportedCurrencies: ['INR', 'USD'], status: 'CATALOG_ONLY', credentialRequirements: ['username', 'patToken'], capabilities: ['PAN_VERIFY', 'BANK_VERIFY'] },
    { providerId: 'onfido', displayName: 'Onfido Identity Verification', category: 'identity_kyc', supportedCountries: ['GLOBAL', 'EU', 'US'], supportedCurrencies: ['USD', 'EUR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiToken'], capabilities: ['FACE_MATCH', 'DOCUMENT_VERIFY'] },
  ],
  vehicle_gps_telematics: [
    { providerId: 'traccar', displayName: 'Traccar GPS Telematics Gateway', category: 'vehicle_gps_telematics', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['serverUrl', 'apiToken'], capabilities: ['LIVE_POSITION', 'IMMOBILIZE', 'TELEMETRY_HISTORY'] },
    { providerId: 'mock_telematics', displayName: 'Mock Vehicle Telematics Provider', category: 'vehicle_gps_telematics', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['LIVE_POSITION'] },
    { providerId: 'geotab', displayName: 'Geotab Fleet Telematics', category: 'vehicle_gps_telematics', supportedCountries: ['GLOBAL', 'US', 'EU'], supportedCurrencies: ['USD', 'EUR'], status: 'REAL_ADAPTER', credentialRequirements: ['database', 'username', 'password'], capabilities: ['LIVE_POSITION', 'ODOMETER'] },
    { providerId: 'samsara', displayName: 'Samsara Connected Operations', category: 'vehicle_gps_telematics', supportedCountries: ['GLOBAL', 'US'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiToken'], capabilities: ['LIVE_POSITION', 'CRASH_DETECTION'] },
  ],
  accounting: [
    { providerId: 'zoho_books', displayName: 'Zoho Books ERP & Invoicing', category: 'accounting', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['orgId', 'authToken'], capabilities: ['CREATE_INVOICE', 'SYNC_CUSTOMER', 'CALCULATE_TAX'] },
    { providerId: 'mock_accounting', displayName: 'Mock ERP Ledger', category: 'accounting', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'SIMULATION_MOCK', credentialRequirements: ['mockKey'], capabilities: ['CREATE_INVOICE'] },
    { providerId: 'tally', displayName: 'Tally Prime Integration', category: 'accounting', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'CATALOG_ONLY', credentialRequirements: ['xmlEndpoint'], capabilities: ['EXPORT_LEDGER'] },
    { providerId: 'quickbooks', displayName: 'Intuit QuickBooks Online', category: 'accounting', supportedCountries: ['US', 'GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['clientId', 'clientSecret'], capabilities: ['CREATE_INVOICE'] },
    { providerId: 'xero', displayName: 'Xero Cloud Accounting', category: 'accounting', supportedCountries: ['AU', 'NZ', 'GB', 'US'], supportedCurrencies: ['USD', 'GBP'], status: 'CATALOG_ONLY', credentialRequirements: ['clientId', 'clientSecret'], capabilities: ['CREATE_INVOICE'] },
  ],
  tax_gst: [
    { providerId: 'zoho_books', displayName: 'Zoho Books GST Engine', category: 'tax_gst', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['orgId'], capabilities: ['TAX_CALCULATION', 'GST_E_INVOICE'] },
    { providerId: 'clear_tax', displayName: 'Clear (ClearTax) GST Suite', category: 'tax_gst', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'CATALOG_ONLY', credentialRequirements: ['authKey', 'gstin'], capabilities: ['GST_E_INVOICE', 'EWAY_BILL'] },
    { providerId: 'avalara', displayName: 'Avalara AvaTax', category: 'tax_gst', supportedCountries: ['US', 'GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['accountId', 'licenseKey'], capabilities: ['TAX_CALCULATION'] },
  ],
  search: [
    { providerId: 'meilisearch', displayName: 'Meilisearch Fast Engine', category: 'search', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['host', 'apiKey'], capabilities: ['INDEX_DOCUMENT', 'SEARCH_QUERY'] },
    { providerId: 'typesense', displayName: 'Typesense Search', category: 'search', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['SEARCH_QUERY'] },
    { providerId: 'algolia', displayName: 'Algolia Search & Discovery', category: 'search', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['appId', 'apiKey'], capabilities: ['SEARCH_QUERY'] },
  ],
  analytics: [
    { providerId: 'posthog', displayName: 'PostHog Product Analytics', category: 'analytics', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey', 'host'], capabilities: ['TRACK_EVENT', 'IDENTIFY_USER', 'BATCH_EVENTS'] },
    { providerId: 'mixpanel', displayName: 'Mixpanel Analytics', category: 'analytics', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['token'], capabilities: ['TRACK_EVENT'] },
    { providerId: 'segment', displayName: 'Twilio Segment CDP', category: 'analytics', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['writeKey'], capabilities: ['TRACK_EVENT', 'IDENTIFY_USER'] },
  ],
  ai_llm: [
    { providerId: 'gemini', displayName: 'Google Gemini 1.5 Flash / Pro', category: 'ai_llm', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['AI_CHAT', 'AI_TEXT_GENERATION', 'AI_SUMMARIZATION', 'AI_CLASSIFICATION', 'AI_EMBEDDINGS'] },
    { providerId: 'openai', displayName: 'OpenAI GPT-4o / ChatGPT', category: 'ai_llm', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['AI_CHAT', 'AI_TEXT_GENERATION'] },
    { providerId: 'anthropic', displayName: 'Anthropic Claude 3.5 Sonnet', category: 'ai_llm', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['AI_CHAT'] },
    { providerId: 'azure_openai', displayName: 'Azure OpenAI Enterprise', category: 'ai_llm', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['endpoint', 'apiKey'], capabilities: ['AI_CHAT'] },
  ],
  ocr: [
    { providerId: 'hyperverge', displayName: 'HyperVerge Document OCR', category: 'ocr', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['appId', 'appKey'], capabilities: ['OCR_EXTRACTION'] },
    { providerId: 'google_vision', displayName: 'Google Cloud Vision OCR', category: 'ocr', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['OCR_EXTRACTION'] },
    { providerId: 'aws_textract', displayName: 'Amazon Textract', category: 'ocr', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['accessKey', 'secretKey'], capabilities: ['OCR_EXTRACTION'] },
  ],
  document_verification: [
    { providerId: 'hyperverge', displayName: 'HyperVerge Document AI', category: 'document_verification', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['appId', 'appKey'], capabilities: ['VERIFY_DOCUMENT'] },
    { providerId: 'surepass', displayName: 'Surepass Document AI', category: 'document_verification', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiToken'], capabilities: ['VERIFY_DOCUMENT'] },
    { providerId: 'persona', displayName: 'Persona Identity Verification', category: 'document_verification', supportedCountries: ['US', 'GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['VERIFY_DOCUMENT'] },
  ],
  e_signature: [
    { providerId: 'docusign', displayName: 'DocuSign eSignature', category: 'e_signature', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['integrationKey', 'rsaKey'], capabilities: ['SIGN_DOCUMENT', 'TEMPLATE_SIGN'] },
    { providerId: 'zoho_sign', displayName: 'Zoho Sign', category: 'e_signature', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR', 'USD'], status: 'CATALOG_ONLY', credentialRequirements: ['authToken'], capabilities: ['SIGN_DOCUMENT'] },
  ],
  cloud_messaging: [
    { providerId: 'fcm', displayName: 'Firebase Cloud Messaging', category: 'cloud_messaging', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['serviceAccountJson'], capabilities: ['SEND_PUSH'] },
    { providerId: 'aws_sns', displayName: 'AWS SNS Cloud Messaging', category: 'cloud_messaging', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['accessKey', 'secretKey'], capabilities: ['SEND_PUSH'] },
  ],
  customer_support: [
    { providerId: 'freshdesk', displayName: 'Freshdesk Customer Service', category: 'customer_support', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey', 'domain'], capabilities: ['CREATE_TICKET', 'SYNC_CONTACT'] },
    { providerId: 'zendesk', displayName: 'Zendesk Support Suite', category: 'customer_support', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiToken', 'subdomain'], capabilities: ['CREATE_TICKET'] },
  ],
  voice_calling: [
    { providerId: 'twilio_voice', displayName: 'Twilio Programmable Voice', category: 'voice_calling', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['accountSid', 'authToken'], capabilities: ['VOICE_CALL', 'IVR'] },
    { providerId: 'exotel_voice', displayName: 'Exotel Cloud Telephony', category: 'voice_calling', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'CATALOG_ONLY', credentialRequirements: ['sid', 'token'], capabilities: ['VOICE_CALL'] },
  ],
  translation: [
    { providerId: 'google_translate', displayName: 'Google Cloud Translation', category: 'translation', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['TRANSLATE_TEXT'] },
    { providerId: 'deepl', displayName: 'DeepL Translation API', category: 'translation', supportedCountries: ['GLOBAL', 'EU'], supportedCurrencies: ['EUR', 'USD'], status: 'CATALOG_ONLY', credentialRequirements: ['authKey'], capabilities: ['TRANSLATE_TEXT'] },
  ],
  image_processing: [
    { providerId: 'cloudinary', displayName: 'Cloudinary Image & Video CDN', category: 'image_processing', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['cloudName', 'apiKey', 'apiSecret'], capabilities: ['RESIZE', 'CROP', 'WATERMARK'] },
    { providerId: 'imgix', displayName: 'imgix Real-Time Processing', category: 'image_processing', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['OPTIMIZE', 'THUMBNAIL'] },
  ],
  fraud_risk_detection: [
    { providerId: 'sift', displayName: 'Sift Digital Trust & Safety', category: 'fraud_risk_detection', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['RISK_SCORE', 'DEVICE_FINGERPRINT'] },
    { providerId: 'seon', displayName: 'SEON Fraud Fighters', category: 'fraud_risk_detection', supportedCountries: ['GLOBAL', 'EU'], supportedCurrencies: ['USD', 'EUR'], status: 'CATALOG_ONLY', credentialRequirements: ['licenseKey'], capabilities: ['EMAIL_RISK', 'PHONE_RISK'] },
  ],
  address_validation: [
    { providerId: 'google_address_validation', displayName: 'Google Address Validation API', category: 'address_validation', supportedCountries: ['GLOBAL', 'US'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['VALIDATE_ADDRESS'] },
    { providerId: 'smartystreets', displayName: 'Smarty (SmartyStreets)', category: 'address_validation', supportedCountries: ['US', 'GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['authId', 'authToken'], capabilities: ['VALIDATE_ADDRESS'] },
  ],
  currency_fx: [
    { providerId: 'fixer_io', displayName: 'Fixer.io Exchange Rates', category: 'currency_fx', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD', 'EUR'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey'], capabilities: ['EXCHANGE_RATE', 'HISTORICAL_RATE'] },
    { providerId: 'open_exchange_rates', displayName: 'Open Exchange Rates', category: 'currency_fx', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['appId'], capabilities: ['EXCHANGE_RATE'] },
  ],
  business_verification: [
    { providerId: 'surepass_gst', displayName: 'Surepass GST & MCA Verification', category: 'business_verification', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiToken'], capabilities: ['GST_VERIFICATION', 'CIN_VERIFICATION'] },
    { providerId: 'karza', displayName: 'Karza (Perfios) Corporate Due Diligence', category: 'business_verification', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'CATALOG_ONLY', credentialRequirements: ['keyId'], capabilities: ['GST_VERIFICATION'] },
  ],
  email_delivery: [
    { providerId: 'resend', displayName: 'Resend Transactional Engine', category: 'email_delivery', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['SEND_EMAIL'] },
    { providerId: 'sendgrid', displayName: 'SendGrid Delivery Engine', category: 'email_delivery', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['SEND_EMAIL'] },
    { providerId: 'mailgun', displayName: 'Mailgun (Sinch)', category: 'email_delivery', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['apiKey', 'domain'], capabilities: ['SEND_EMAIL'] },
  ],
  sms_otp: [
    { providerId: 'msg91_otp', displayName: 'MSG91 SendOTP Engine', category: 'sms_otp', supportedCountries: ['IN', 'GLOBAL'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['authKey'], capabilities: ['SEND_OTP', 'VERIFY_OTP'] },
    { providerId: 'twilio_verify', displayName: 'Twilio Verify SMS OTP', category: 'sms_otp', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'REAL_ADAPTER', credentialRequirements: ['serviceSid', 'authToken'], capabilities: ['SEND_OTP', 'VERIFY_OTP'] },
  ],
  whatsapp_otp: [
    { providerId: 'meta_whatsapp_otp', displayName: 'Meta WhatsApp Authentication OTP', category: 'whatsapp_otp', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['INR', 'USD'], status: 'REAL_ADAPTER', credentialRequirements: ['systemUserToken'], capabilities: ['SEND_OTP'] },
    { providerId: 'gupshup_otp', displayName: 'Gupshup 2FA WhatsApp Engine', category: 'whatsapp_otp', supportedCountries: ['IN'], supportedCurrencies: ['INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['SEND_OTP'] },
  ],
  maps_navigation: [
    { providerId: 'mapbox', displayName: 'Mapbox Navigation SDK Engine', category: 'maps_navigation', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['accessToken'], capabilities: ['TURN_BY_TURN', 'ROUTE'] },
    { providerId: 'google_maps', displayName: 'Google Maps Navigation', category: 'maps_navigation', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['apiKey'], capabilities: ['ROUTE'] },
  ],
  vehicle_data_telemetry: [
    { providerId: 'traccar', displayName: 'Traccar Telemetry Ingestion', category: 'vehicle_data_telemetry', supportedCountries: ['GLOBAL', 'IN'], supportedCurrencies: ['USD', 'INR'], status: 'REAL_ADAPTER', credentialRequirements: ['serverUrl', 'apiToken'], capabilities: ['LIVE_POSITION', 'SPEED', 'IGNITION'] },
    { providerId: 'geotab_telemetry', displayName: 'Geotab MyGeotab API', category: 'vehicle_data_telemetry', supportedCountries: ['GLOBAL'], supportedCurrencies: ['USD'], status: 'CATALOG_ONLY', credentialRequirements: ['username', 'password'], capabilities: ['LIVE_POSITION'] },
  ],
};
