import { IntegrationCategory } from '../registry/provider.types';
import {
  CatalogProviderMetadata,
  ProviderActivationState,
  ProviderEnvironment,
  ProviderLifecycleState,
  ProviderCertificationLevel,
} from './provider-catalog.types';
import { ENTERPRISE_EXPANDED_PROVIDERS } from './enterprise-providers.data';

export const INITIAL_PROVIDER_CATALOG: CatalogProviderMetadata[] = [
  // =========================================================================
  // PAYMENTS
  // =========================================================================
  {
    providerId: 'razorpay',
    category: IntegrationCategory.PAYMENT,
    name: 'Razorpay',
    tagline: 'Leading unified payment gateway for India & Southeast Asia',
    description:
      'Accept UPI, credit/debit cards, netbanking, wallets, and instant settlements with built-in refund integrity and automated webhook orchestration.',
    icon: 'payment',
    websiteUrl: 'https://razorpay.com',
    documentation: {
      overview: 'Full-stack payment suite with native UPI intent, card vaulting, and recurring deposits.',
      docsUrl: 'https://razorpay.com/docs',
      setupGuide: 'Obtain Key ID and Secret from Razorpay Dashboard > Settings > API Keys. Enable webhooks for payment.captured, order.paid, and refund.processed.',
      webhookGuide: 'Set webhook endpoint to /payments/webhook with your configured Webhook Secret.',
      supportEmail: 'support@razorpay.com',
    },
    version: '2.9.6',
    apiVersion: 'v1',
    author: 'Razorpay Software Pvt. Ltd.',
    tags: ['payments', 'upi', 'cards', 'india', 'wallets'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      {
        key: 'keyId',
        label: 'Key ID',
        type: 'string',
        required: true,
        isSecret: false,
        description: 'Razorpay API Key ID (rzp_test_... or rzp_live_...)',
        placeholder: 'rzp_test_xxxxxxxxxx',
        validationRegex: '^rzp_(test|live)_[A-Za-z0-9]+$',
        environmentScoped: true,
      },
      {
        key: 'keySecret',
        label: 'Key Secret',
        type: 'password',
        required: true,
        isSecret: true,
        description: 'Razorpay Key Secret used for request signing and server authorization',
        placeholder: '••••••••••••••••',
        environmentScoped: true,
      },
      {
        key: 'webhookSecret',
        label: 'Webhook Secret',
        type: 'password',
        required: true,
        isSecret: true,
        description: 'Secret token configured on the Razorpay Dashboard for HMAC SHA256 webhook verification',
        placeholder: '••••••••••••••••',
        environmentScoped: true,
      },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'CAPTURE_PAYMENT',
      'REFUND_PAYMENT',
      'WEBHOOK_HANDLING',
      'WEBHOOKS',
      'RECONCILIATION',
      'SPLIT_PAYMENT',
      'INSTANT_REFUND',
      '3DS_SECURE',
      'UPI_INTENT',
    ],
    supportedCurrencies: ['INR', 'USD', 'EUR', 'AED'],
    supportedCountries: ['IN', 'AE', 'SG', 'MY'],
    supportedWebhookEvents: [
      'payment.captured',
      'payment.failed',
      'order.paid',
      'refund.processed',
      'refund.failed',
    ],
    webhookSignatureHeader: 'x-razorpay-signature',
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    adapterImplemented: true,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET', 'EMI'],
    costModel: { percentageFee: 2.0, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.95,
    maxRps: 200,
    priority: 1,
    fallbackProviderId: 'cashfree',
  },
  {
    providerId: 'stripe',
    category: IntegrationCategory.PAYMENT,
    name: 'Stripe',
    tagline: 'Global financial infrastructure supporting 135+ currencies',
    description:
      'Seamless global checkout supporting PaymentIntents, Apple Pay, Google Pay, international cards, and automated dispute management.',
    icon: 'credit_card',
    websiteUrl: 'https://stripe.com',
    documentation: {
      overview: 'Industry-standard payment platform for international expansion, multi-currency pricing, and fraud prevention.',
      docsUrl: 'https://stripe.com/docs',
      setupGuide: 'Create restricted API keys in the Stripe Developer Dashboard with permissions for charges, refunds, and payment intents.',
      webhookGuide: 'Add endpoint /integrations/webhooks/stripe with signing secret.',
      supportEmail: 'support@stripe.com',
    },
    version: '15.2.0',
    apiVersion: '2024-06-20',
    author: 'Stripe Inc.',
    tags: ['payments', 'global', 'cards', 'applepay', 'googlepay', 'multi-currency'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      {
        key: 'publishableKey',
        label: 'Publishable Key',
        type: 'string',
        required: true,
        isSecret: false,
        description: 'Stripe Publishable API Key (pk_test_... or pk_live_...)',
        placeholder: 'pk_test_xxxxxxxxxx',
        environmentScoped: true,
      },
      {
        key: 'secretKey',
        label: 'Secret Key',
        type: 'password',
        required: true,
        isSecret: true,
        description: 'Stripe Secret API Key (sk_test_... or sk_live_...)',
        placeholder: 'sk_test_••••••••••••',
        environmentScoped: true,
      },
      {
        key: 'webhookSecret',
        label: 'Webhook Signing Secret',
        type: 'password',
        required: true,
        isSecret: true,
        description: 'Endpoint signing secret (whsec_...) for HMAC signature verification',
        placeholder: 'whsec_••••••••••••',
        environmentScoped: true,
      },
    ],
    supportedCapabilities: [
      'CREATE_ORDER',
      'VERIFY_PAYMENT',
      'CAPTURE_PAYMENT',
      'REFUND_PAYMENT',
      'WEBHOOK_HANDLING',
      '3DS_SECURE',
      'MULTI_CURRENCY',
    ],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AED', 'INR', 'SGD', 'CAD', 'AUD'],
    supportedCountries: ['US', 'GB', 'AE', 'SG', 'EU', 'CA', 'AU', 'IN'],
    supportedWebhookEvents: [
      'payment_intent.succeeded',
      'payment_intent.payment_failed',
      'charge.refunded',
      'charge.dispute.created',
    ],
    webhookSignatureHeader: 'stripe-signature',
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.LIVE_READY,
    certificationLevel: ProviderCertificationLevel.PRODUCTION_VALIDATED,
    adapterImplemented: true,
    supportedPaymentMethods: ['CREDIT_CARD', 'DEBIT_CARD', 'INTERNATIONAL_CARD', 'APPLE_PAY', 'GOOGLE_PAY'],
    costModel: { percentageFee: 2.9, fixedFee: 0.30, currency: 'USD' },
    slaUptimePercent: 99.99,
    maxRps: 300,
    priority: 90,
    fallbackProviderId: 'razorpay',
  },
  {
    providerId: 'cashfree',
    category: IntegrationCategory.PAYMENT,
    name: 'Cashfree Payments',
    tagline: 'High-speed payment gateway & instant automated payout engine',
    description:
      'Engineered for Indian marketplaces with deep UPI Autopay, instantaneous security deposit refunds, and vendor settlement split capabilities.',
    icon: 'account_balance_wallet',
    websiteUrl: 'https://cashfree.com',
    documentation: {
      overview: 'Full-stack payment gateway & payout routing for vehicle rentals.',
      docsUrl: 'https://docs.cashfree.com',
      setupGuide: 'Generate App ID and Secret Key in Cashfree Merchant Portal.',
      supportEmail: 'care@cashfree.com',
    },
    version: '4.1.0',
    author: 'Cashfree Payments India Pvt Ltd',
    tags: ['payments', 'upi', 'instant-refund', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      {
        key: 'appId',
        label: 'App ID',
        type: 'string',
        required: true,
        isSecret: false,
        description: 'Cashfree Merchant App ID',
        environmentScoped: true,
      },
      {
        key: 'secretKey',
        label: 'Secret Key',
        type: 'password',
        required: true,
        isSecret: true,
        description: 'Cashfree API Secret Key',
        environmentScoped: true,
      },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'INSTANT_REFUND', 'SPLIT_PAYMENT', 'UPI_INTENT'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.SANDBOX_READY,
    certificationLevel: ProviderCertificationLevel.SANDBOX_VALIDATED,
    adapterImplemented: false,
    supportedPaymentMethods: ['UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET'],
    costModel: { percentageFee: 1.9, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 99.9,
    maxRps: 150,
    priority: 2,
  },
  {
    providerId: 'payu',
    category: IntegrationCategory.PAYMENT,
    name: 'PayU India',
    tagline: 'Enterprise omni-channel payment gateway and checkout solutions',
    description: 'High availability checkout covering 150+ payment modes across India, LATAM, and EMEA.',
    icon: 'payments',
    websiteUrl: 'https://payu.in',
    documentation: {
      overview: 'Enterprise payment routing with high conversion checkout.',
      docsUrl: 'https://devguide.payu.in',
      setupGuide: 'Enter Merchant Key and Salt from PayU dashboard.',
    },
    version: '3.2.0',
    author: 'PayU Payments',
    tags: ['payments', 'india', 'emea'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantKey', label: 'Merchant Key', type: 'string', required: true, isSecret: false, description: 'PayU Key' },
      { key: 'merchantSalt', label: 'Merchant Salt', type: 'password', required: true, isSecret: true, description: 'PayU Salt' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT'],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'PL', 'TR'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 80,
  },
  {
    providerId: 'phonepe',
    category: IntegrationCategory.PAYMENT,
    name: 'PhonePe Payment Gateway',
    tagline: 'Direct-to-bank UPI intent & PhonePe ecosystem gateway',
    description: 'Native UPI flow with industry-highest success rates for mobile customer applications.',
    icon: 'phone_android',
    websiteUrl: 'https://phonepe.com',
    documentation: {
      overview: 'PhonePe standard checkout with fast-track UPI.',
      docsUrl: 'https://developer.phonepe.com',
      setupGuide: 'Obtain Merchant ID and Salt Key from PhonePe Developer Portal.',
    },
    version: '2.0.1',
    author: 'PhonePe Pvt Ltd',
    tags: ['payments', 'upi', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantId', label: 'Merchant ID', type: 'string', required: true, isSecret: false, description: 'PhonePe Merchant ID' },
      { key: 'saltKey', label: 'Salt Key', type: 'password', required: true, isSecret: true, description: 'PhonePe Secret Salt Key' },
      { key: 'saltIndex', label: 'Salt Index', type: 'number', required: true, isSecret: false, description: 'Salt Index (e.g. 1)' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT'],
    supportedCurrencies: ['INR'],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 75,
  },
  {
    providerId: 'adyen',
    category: IntegrationCategory.PAYMENT,
    name: 'Adyen',
    tagline: 'Global enterprise financial technology platform',
    description: 'Unified cross-border commerce with intelligent payment routing and risk management.',
    icon: 'account_balance',
    websiteUrl: 'https://adyen.com',
    documentation: {
      overview: 'Global payments leader for large multi-city rental chains.',
      docsUrl: 'https://docs.adyen.com',
      setupGuide: 'Configure Adyen Merchant Account and API key.',
    },
    version: '12.0.0',
    author: 'Adyen N.V.',
    tags: ['payments', 'global', 'enterprise'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'merchantAccount', label: 'Merchant Account', type: 'string', required: true, isSecret: false, description: 'Adyen Account' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Adyen API Key' },
    ],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', '3DS_SECURE', 'MULTI_CURRENCY'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AED', 'SGD'],
    supportedCountries: ['US', 'GB', 'EU', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 70,
  },
  {
    providerId: 'mock_payment',
    category: IntegrationCategory.PAYMENT,
    name: 'Mock Payment Provider',
    tagline: 'Built-in sandbox simulation provider for local test suites',
    description: 'Instant, deterministic mock orders and refunds for automated integration testing.',
    icon: 'bug_report',
    websiteUrl: 'https://drivego.in',
    documentation: {
      overview: 'In-memory mock payment provider for local dev and CI/CD pipelines.',
      docsUrl: 'https://drivego.in/docs',
      setupGuide: 'No credentials required. Always healthy in development environments.',
    },
    version: '1.0.0',
    author: 'DriveGo Core Team',
    tags: ['test', 'mock', 'sandbox'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [],
    supportedCapabilities: ['CREATE_ORDER', 'VERIFY_PAYMENT', 'REFUND_PAYMENT', 'SPLIT_PAYMENT'],
    supportedCurrencies: ['INR', 'USD'],
    supportedCountries: ['IN', 'US'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    lifecycleState: ProviderLifecycleState.SANDBOX_READY,
    certificationLevel: ProviderCertificationLevel.SANDBOX_VALIDATED,
    adapterImplemented: true,
    supportedPaymentMethods: ['UPI', 'CARD', 'WALLET'],
    costModel: { percentageFee: 0, fixedFee: 0, currency: 'INR' },
    slaUptimePercent: 100,
    maxRps: 1000,
    priority: 99,
  },

  // =========================================================================
  // WHATSAPP
  // =========================================================================
  {
    providerId: 'meta',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Meta WhatsApp Cloud API',
    tagline: 'Official Meta Graph API for WhatsApp Business Messaging',
    description: 'Send certified templates for booking confirmations, trip reminders, invoices, and emergency alerts.',
    icon: 'chat',
    websiteUrl: 'https://developers.facebook.com/docs/whatsapp/cloud-api',
    documentation: {
      overview: 'Direct Meta Cloud API hosting with zero middleman latency.',
      docsUrl: 'https://developers.facebook.com/docs/whatsapp',
      setupGuide: 'Configure System User Access Token and Phone Number ID in Meta Business Manager.',
    },
    version: '20.0.0',
    apiVersion: 'v20.0',
    author: 'Meta Platforms Inc.',
    tags: ['whatsapp', 'messaging', 'meta', 'templates'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessToken', label: 'Access Token', type: 'password', required: true, isSecret: true, description: 'Meta Permanent System User Token' },
      { key: 'phoneNumberId', label: 'Phone Number ID', type: 'string', required: true, isSecret: false, description: 'WhatsApp Business Phone Number ID' },
      { key: 'apiVersion', label: 'API Version', type: 'string', required: false, isSecret: false, description: 'Graph API version (default v20.0)' },
    ],
    supportedCapabilities: ['SEND_TEMPLATE', 'SEND_TEXT', 'SEND_MEDIA', 'WEBHOOK_DELIVERY_STATUS'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'AE', 'US', 'GB', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 1,
    fallbackProviderId: 'gupshup_whatsapp',
  },
  {
    providerId: 'gupshup_whatsapp',
    category: IntegrationCategory.MESSAGING_WHATSAPP,
    name: 'Gupshup WhatsApp BSP',
    tagline: 'Enterprise WhatsApp Business Solution Provider',
    description: 'High-volume WhatsApp delivery engine with conversational AI and auto-fallback to SMS.',
    icon: 'forum',
    websiteUrl: 'https://gupshup.io',
    documentation: {
      overview: 'Gupshup enterprise WhatsApp proxy.',
      docsUrl: 'https://docs.gupshup.io',
      setupGuide: 'Enter Gupshup App Name and API Key.',
    },
    version: '2.2.0',
    author: 'Gupshup Technology',
    tags: ['whatsapp', 'bsp', 'enterprise'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'appName', label: 'App Name', type: 'string', required: true, isSecret: false, description: 'Gupshup App Name' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Gupshup Account API Key' },
    ],
    supportedCapabilities: ['SEND_TEMPLATE', 'SEND_TEXT'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'AE', 'US'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 2,
  },

  // =========================================================================
  // SMS
  // =========================================================================
  {
    providerId: 'msg91',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'MSG91 SMS Gateway',
    tagline: 'Enterprise DLT-compliant SMS & OTP delivery platform in India',
    description: 'High-speed transactional SMS and verification OTPs with DLT template binding and delivery reporting.',
    icon: 'sms',
    websiteUrl: 'https://msg91.com',
    documentation: {
      overview: 'Indian DLT-approved SMS gateway optimized for low-latency OTP dispatch.',
      docsUrl: 'https://docs.msg91.com',
      setupGuide: 'Obtain Auth Key from MSG91 control panel and register transactional Sender ID (e.g. DRIVGO).',
    },
    version: '5.0.0',
    author: 'Walkover Technologies',
    tags: ['sms', 'otp', 'dlt', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'authKey', label: 'Auth Key', type: 'password', required: true, isSecret: true, description: 'MSG91 API Authentication Key' },
      { key: 'templateId', label: 'Template ID', type: 'string', required: true, isSecret: false, description: 'DLT Registered Template ID' },
      { key: 'senderId', label: 'Sender ID', type: 'string', required: false, isSecret: false, description: 'Approved 6-character Sender ID (e.g. DRIVGO)' },
    ],
    supportedCapabilities: ['SEND_OTP', 'SEND_TRANSACTIONAL', 'DELIVERY_REPORT'],
    supportedCurrencies: [],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
    fallbackProviderId: 'twilio',
  },
  {
    providerId: 'twilio',
    category: IntegrationCategory.MESSAGING_SMS,
    name: 'Twilio SMS',
    tagline: 'Global programmable SMS & messaging platform',
    description: 'Worldwide carrier network delivery for international customers and cross-border rentals.',
    icon: 'message',
    websiteUrl: 'https://twilio.com',
    documentation: {
      overview: 'Global cloud telecom communications.',
      docsUrl: 'https://www.twilio.com/docs/sms',
      setupGuide: 'Copy Account SID, Auth Token, and Twilio phone number.',
    },
    version: '4.0.0',
    author: 'Twilio Inc.',
    tags: ['sms', 'global', 'telecom'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accountSid', label: 'Account SID', type: 'string', required: true, isSecret: false, description: 'Twilio Account SID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, isSecret: true, description: 'Twilio Auth Token' },
      { key: 'fromNumber', label: 'From Phone Number', type: 'string', required: true, isSecret: false, description: 'Registered Twilio E.164 phone number' },
    ],
    supportedCapabilities: ['SEND_TRANSACTIONAL', 'SEND_OTP', 'SEND_PROMOTIONAL', 'DELIVERY_REPORT'],
    supportedCurrencies: [],
    supportedCountries: ['US', 'GB', 'AE', 'SG', 'IN', 'EU', 'CA', 'AU'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 90,
  },

  // =========================================================================
  // EMAIL
  // =========================================================================
  {
    providerId: 'resend',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'Resend',
    tagline: 'Modern developer-first email platform with first-class deliverability',
    description: 'Clean HTML transactional emails for invoices, trip itineraries, booking receipts, and policy agreements.',
    icon: 'mail',
    websiteUrl: 'https://resend.com',
    documentation: {
      overview: 'Fast, modern transactional email API with React Email compatibility.',
      docsUrl: 'https://resend.com/docs',
      setupGuide: 'Generate an API key in Resend dashboard and verify your sending domain DNS records.',
    },
    version: '2.0.0',
    author: 'Resend Inc.',
    tags: ['email', 'transactional', 'invoices'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Resend API Key (re_...)' },
      { key: 'fromEmail', label: 'Sender Address', type: 'string', required: false, isSecret: false, description: 'From address (e.g. notifications@drivego.in)' },
    ],
    supportedCapabilities: ['SEND_TRANSACTIONAL', 'SEND_HTML', 'SEND_ATTACHMENT', 'SEND_TEMPLATE'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
    fallbackProviderId: 'sendgrid',
  },
  {
    providerId: 'sendgrid',
    category: IntegrationCategory.MESSAGING_EMAIL,
    name: 'SendGrid',
    tagline: 'Enterprise cloud email deliverability engine',
    description: 'Mass transactional and marketing email delivery with dedicated IP pools and deliverability intelligence.',
    icon: 'mark_email_read',
    websiteUrl: 'https://sendgrid.com',
    documentation: {
      overview: 'High-volume enterprise email provider.',
      docsUrl: 'https://docs.sendgrid.com',
      setupGuide: 'Generate a SendGrid API Key with Full Access or Mail Send permissions.',
    },
    version: '7.7.0',
    author: 'Twilio SendGrid',
    tags: ['email', 'enterprise', 'high-volume'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'SendGrid API Key (SG....)' },
      { key: 'fromEmail', label: 'Verified Sender', type: 'string', required: true, isSecret: false, description: 'Verified Single Sender email' },
    ],
    supportedCapabilities: ['SEND_TRANSACTIONAL', 'SEND_HTML', 'SEND_ATTACHMENT'],
    supportedCurrencies: [],
    supportedCountries: ['US', 'GB', 'IN', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 90,
  },

  // =========================================================================
  // PUSH NOTIFICATIONS
  // =========================================================================
  {
    providerId: 'fcm',
    category: IntegrationCategory.MESSAGING_PUSH,
    name: 'Firebase Cloud Messaging (FCM)',
    tagline: 'Cross-platform push messaging for Android, iOS, and Web',
    description: 'Direct push notification dispatch to user devices with multicast, background data payloads, and silent sync.',
    icon: 'notifications_active',
    websiteUrl: 'https://firebase.google.com/docs/cloud-messaging',
    documentation: {
      overview: 'Standard push notification infrastructure across Android, iOS, and Web clients.',
      docsUrl: 'https://firebase.google.com/docs/cloud-messaging',
      setupGuide: 'Download Service Account JSON from Firebase Console > Project Settings > Service accounts.',
    },
    version: '14.1.0',
    author: 'Google LLC',
    tags: ['push', 'mobile', 'firebase', 'notifications'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'projectId', label: 'Project ID', type: 'string', required: true, isSecret: false, description: 'Firebase Project ID' },
      { key: 'clientEmail', label: 'Client Email', type: 'string', required: true, isSecret: false, description: 'Service Account client email' },
      { key: 'privateKey', label: 'Private Key', type: 'textarea', required: true, isSecret: true, description: 'RSA Private Key from Service Account JSON' },
    ],
    supportedCapabilities: ['SEND_UNICAST', 'SEND_MULTICAST', 'SEND_TOPIC', 'DATA_PAYLOAD'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },

  // =========================================================================
  // MAPS & GEOSPATIAL
  // =========================================================================
  {
    providerId: 'google',
    category: IntegrationCategory.MAPS,
    name: 'Google Maps Platform',
    tagline: 'Accurate global mapping, geocoding, distance matrix, and route calculation',
    description: 'Sub-second geocoding, address autocomplete, doorstep delivery route calculations, and hub radius verification.',
    icon: 'map',
    websiteUrl: 'https://mapsplatform.google.com',
    documentation: {
      overview: 'Industry gold standard for mapping, location lookup, and ETA routing.',
      docsUrl: 'https://developers.google.com/maps',
      setupGuide: 'Enable Places API, Geocoding API, and Distance Matrix API in Google Cloud Console.',
    },
    version: '3.0.0',
    author: 'Google LLC',
    tags: ['maps', 'geocoding', 'distance-matrix', 'navigation'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, isSecret: true, description: 'Google Cloud API Key with Maps permissions' },
    ],
    supportedCapabilities: ['GEOCODING', 'REVERSE_GEOCODING', 'DISTANCE_MATRIX', 'DIRECTIONS', 'PLACE_AUTOCOMPLETE'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
    fallbackProviderId: 'mapbox',
  },
  {
    providerId: 'mapbox',
    category: IntegrationCategory.MAPS,
    name: 'Mapbox',
    tagline: 'Customizable location & navigation developer platform',
    description: 'High performance vector maps, turn-by-turn routing, and custom geospatial boundary querying.',
    icon: 'explore',
    websiteUrl: 'https://mapbox.com',
    documentation: {
      overview: 'Developer-first mapping engine.',
      docsUrl: 'https://docs.mapbox.com',
      setupGuide: 'Create Secret Access Token in Mapbox Account Settings.',
    },
    version: '2.1.0',
    author: 'Mapbox Inc.',
    tags: ['maps', 'vector-tiles', 'navigation'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessToken', label: 'Access Token', type: 'password', required: true, isSecret: true, description: 'Mapbox Secret Token (sk.ey...)' },
    ],
    supportedCapabilities: ['GEOCODING', 'REVERSE_GEOCODING', 'DISTANCE_MATRIX', 'DIRECTIONS'],
    supportedCurrencies: [],
    supportedCountries: ['US', 'GB', 'IN', 'AE'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 90,
  },

  // =========================================================================
  // STORAGE
  // =========================================================================
  {
    providerId: 'r2',
    category: IntegrationCategory.STORAGE,
    name: 'Cloudflare R2 Storage',
    tagline: 'S3-compatible object storage with zero egress fees',
    description: 'Secure, cost-effective storage for vehicle inspection photos, driving licences, RC books, and damage claims.',
    icon: 'cloud_queue',
    websiteUrl: 'https://cloudflare.com/products/r2',
    documentation: {
      overview: 'High performance S3-compatible storage with no bandwidth/egress surcharges.',
      docsUrl: 'https://developers.cloudflare.com/r2',
      setupGuide: 'Create an R2 bucket and generate R2 API Token with Object Read & Write permissions.',
    },
    version: '3.10.0',
    author: 'Cloudflare Inc.',
    tags: ['storage', 's3', 'zero-egress', 'r2'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKeyId', label: 'Access Key ID', type: 'string', required: true, isSecret: false, description: 'Cloudflare R2 Access Key ID' },
      { key: 'secretAccessKey', label: 'Secret Access Key', type: 'password', required: true, isSecret: true, description: 'Cloudflare R2 Secret Access Key' },
      { key: 'endpoint', label: 'S3 API Endpoint', type: 'url', required: true, isSecret: false, description: 'R2 S3 API Endpoint URL (https://<account_id>.r2.cloudflarestorage.com)' },
      { key: 'bucketName', label: 'Bucket Name', type: 'string', required: true, isSecret: false, description: 'R2 Bucket name (e.g. drivego-uploads)' },
      { key: 'publicUrl', label: 'Public Domain / CDN URL', type: 'url', required: false, isSecret: false, description: 'Public custom domain or dev.r2.dev URL' },
    ],
    supportedCapabilities: ['PRESIGNED_UPLOAD', 'PRESIGNED_DOWNLOAD', 'DELETE_OBJECT', 'PUBLIC_READ'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
    fallbackProviderId: 's3',
  },
  {
    providerId: 's3',
    category: IntegrationCategory.STORAGE,
    name: 'Amazon Web Services (AWS) S3',
    tagline: 'Industry-leading cloud object storage with 99.999999999% durability',
    description: 'Enterprise compliance, cross-region replication, and lifecycle management for documents and photos.',
    icon: 'storage',
    websiteUrl: 'https://aws.amazon.com/s3',
    documentation: {
      overview: 'Scalable cloud object storage with strict IAM policy control.',
      docsUrl: 'https://docs.aws.amazon.com/s3',
      setupGuide: 'Create an IAM User with AmazonS3FullAccess or scoped bucket policies.',
    },
    version: '3.1084.0',
    author: 'Amazon Web Services Inc.',
    tags: ['storage', 'aws', 'enterprise'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'accessKeyId', label: 'Access Key ID', type: 'string', required: true, isSecret: false, description: 'AWS IAM Access Key' },
      { key: 'secretAccessKey', label: 'Secret Access Key', type: 'password', required: true, isSecret: true, description: 'AWS IAM Secret Key' },
      { key: 'region', label: 'AWS Region', type: 'string', required: true, isSecret: false, description: 'e.g. ap-south-1' },
      { key: 'bucketName', label: 'Bucket Name', type: 'string', required: true, isSecret: false, description: 'S3 Bucket name' },
    ],
    supportedCapabilities: ['PRESIGNED_UPLOAD', 'PRESIGNED_DOWNLOAD', 'DELETE_OBJECT', 'PUBLIC_READ'],
    supportedCurrencies: [],
    supportedCountries: ['US', 'GB', 'IN', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 90,
  },

  // =========================================================================
  // IDENTITY VERIFICATION & KYC
  // =========================================================================
  {
    providerId: 'surepass',
    category: IntegrationCategory.IDENTITY_VERIFICATION,
    name: 'Surepass Identity APIs',
    tagline: 'Instant Driving Licence, Aadhaar, PAN, and RC verification in India',
    description: 'Real-time government database verification for instant automated customer onboarding and RC authenticity.',
    icon: 'verified_user',
    websiteUrl: 'https://surepass.io',
    documentation: {
      overview: 'Direct Parivahan & UIDAI integrations for Indian identity verification.',
      docsUrl: 'https://docs.surepass.io',
      setupGuide: 'Generate Bearer Token in Surepass dashboard.',
    },
    version: '2.0.0',
    author: 'Surepass Technologies',
    tags: ['kyc', 'driving-licence', 'rc-verification', 'india'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'API Key (Bearer Token)', type: 'password', required: true, isSecret: true, description: 'Surepass API Token' },
    ],
    supportedCapabilities: ['DRIVING_LICENCE_VERIFY', 'VEHICLE_RC_VERIFY', 'AADHAAR_VERIFY', 'PAN_VERIFY'],
    supportedCurrencies: [],
    supportedCountries: ['IN'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },

  // =========================================================================
  // VEHICLE TRACKING & TELEMATICS
  // =========================================================================
  {
    providerId: 'teltonika',
    category: IntegrationCategory.VEHICLE_TRACKING,
    name: 'Teltonika Telematics',
    tagline: 'Industrial OBD-II and hardwired GPS telematics protocol integration',
    description: 'Continuous GPS pings, speed monitoring, odometer synchronization, and remote starter kill/immobilization.',
    icon: 'gps_fixed',
    websiteUrl: 'https://teltonika-gps.com',
    documentation: {
      overview: 'Standard Teltonika TCP/UDP protocol parser and telemetry ingestion.',
      docsUrl: 'https://wiki.teltonika-gps.com',
      setupGuide: 'Configure tracking gateway host and port in fleet management console.',
    },
    version: '1.4.0',
    author: 'Teltonika Telematics',
    tags: ['telematics', 'gps', 'obd2', 'immobilize'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'serverUrl', label: 'Telemetry Gateway URL', type: 'url', required: true, isSecret: false, description: 'Telemetry TCP/HTTP ingestion endpoint' },
      { key: 'apiSecret', label: 'API Secret', type: 'password', required: true, isSecret: true, description: 'Secret key for immobilizer command authorization' },
    ],
    supportedCapabilities: ['LIVE_TELEMETRY', 'ODOMETER_READING', 'FUEL_OR_BATTERY_LEVEL', 'IMMOBILIZE', 'DEVICE_HEALTH'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'AE', 'US', 'GB', 'EU'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },

  // =========================================================================
  // ACCOUNTING & ERP
  // =========================================================================
  {
    providerId: 'zoho_books',
    category: IntegrationCategory.ACCOUNTING,
    name: 'Zoho Books',
    tagline: 'Automated GST-compliant e-invoicing and vendor ledger sync',
    description: 'Synchronizes rental booking invoices, credit notes, and vendor weekly payout statements directly into Zoho Books.',
    icon: 'receipt',
    websiteUrl: 'https://zoho.com/books',
    documentation: {
      overview: 'Direct OAuth2 ledger synchronization with Zoho Books.',
      docsUrl: 'https://www.zoho.com/books/api/v3',
      setupGuide: 'Register an OAuth Client in Zoho Developer Console and generate refresh token.',
    },
    version: '3.0.0',
    author: 'Zoho Corporation',
    tags: ['accounting', 'gst', 'e-invoicing', 'ledger'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'organizationId', label: 'Organization ID', type: 'string', required: true, isSecret: false, description: 'Zoho Books Organization ID' },
      { key: 'clientId', label: 'Client ID', type: 'string', required: true, isSecret: false, description: 'Zoho OAuth Client ID' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, isSecret: true, description: 'Zoho OAuth Client Secret' },
      { key: 'refreshToken', label: 'Refresh Token', type: 'password', required: true, isSecret: true, description: 'Permanent Refresh Token' },
    ],
    supportedCapabilities: ['SYNC_INVOICE', 'SYNC_CREDIT_NOTE', 'SYNC_PAYOUT', 'RECONCILE_ACCOUNTS'],
    supportedCurrencies: ['INR', 'USD', 'AED'],
    supportedCountries: ['IN', 'AE', 'US'],
    platformAvailability: true,
    tenantTierAvailability: ['PRO', 'ENTERPRISE'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },

  // =========================================================================
  // AI & INTELLIGENCE
  // =========================================================================
  {
    providerId: 'gemini',
    category: IntegrationCategory.AI,
    name: 'Google Gemini AI',
    tagline: 'Multimodal AI intelligence for damage assessment, fraud, and customer care',
    description: 'Inspects return photos for scratch/dent severity, parses handwritten licences, and answers support inquiries.',
    icon: 'psychology',
    websiteUrl: 'https://ai.google.dev',
    documentation: {
      overview: 'Multimodal intelligence powered by Gemini 1.5 Flash and Pro models.',
      docsUrl: 'https://ai.google.dev/docs',
      setupGuide: 'Generate an API key in Google AI Studio.',
    },
    version: '1.5.0',
    author: 'Google LLC',
    tags: ['ai', 'damage-detection', 'multimodal', 'gemini'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'Gemini API Key', type: 'password', required: true, isSecret: true, description: 'Google AI Studio API Key' },
    ],
    supportedCapabilities: ['IMAGE_ANALYSIS', 'TEXT_GENERATION', 'FRAUD_CLASSIFICATION'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },

  // =========================================================================
  // SEARCH & DISCOVERY
  // =========================================================================
  {
    providerId: 'meilisearch',
    category: IntegrationCategory.SEARCH,
    name: 'Meilisearch',
    tagline: 'Blazing fast, typo-tolerant vehicle and location search engine',
    description: 'Power sub-50ms search for customer vehicle discovery, hub lookups, and faceted pricing filters.',
    icon: 'search',
    websiteUrl: 'https://meilisearch.com',
    documentation: {
      overview: 'Open-source instant search engine.',
      docsUrl: 'https://docs.meilisearch.com',
      setupGuide: 'Configure Meilisearch host URL and Master/API key.',
    },
    version: '1.8.0',
    author: 'Meilisearch Inc.',
    tags: ['search', 'typo-tolerance', 'faceting'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'host', label: 'Host URL', type: 'url', required: true, isSecret: false, description: 'Meilisearch instance URL (https://search.drivego.in)' },
      { key: 'apiKey', label: 'Master / Search API Key', type: 'password', required: true, isSecret: true, description: 'API Key with index permissions' },
    ],
    supportedCapabilities: ['FULLTEXT_SEARCH', 'FACETED_FILTERING', 'GEO_SEARCH'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },

  // =========================================================================
  // ANALYTICS & MARKETPLACE INTELLIGENCE
  // =========================================================================
  {
    providerId: 'posthog',
    category: IntegrationCategory.ANALYTICS,
    name: 'PostHog',
    tagline: 'Product analytics, event tracking, and customer conversion funnels',
    description: 'Tracks customer checkout conversion, search drops, vendor fleet utilization, and referral attribution.',
    icon: 'analytics',
    websiteUrl: 'https://posthog.com',
    documentation: {
      overview: 'Complete event analytics & funnel reporting.',
      docsUrl: 'https://posthog.com/docs',
      setupGuide: 'Enter Project API Key and Host URL from PostHog settings.',
    },
    version: '1.130.0',
    author: 'PostHog Inc.',
    tags: ['analytics', 'funnels', 'conversion', 'events'],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    defaultEnvironment: ProviderEnvironment.SANDBOX,
    credentialSchema: [
      { key: 'apiKey', label: 'Project API Key', type: 'string', required: true, isSecret: false, description: 'PostHog Project API Key (phc_...)' },
      { key: 'host', label: 'Host URL', type: 'url', required: false, isSecret: false, description: 'Host (default https://us.i.posthog.com)' },
    ],
    supportedCapabilities: ['EVENT_TRACKING', 'USER_IDENTIFICATION', 'FUNNEL_ANALYSIS'],
    supportedCurrencies: [],
    supportedCountries: ['IN', 'US', 'GB', 'AE', 'SG'],
    platformAvailability: true,
    tenantTierAvailability: ['ALL'],
    activationState: ProviderActivationState.ACTIVE,
    priority: 100,
  },
  ...ENTERPRISE_EXPANDED_PROVIDERS,
];
