import { IntegrationCategory } from '../registry/provider.types';
import { ProviderEnvironment } from '../catalog/provider-catalog.types';
import { ProviderPackManifest } from './provider-pack.types';

export const BUILTIN_PROVIDER_PACKS: ProviderPackManifest[] = [
  // 1. Mapbox
  {
    id: 'mapbox',
    name: 'mapbox',
    displayName: 'Mapbox Geospatial & Navigation',
    category: IntegrationCategory.MAPS,
    version: {
      apiVersion: 'v5',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-15',
    },
    capabilities: [
      { capability: 'GEOCODE', category: IntegrationCategory.MAPS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Forward geocoding via Mapbox Geocoding v5', expectedLatencyMs: 95, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'REVERSE_GEOCODE', category: IntegrationCategory.MAPS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Reverse geocoding coordinates to street address', expectedLatencyMs: 90, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'ROUTE', category: IntegrationCategory.MAPS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Turn-by-turn driving directions with traffic', expectedLatencyMs: 160, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'DISTANCE_MATRIX', category: IntegrationCategory.MAPS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Travel distance and duration matrix computation', expectedLatencyMs: 180, slaUptimePercent: 99.9, idempotent: true },
    ],
    credentialSchema: [
      { key: 'MAPBOX_ACCESS_TOKEN', label: 'Mapbox Access Token', type: 'password', required: true, isSecret: true, description: 'pk.ey... or sk.ey... access token from Mapbox Account' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['GLOBAL', 'IN', 'US', 'EU'],
    supportedCurrencies: ['USD', 'INR', 'EUR'],
    rateLimits: { rps: 100, rpm: 3000, burstCapacity: 150, concurrencyLimit: 40 },
    costModel: { providerId: 'mapbox', category: IntegrationCategory.MAPS, fixedFee: 0, percentageFee: 0, perRequestCost: 0.005, perMessageCost: 0, currency: 'USD', regionSpecificCosts: {} },
    webhookConfig: { supported: false, secretRequired: false, supportsReplayProtection: false },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 4000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 3, backoffFactor: 1.5, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', 'ECONNRESET', '429', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://docs.mapbox.com/api/navigation/directions/',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['maps', 'routing', 'navigation', 'geocoding'],
  },

  // 2. Traccar Telematics
  {
    id: 'traccar',
    name: 'traccar',
    displayName: 'Traccar Open GPS Telematics Hub',
    category: IntegrationCategory.VEHICLE_TRACKING,
    version: {
      apiVersion: 'v5.10',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-02-01',
    },
    capabilities: [
      { capability: 'GPS_POSITION', category: IntegrationCategory.VEHICLE_TRACKING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Real-time vehicle position and coordinates', expectedLatencyMs: 70, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'LIVE_LOCATION', category: IntegrationCategory.VEHICLE_TRACKING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Live tracking stream for active car rentals', expectedLatencyMs: 65, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'TRIP_TRACKING', category: IntegrationCategory.VEHICLE_TRACKING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Trip trajectory and speed profiling', expectedLatencyMs: 110, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'IMMOBILIZE', category: IntegrationCategory.VEHICLE_TRACKING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Remote starter relay engine cutoff command', expectedLatencyMs: 250, slaUptimePercent: 99.95, idempotent: false },
      { capability: 'RESTORE_ENGINE', category: IntegrationCategory.VEHICLE_TRACKING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Restore vehicle ignition relay', expectedLatencyMs: 250, slaUptimePercent: 99.95, idempotent: false },
      { capability: 'GEOFENCE_CHECK', category: IntegrationCategory.VEHICLE_TRACKING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Boundary entry/exit polygon validation', expectedLatencyMs: 50, slaUptimePercent: 99.99, idempotent: true },
    ],
    credentialSchema: [
      { key: 'TRACCAR_SERVER_URL', label: 'Traccar Server URL', type: 'url', required: true, isSecret: false, description: 'Base endpoint URL of Traccar instance' },
      { key: 'TRACCAR_API_TOKEN', label: 'Traccar User API Token', type: 'password', required: true, isSecret: true, description: 'Admin or tenant user authorization token' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['GLOBAL', 'IN', 'US', 'EU'],
    supportedCurrencies: ['USD', 'INR', 'EUR'],
    rateLimits: { rps: 150, rpm: 5000, burstCapacity: 200, concurrencyLimit: 50 },
    costModel: { providerId: 'traccar', category: IntegrationCategory.VEHICLE_TRACKING, fixedFee: 0, percentageFee: 0, perRequestCost: 0.001, perMessageCost: 0, currency: 'USD', regionSpecificCosts: {} },
    webhookConfig: { supported: true, signatureHeader: 'X-Traccar-Signature', algorithm: 'HMAC-SHA256', secretRequired: true, supportsReplayProtection: true },
    healthCheckConfig: { intervalSeconds: 30, timeoutMs: 3000, degradedThresholdFailures: 2 },
    retryPolicy: { maxRetries: 2, backoffFactor: 2, initialIntervalMs: 300, retryableErrorCodes: ['ETIMEDOUT', '502', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://www.traccar.org/api-reference/',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['telematics', 'gps', 'fleet', 'immobilization', 'iot'],
  },

  // 3. HyperVerge KYC
  {
    id: 'hyperverge',
    name: 'hyperverge',
    displayName: 'HyperVerge AI Identity & Fraud Stack',
    category: IntegrationCategory.IDENTITY_VERIFICATION,
    version: {
      apiVersion: 'v3.2',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-20',
    },
    capabilities: [
      { capability: 'PAN_VERIFICATION', category: IntegrationCategory.IDENTITY_VERIFICATION, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'NSDL PAN verification with name match score', expectedLatencyMs: 450, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'AADHAAR_VERIFICATION', category: IntegrationCategory.IDENTITY_VERIFICATION, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'UIDAI OTP-based Aadhaar KYC verification', expectedLatencyMs: 850, slaUptimePercent: 99.8, idempotent: false },
      { capability: 'DRIVING_LICENCE_VERIFICATION', category: IntegrationCategory.IDENTITY_VERIFICATION, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'MoRTH Sarathi driving license status and classes', expectedLatencyMs: 650, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'VEHICLE_RC_VERIFICATION', category: IntegrationCategory.IDENTITY_VERIFICATION, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Vahan vehicle registration cert & fitness validation', expectedLatencyMs: 600, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'FACE_MATCH', category: IntegrationCategory.IDENTITY_VERIFICATION, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Biometric face match between selfie and government ID', expectedLatencyMs: 500, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'LIVENESS', category: IntegrationCategory.IDENTITY_VERIFICATION, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Anti-spoofing video/photo liveness detection', expectedLatencyMs: 700, slaUptimePercent: 99.9, idempotent: true },
    ],
    credentialSchema: [
      { key: 'HYPERVERGE_APP_ID', label: 'HyperVerge App ID', type: 'string', required: true, isSecret: false, description: 'Application identifier' },
      { key: 'HYPERVERGE_APP_KEY', label: 'HyperVerge App Key', type: 'password', required: true, isSecret: true, description: 'Application secret key' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['IN', 'GLOBAL'],
    supportedCurrencies: ['INR', 'USD'],
    rateLimits: { rps: 30, rpm: 1000, burstCapacity: 50, concurrencyLimit: 20 },
    costModel: { providerId: 'hyperverge', category: IntegrationCategory.IDENTITY_VERIFICATION, fixedFee: 0, percentageFee: 0, perRequestCost: 0.08, perMessageCost: 0, currency: 'USD', regionSpecificCosts: { IN: 4.5 } },
    webhookConfig: { supported: true, signatureHeader: 'X-HyperVerge-Signature', secretRequired: true, supportsReplayProtection: true },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 5000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 2, backoffFactor: 2, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://docs.hyperverge.co/',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['kyc', 'identity', 'aadhaar', 'pan', 'sarathi', 'vahan', 'liveness'],
  },

  // 4. Zoho Books Accounting
  {
    id: 'zoho_books',
    name: 'zoho_books',
    displayName: 'Zoho Books ERP & Invoicing',
    category: IntegrationCategory.ACCOUNTING,
    version: {
      apiVersion: 'v3',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-02-10',
    },
    capabilities: [
      { capability: 'CREATE_INVOICE', category: IntegrationCategory.ACCOUNTING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Generate GST-compliant tax invoices for rental bookings', expectedLatencyMs: 380, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'SYNC_CUSTOMER', category: IntegrationCategory.ACCOUNTING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Synchronize customer contact and GSTIN data', expectedLatencyMs: 250, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'SYNC_PAYMENT', category: IntegrationCategory.ACCOUNTING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Record payment ledger entries and reconciliation', expectedLatencyMs: 300, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'TAX_CALCULATION', category: IntegrationCategory.ACCOUNTING, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Compute CGST/SGST or IGST depending on inter-state rules', expectedLatencyMs: 40, slaUptimePercent: 99.99, idempotent: true },
    ],
    credentialSchema: [
      { key: 'ZOHO_BOOKS_ORG_ID', label: 'Zoho Books Organization ID', type: 'string', required: true, isSecret: false, description: 'Primary business organization ID' },
      { key: 'ZOHO_BOOKS_AUTH_TOKEN', label: 'Zoho Books OAuth2 Token', type: 'password', required: true, isSecret: true, description: 'OAuth2 access token with ZohoBooks.fullaccess.all scope' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['IN', 'GLOBAL'],
    supportedCurrencies: ['INR', 'USD', 'EUR', 'GBP'],
    rateLimits: { rps: 20, rpm: 600, burstCapacity: 35, concurrencyLimit: 15 },
    costModel: { providerId: 'zoho_books', category: IntegrationCategory.ACCOUNTING, fixedFee: 0, percentageFee: 0, perRequestCost: 0, perMessageCost: 0, currency: 'INR', regionSpecificCosts: {} },
    webhookConfig: { supported: true, signatureHeader: 'X-Zoho-Signature', secretRequired: true, supportsReplayProtection: true },
    healthCheckConfig: { intervalSeconds: 120, timeoutMs: 6000, degradedThresholdFailures: 2 },
    retryPolicy: { maxRetries: 3, backoffFactor: 2, initialIntervalMs: 1000, retryableErrorCodes: ['ETIMEDOUT', '429', '500', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://www.zoho.com/books/api/v3/',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['accounting', 'gst', 'invoicing', 'erp', 'reconciliation'],
  },

  // 5. Google Gemini AI
  {
    id: 'gemini',
    name: 'gemini',
    displayName: 'Google Gemini 1.5/2.0 Multimodal AI',
    category: IntegrationCategory.AI,
    version: {
      apiVersion: 'v1beta',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-05',
    },
    capabilities: [
      { capability: 'CHAT', category: IntegrationCategory.AI, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Multi-turn conversational customer concierge', expectedLatencyMs: 600, slaUptimePercent: 99.95, idempotent: false },
      { capability: 'TEXT_GENERATION', category: IntegrationCategory.AI, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Automated description & marketing copy generation', expectedLatencyMs: 400, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'SUMMARIZATION', category: IntegrationCategory.AI, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Vehicle condition & handover incident report summary', expectedLatencyMs: 500, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'CLASSIFICATION', category: IntegrationCategory.AI, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Customer dispute and message intent classification', expectedLatencyMs: 300, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'EXTRACTION', category: IntegrationCategory.AI, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Zero-shot entity extraction into JSON schemas', expectedLatencyMs: 450, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'EMBEDDINGS', category: IntegrationCategory.AI, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Semantic search vectors via text-embedding-004', expectedLatencyMs: 150, slaUptimePercent: 99.99, idempotent: true },
    ],
    credentialSchema: [
      { key: 'GEMINI_API_KEY', label: 'Google AI Studio / Vertex Key', type: 'password', required: true, isSecret: true, description: 'AI Studio API key or Vertex service credentials' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['GLOBAL', 'IN', 'US', 'EU'],
    supportedCurrencies: ['USD', 'INR'],
    rateLimits: { rps: 60, rpm: 2000, burstCapacity: 100, concurrencyLimit: 30 },
    costModel: { providerId: 'gemini', category: IntegrationCategory.AI, fixedFee: 0, percentageFee: 0, perRequestCost: 0.0003, perMessageCost: 0, currency: 'USD', regionSpecificCosts: {} },
    webhookConfig: { supported: false, secretRequired: false, supportsReplayProtection: false },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 5000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 2, backoffFactor: 1.5, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', '429', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://ai.google.dev/docs',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['ai', 'llm', 'gemini', 'nlp', 'summarization', 'embeddings'],
  },

  // 6. Meilisearch
  {
    id: 'meilisearch',
    name: 'meilisearch',
    displayName: 'Meilisearch Instant Search Engine',
    category: IntegrationCategory.SEARCH,
    version: {
      apiVersion: 'v1.6',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-10',
    },
    capabilities: [
      { capability: 'INDEX_DOCUMENT', category: IntegrationCategory.SEARCH, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Index rental fleet vehicles and hubs', expectedLatencyMs: 30, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'SEARCH_QUERY', category: IntegrationCategory.SEARCH, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Sub-15ms typo-tolerant fleet vehicle search', expectedLatencyMs: 15, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'AUTOCOMPLETE', category: IntegrationCategory.SEARCH, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Real-time search-as-you-type suggestions', expectedLatencyMs: 10, slaUptimePercent: 99.99, idempotent: true },
    ],
    credentialSchema: [
      { key: 'MEILISEARCH_HOST', label: 'Meilisearch Endpoint', type: 'url', required: true, isSecret: false, description: 'Host endpoint URL (e.g. http://localhost:7700)' },
      { key: 'MEILISEARCH_API_KEY', label: 'Master / Search API Key', type: 'password', required: true, isSecret: true, description: 'API Key with search & documents permissions' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['GLOBAL'],
    supportedCurrencies: ['*'],
    rateLimits: { rps: 500, rpm: 25000, burstCapacity: 1000, concurrencyLimit: 100 },
    costModel: { providerId: 'meilisearch', category: IntegrationCategory.SEARCH, fixedFee: 0, percentageFee: 0, perRequestCost: 0, perMessageCost: 0, currency: 'USD', regionSpecificCosts: {} },
    webhookConfig: { supported: false, secretRequired: false, supportsReplayProtection: false },
    healthCheckConfig: { intervalSeconds: 30, timeoutMs: 2000, degradedThresholdFailures: 2 },
    retryPolicy: { maxRetries: 2, backoffFactor: 1.5, initialIntervalMs: 200, retryableErrorCodes: ['ECONNREFUSED', 'ETIMEDOUT'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://www.meilisearch.com/docs',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['search', 'full-text', 'faceted-search', 'autocomplete'],
  },

  // 7. PostHog Analytics
  {
    id: 'posthog',
    name: 'posthog',
    displayName: 'PostHog Product Telemetry & Analytics',
    category: IntegrationCategory.ANALYTICS,
    version: {
      apiVersion: 'v1',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-02-05',
    },
    capabilities: [
      { capability: 'TRACK_EVENT', category: IntegrationCategory.ANALYTICS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Server-side booking & funnel conversion events', expectedLatencyMs: 25, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'IDENTIFY_USER', category: IntegrationCategory.ANALYTICS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Link user ID with rental persona and preferences', expectedLatencyMs: 30, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'BATCH_EVENTS', category: IntegrationCategory.ANALYTICS, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'High-throughput async event batch ingestion', expectedLatencyMs: 40, slaUptimePercent: 99.99, idempotent: true },
    ],
    credentialSchema: [
      { key: 'POSTHOG_API_KEY', label: 'PostHog Project API Key', type: 'password', required: true, isSecret: true, description: 'Project API key from PostHog Project Settings' },
      { key: 'POSTHOG_HOST', label: 'PostHog Host URL', type: 'url', required: false, isSecret: false, description: 'Cloud or self-hosted PostHog instance URL' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['GLOBAL'],
    supportedCurrencies: ['*'],
    rateLimits: { rps: 300, rpm: 15000, burstCapacity: 500, concurrencyLimit: 80 },
    costModel: { providerId: 'posthog', category: IntegrationCategory.ANALYTICS, fixedFee: 0, percentageFee: 0, perRequestCost: 0.0001, perMessageCost: 0, currency: 'USD', regionSpecificCosts: {} },
    webhookConfig: { supported: false, secretRequired: false, supportsReplayProtection: false },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 3000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 2, backoffFactor: 2, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://posthog.com/docs',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['analytics', 'product-telemetry', 'funnel', 'conversion'],
  },

  // 8. Razorpay Payments
  {
    id: 'razorpay',
    name: 'razorpay',
    displayName: 'Razorpay Payments & Escrow Gateway',
    category: IntegrationCategory.PAYMENT,
    version: {
      apiVersion: 'v1',
      adapterVersion: '2.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-01',
    },
    capabilities: [
      { capability: 'CREATE_ORDER', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Creates transactional payment orders', expectedLatencyMs: 180, slaUptimePercent: 99.95, idempotent: true },
      { capability: 'VERIFY_PAYMENT', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'HMAC signature verification for payment captures', expectedLatencyMs: 10, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'CAPTURE', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Authorizes and captures funds from payment hold', expectedLatencyMs: 250, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'REFUND', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Initiates immediate or normal refunds to customer', expectedLatencyMs: 350, slaUptimePercent: 99.9, idempotent: true, refundable: true },
      { capability: 'UPI', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Native UPI collect & intent flows', expectedLatencyMs: 150, slaUptimePercent: 99.95, idempotent: true },
    ],
    credentialSchema: [
      { key: 'RAZORPAY_KEY_ID', label: 'Key ID', type: 'string', required: true, isSecret: false, description: 'Razorpay public Key ID' },
      { key: 'RAZORPAY_KEY_SECRET', label: 'Key Secret', type: 'password', required: true, isSecret: true, description: 'Razorpay secret key' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['IN'],
    supportedCurrencies: ['INR', 'USD', 'EUR'],
    rateLimits: { rps: 100, rpm: 4000, burstCapacity: 150, concurrencyLimit: 40 },
    costModel: { providerId: 'razorpay', category: IntegrationCategory.PAYMENT, fixedFee: 0, percentageFee: 2.0, perRequestCost: 0, perMessageCost: 0, currency: 'INR', regionSpecificCosts: {} },
    webhookConfig: { supported: true, signatureHeader: 'X-Razorpay-Signature', algorithm: 'HMAC-SHA256', secretRequired: true, supportsReplayProtection: true },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 5000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 3, backoffFactor: 2, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://razorpay.com/docs/',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['payments', 'upi', 'cards', 'refunds', 'india'],
  },

  // 9. Cashfree Payments
  {
    id: 'cashfree',
    name: 'cashfree',
    displayName: 'Cashfree Payments & Payouts',
    category: IntegrationCategory.PAYMENT,
    version: {
      apiVersion: '2023-08-01',
      adapterVersion: '1.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-10',
    },
    capabilities: [
      { capability: 'CREATE_ORDER', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Creates Cashfree payment sessions', expectedLatencyMs: 190, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'VERIFY_PAYMENT', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Verifies payment order status', expectedLatencyMs: 150, slaUptimePercent: 99.9, idempotent: true },
      { capability: 'REFUND', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Direct gateway refund', expectedLatencyMs: 320, slaUptimePercent: 99.9, idempotent: true, refundable: true },
      { capability: 'UPI', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'UPI dynamic QR and intent', expectedLatencyMs: 140, slaUptimePercent: 99.9, idempotent: true },
    ],
    credentialSchema: [
      { key: 'CASHFREE_APP_ID', label: 'App ID', type: 'string', required: true, isSecret: false, description: 'Cashfree merchant App ID' },
      { key: 'CASHFREE_SECRET_KEY', label: 'Secret Key', type: 'password', required: true, isSecret: true, description: 'Cashfree secret key' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['IN'],
    supportedCurrencies: ['INR'],
    rateLimits: { rps: 80, rpm: 3000, burstCapacity: 120, concurrencyLimit: 30 },
    costModel: { providerId: 'cashfree', category: IntegrationCategory.PAYMENT, fixedFee: 0, percentageFee: 1.9, perRequestCost: 0, perMessageCost: 0, currency: 'INR', regionSpecificCosts: {} },
    webhookConfig: { supported: true, signatureHeader: 'x-webhook-signature', algorithm: 'HMAC-SHA256', secretRequired: true, supportsReplayProtection: true },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 5000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 3, backoffFactor: 2, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://docs.cashfree.com/',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['payments', 'upi', 'payouts', 'india'],
  },

  // 10. Stripe Payments
  {
    id: 'stripe',
    name: 'stripe',
    displayName: 'Stripe Global Financial Infrastructure',
    category: IntegrationCategory.PAYMENT,
    version: {
      apiVersion: '2023-10-16',
      adapterVersion: '2.0.0',
      credentialSchemaVersion: '1.0',
      releasedAt: '2026-01-01',
    },
    capabilities: [
      { capability: 'CREATE_ORDER', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Creates PaymentIntents with 3D Secure 2', expectedLatencyMs: 220, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'CAPTURE', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Captures pre-authorized security holds', expectedLatencyMs: 200, slaUptimePercent: 99.99, idempotent: true },
      { capability: 'REFUND', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Refunds card charges with idempotency', expectedLatencyMs: 250, slaUptimePercent: 99.99, idempotent: true, refundable: true },
      { capability: 'CARD', category: IntegrationCategory.PAYMENT, version: '1.0', supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE], description: 'Global Visa, Mastercard, Amex, Apple Pay, Google Pay', expectedLatencyMs: 180, slaUptimePercent: 99.99, idempotent: true },
    ],
    credentialSchema: [
      { key: 'STRIPE_SECRET_KEY', label: 'Secret API Key', type: 'password', required: true, isSecret: true, description: 'sk_live or sk_test key' },
      { key: 'STRIPE_PUBLISHABLE_KEY', label: 'Publishable Key', type: 'string', required: true, isSecret: false, description: 'pk_live or pk_test key' },
    ],
    supportedEnvironments: [ProviderEnvironment.SANDBOX, ProviderEnvironment.LIVE],
    supportedRegions: ['GLOBAL', 'US', 'EU', 'GB', 'IN', 'SG', 'AU'],
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'INR', 'AUD', 'SGD', 'CAD'],
    rateLimits: { rps: 100, rpm: 4000, burstCapacity: 150, concurrencyLimit: 50 },
    costModel: { providerId: 'stripe', category: IntegrationCategory.PAYMENT, fixedFee: 0.30, percentageFee: 2.9, perRequestCost: 0, perMessageCost: 0, currency: 'USD', regionSpecificCosts: {} },
    webhookConfig: { supported: true, signatureHeader: 'Stripe-Signature', algorithm: 'HMAC-SHA256', secretRequired: true, supportsReplayProtection: true },
    healthCheckConfig: { intervalSeconds: 60, timeoutMs: 4000, degradedThresholdFailures: 3 },
    retryPolicy: { maxRetries: 3, backoffFactor: 1.5, initialIntervalMs: 500, retryableErrorCodes: ['ETIMEDOUT', '429', '503'] },
    fallbackEligibility: { eligibleAsPrimary: true, eligibleAsSecondaryFallback: true },
    documentationUrl: 'https://stripe.com/docs/api',
    implementationStatus: 'REAL_ADAPTER',
    tags: ['payments', 'cards', 'global', 'apple-pay', 'google-pay'],
  },
];
