import 'package:models/models.dart';

class MockData {
  static final List<UserModel> customers = [
    const UserModel(
      id: 'c1',
      name: 'Rahul Sharma',
      phone: '9876543210',
      email: 'rahul.sharma@example.com',
      role: 'customer',
    ),
    const UserModel(
      id: 'c2',
      name: 'Priya Patel',
      phone: '9876543211',
      email: 'priya.patel@example.com',
      role: 'customer',
    ),
    const UserModel(
      id: 'c3',
      name: 'Vikram Singh',
      phone: '9876543212',
      email: 'vikram.singh@example.com',
      role: 'customer',
    ),
    const UserModel(
      id: 'c4',
      name: 'Ananya Iyer',
      phone: '9876543213',
      email: 'ananya.iyer@example.com',
      role: 'customer',
    ),
    const UserModel(
      id: 'c5',
      name: 'Rohan Mehta',
      phone: '9876543214',
      email: 'rohan.mehta@example.com',
      role: 'customer',
    ),
  ];

  static final List<VendorModel> vendors = [
    // Mumbai (v1 - v4)
    const VendorModel(
      id: 'v1',
      businessName: 'Mumbai Car Rentals',
      ownerName: 'Amit Shah',
      city: 'Mumbai',
      phone: '9876543001',
      gstNumber: '27AAAAA1111A1Z1',
      bankDetails: 'HDFC Bank - 50100234567890',
      verificationStatus: 'verified',
      rating: 4.5,
      totalTrips: 120,
    ),
    const VendorModel(
      id: 'v2',
      businessName: 'Apex Drive Mumbai',
      ownerName: 'Rajesh Kulkarni',
      city: 'Mumbai',
      gstNumber: '27BBBBB2222B2Z2',
      bankDetails: 'ICICI Bank - 000401234567',
      verificationStatus: 'verified',
      rating: 4.2,
      totalTrips: 85,
    ),
    const VendorModel(
      id: 'v3',
      businessName: 'Siddhivinayak Cabs',
      ownerName: 'Sachin Patil',
      city: 'Mumbai',
      gstNumber: '27CCCCC3333C3Z3',
      bankDetails: 'State Bank of India - 30012345678',
      verificationStatus: 'verified',
      rating: 4.7,
      totalTrips: 150,
    ),
    const VendorModel(
      id: 'v4',
      businessName: 'Gateway Self Drive',
      ownerName: 'Milind Deora',
      city: 'Mumbai',
      phone: '9876543004',
      gstNumber: null,
      bankDetails: null,
      verificationStatus: 'pending',
      rating: 0.0,
      totalTrips: 0,
    ),

    // Delhi (v5 - v8)
    const VendorModel(
      id: 'v5',
      businessName: 'Delhi Travel Solutions',
      ownerName: 'Sanjay Gupta',
      city: 'Delhi',
      gstNumber: '07DDDDD4444D4Z4',
      bankDetails: 'Axis Bank - 912010023456789',
      verificationStatus: 'verified',
      rating: 4.3,
      totalTrips: 95,
    ),
    const VendorModel(
      id: 'v6',
      businessName: 'Capital Cruiser',
      ownerName: 'Harpreet Singh',
      city: 'Delhi',
      gstNumber: '07EEEEE5555E5Z5',
      bankDetails: 'Punjab National Bank - 0123000100234567',
      verificationStatus: 'verified',
      rating: 4.1,
      totalTrips: 70,
    ),
    const VendorModel(
      id: 'v7',
      businessName: 'NCR Wheels',
      ownerName: 'Deepak Kumar',
      city: 'Delhi',
      gstNumber: '07FFFFF6666F6Z6',
      bankDetails: 'HDFC Bank - 50100987654321',
      verificationStatus: 'verified',
      rating: 4.6,
      totalTrips: 110,
    ),
    const VendorModel(
      id: 'v8',
      businessName: 'Taj Express Rentals',
      ownerName: 'Rahul Yadav',
      city: 'Delhi',
      gstNumber: null,
      bankDetails: null,
      verificationStatus: 'pending',
      rating: 0.0,
      totalTrips: 0,
    ),

    // Bangalore (v9 - v12)
    const VendorModel(
      id: 'v9',
      businessName: 'Silicon Valley Drives',
      ownerName: 'Karthik Raja',
      city: 'Bangalore',
      gstNumber: '29GGGGG7777G7Z7',
      bankDetails: 'Kotak Bank - 1234567890',
      verificationStatus: 'verified',
      rating: 4.8,
      totalTrips: 135,
    ),
    const VendorModel(
      id: 'v10',
      businessName: 'Nandi Hills Wheels',
      ownerName: 'Srinivas Murthy',
      city: 'Bangalore',
      gstNumber: '29HHHHH8888H8Z8',
      bankDetails: 'State Bank of India - 31098765432',
      verificationStatus: 'verified',
      rating: 4.4,
      totalTrips: 90,
    ),
    const VendorModel(
      id: 'v11',
      businessName: 'Garden City Cruisers',
      ownerName: 'Vijay Mallya',
      city: 'Bangalore',
      gstNumber: '29IIIII9999I9Z9',
      bankDetails: 'ICICI Bank - 000409876543',
      verificationStatus: 'verified',
      rating: 3.9,
      totalTrips: 60,
    ),
    const VendorModel(
      id: 'v12',
      businessName: 'Bengaluru Auto Hub',
      ownerName: 'Anand Gowda',
      city: 'Bangalore',
      gstNumber: null,
      bankDetails: null,
      verificationStatus: 'pending',
      rating: 0.0,
      totalTrips: 0,
    ),

    // Chennai (v13 - v16)
    const VendorModel(
      id: 'v13',
      businessName: 'Coromandel Rent-a-Car',
      ownerName: 'Srinivasan K.',
      city: 'Chennai',
      gstNumber: '33JJJJJ0000J0Z0',
      bankDetails: 'Indian Bank - 6012345678',
      verificationStatus: 'verified',
      rating: 4.4,
      totalTrips: 80,
    ),
    const VendorModel(
      id: 'v14',
      businessName: 'Marina Drive Wheels',
      ownerName: 'Subramanian Ram',
      city: 'Chennai',
      gstNumber: '33KKKKK1111K1Z1',
      bankDetails: 'HDFC Bank - 50100111222333',
      verificationStatus: 'verified',
      rating: 4.2,
      totalTrips: 75,
    ),
    const VendorModel(
      id: 'v15',
      businessName: 'Madras Motors',
      ownerName: 'Vijay Kumar',
      city: 'Chennai',
      gstNumber: '33LLLLL2222L2Z2',
      bankDetails: 'Axis Bank - 915010044445555',
      verificationStatus: 'verified',
      rating: 4.5,
      totalTrips: 105,
    ),
    const VendorModel(
      id: 'v16',
      businessName: 'Chennai Premium Rides',
      ownerName: 'Ramesh Chand',
      city: 'Chennai',
      gstNumber: '33MMMMM3333M3Z3',
      bankDetails: 'Canara Bank - 100923456789',
      verificationStatus: 'verified',
      rating: 4.7,
      totalTrips: 115,
    ),

    // Hyderabad (v17 - v20)
    const VendorModel(
      id: 'v17',
      businessName: 'Nizam Chauffeurs',
      ownerName: 'Mohammed Ali',
      city: 'Hyderabad',
      gstNumber: '36NNNNN4444N4Z4',
      bankDetails: 'HDFC Bank - 50100333444555',
      verificationStatus: 'verified',
      rating: 4.6,
      totalTrips: 112,
    ),
    const VendorModel(
      id: 'v18',
      businessName: 'Charminar Cabs',
      ownerName: 'K. Chandrashekar',
      city: 'Hyderabad',
      gstNumber: '36OOOOO5555O5Z5',
      bankDetails: 'State Bank of India - 32011122233',
      verificationStatus: 'verified',
      rating: 4.3,
      totalTrips: 88,
    ),
    const VendorModel(
      id: 'v19',
      businessName: 'Cyberabad Cars',
      ownerName: 'Ravi Teja',
      city: 'Hyderabad',
      gstNumber: '36PPPPP6666P6Z6',
      bankDetails: 'ICICI Bank - 000405556667',
      verificationStatus: 'verified',
      rating: 4.5,
      totalTrips: 100,
    ),
    const VendorModel(
      id: 'v20',
      businessName: 'Biryani Travel Hub',
      ownerName: 'Suresh Naidu',
      city: 'Hyderabad',
      gstNumber: '36QQQQQ7777Q7Z7',
      bankDetails: 'Union Bank of India - 520123456789',
      verificationStatus: 'verified',
      rating: 4.0,
      totalTrips: 50,
    ),
  ];

  static final List<CarModel> cars = [
    // Mumbai (v1 - v4)
    // v1
    const CarModel(
      id: 'car1',
      vendorId: 'v1',
      make: 'Maruti Suzuki',
      model: 'Swift',
      year: 2022,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 14.0,
      pricePerDay: 1700.0,
      pricePerHour: 140.0,
      rating: 4.5,
    ),
    const CarModel(
      id: 'car2',
      vendorId: 'v1',
      make: 'Mahindra',
      model: 'XUV700',
      year: 2022,
      type: 'SUV',
      fuelType: 'Diesel',
      seating: 7,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 21.0,
      pricePerDay: 4000.0,
      pricePerHour: 350.0,
      rating: 4.7,
    ),
    // v2
    const CarModel(
      id: 'car3',
      vendorId: 'v2',
      make: 'Honda',
      model: 'City',
      year: 2021,
      type: 'Sedan',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 17.0,
      pricePerDay: 2300.0,
      pricePerHour: 210.0,
      rating: 4.3,
    ),
    const CarModel(
      id: 'car4',
      vendorId: 'v2',
      make: 'BMW',
      model: '3 Series',
      year: 2022,
      type: 'Luxury',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1555215695-3004980ad54e'],
      pricePerKm: 40.0,
      pricePerDay: 9000.0,
      pricePerHour: 950.0,
      rating: 4.8,
    ),
    // v3
    const CarModel(
      id: 'car5',
      vendorId: 'v3',
      make: 'Force',
      model: 'Traveller',
      year: 2021,
      type: 'Tempo Traveller',
      fuelType: 'Diesel',
      seating: 12,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 27.0,
      pricePerDay: 5600.0,
      pricePerHour: 500.0,
      rating: 4.6,
    ),
    const CarModel(
      id: 'car6',
      vendorId: 'v3',
      make: 'Tata',
      model: 'Winger',
      year: 2020,
      type: 'Mini Bus',
      fuelType: 'Diesel',
      seating: 15,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 34.0,
      pricePerDay: 8000.0,
      pricePerHour: 700.0,
      rating: 4.4,
    ),
    // v4
    const CarModel(
      id: 'car7',
      vendorId: 'v4',
      make: 'Hyundai',
      model: 'i20',
      year: 2022,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 14.0,
      pricePerDay: 1700.0,
      pricePerHour: 140.0,
      rating: 4.0,
    ),
    const CarModel(
      id: 'car8',
      vendorId: 'v4',
      make: 'Tata',
      model: 'Nexon',
      year: 2022,
      type: 'SUV',
      fuelType: 'Electric',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 21.0,
      pricePerDay: 4000.0,
      pricePerHour: 350.0,
      rating: 4.2,
    ),

    // Delhi (v5 - v8)
    // v5
    const CarModel(
      id: 'car9',
      vendorId: 'v5',
      make: 'Maruti Suzuki',
      model: 'WagonR',
      year: 2021,
      type: 'Hatchback',
      fuelType: 'CNG',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 13.0,
      pricePerDay: 1600.0,
      pricePerHour: 130.0,
      rating: 4.1,
    ),
    const CarModel(
      id: 'car10',
      vendorId: 'v5',
      make: 'Toyota',
      model: 'Innova Crysta',
      year: 2022,
      type: 'SUV',
      fuelType: 'Diesel',
      seating: 7,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 21.0,
      pricePerDay: 4000.0,
      pricePerHour: 350.0,
      rating: 4.6,
    ),
    // v6
    const CarModel(
      id: 'car11',
      vendorId: 'v6',
      make: 'Hyundai',
      model: 'Verna',
      year: 2022,
      type: 'Sedan',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 17.0,
      pricePerDay: 2300.0,
      pricePerHour: 210.0,
      rating: 4.3,
    ),
    const CarModel(
      id: 'car12',
      vendorId: 'v6',
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2021,
      type: 'Luxury',
      fuelType: 'Diesel',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1555215695-3004980ad54e'],
      pricePerKm: 40.0,
      pricePerDay: 9000.0,
      pricePerHour: 950.0,
      rating: 4.5,
    ),
    // v7
    const CarModel(
      id: 'car13',
      vendorId: 'v7',
      make: 'Force',
      model: 'Traveller 12S',
      year: 2022,
      type: 'Tempo Traveller',
      fuelType: 'Diesel',
      seating: 12,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 27.0,
      pricePerDay: 5600.0,
      pricePerHour: 500.0,
      rating: 4.7,
    ),
    const CarModel(
      id: 'car14',
      vendorId: 'v7',
      make: 'Mahindra',
      model: 'Cruzio',
      year: 2021,
      type: 'Mini Bus',
      fuelType: 'Diesel',
      seating: 19,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 34.0,
      pricePerDay: 8000.0,
      pricePerHour: 700.0,
      rating: 4.4,
    ),
    // v8
    const CarModel(
      id: 'car15',
      vendorId: 'v8',
      make: 'Tata',
      model: 'Altroz',
      year: 2022,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 14.0,
      pricePerDay: 1700.0,
      pricePerHour: 140.0,
      rating: 3.8,
    ),
    const CarModel(
      id: 'car16',
      vendorId: 'v8',
      make: 'Hyundai',
      model: 'Creta',
      year: 2022,
      type: 'SUV',
      fuelType: 'Diesel',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 21.0,
      pricePerDay: 4000.0,
      pricePerHour: 350.0,
      rating: 4.1,
    ),

    // Bangalore (v9 - v12)
    // v9
    const CarModel(
      id: 'car17',
      vendorId: 'v9',
      make: 'Tata',
      model: 'Tiago',
      year: 2021,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 12.0,
      pricePerDay: 1500.0,
      pricePerHour: 120.0,
      rating: 4.8,
    ),
    const CarModel(
      id: 'car18',
      vendorId: 'v9',
      make: 'Mahindra',
      model: 'Thar',
      year: 2022,
      type: 'SUV',
      fuelType: 'Diesel',
      seating: 4,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 18.0,
      pricePerDay: 3500.0,
      pricePerHour: 300.0,
      rating: 4.9,
    ),
    // v10
    const CarModel(
      id: 'car19',
      vendorId: 'v10',
      make: 'Skoda',
      model: 'Slavia',
      year: 2022,
      type: 'Sedan',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 15.0,
      pricePerDay: 2000.0,
      pricePerHour: 180.0,
      rating: 4.4,
    ),
    const CarModel(
      id: 'car20',
      vendorId: 'v10',
      make: 'Audi',
      model: 'A4',
      year: 2022,
      type: 'Luxury',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1555215695-3004980ad54e'],
      pricePerKm: 35.0,
      pricePerDay: 8000.0,
      pricePerHour: 800.0,
      rating: 4.6,
    ),
    // v11
    const CarModel(
      id: 'car21',
      vendorId: 'v11',
      make: 'Force',
      model: 'Traveller 17S',
      year: 2021,
      type: 'Tempo Traveller',
      fuelType: 'Diesel',
      seating: 17,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 24.0,
      pricePerDay: 5000.0,
      pricePerHour: 450.0,
      rating: 4.0,
    ),
    const CarModel(
      id: 'car22',
      vendorId: 'v11',
      make: 'Eicher',
      model: 'Starline',
      year: 2020,
      type: 'Mini Bus',
      fuelType: 'Diesel',
      seating: 21,
      isAC: false,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 30.0,
      pricePerDay: 7000.0,
      pricePerHour: 600.0,
      rating: 3.9,
    ),
    // v12
    const CarModel(
      id: 'car23',
      vendorId: 'v12',
      make: 'Renault',
      model: 'Kwid',
      year: 2021,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 12.0,
      pricePerDay: 1500.0,
      pricePerHour: 120.0,
      rating: 4.0,
    ),
    const CarModel(
      id: 'car24',
      vendorId: 'v12',
      make: 'Kia',
      model: 'Seltos',
      year: 2022,
      type: 'SUV',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 18.0,
      pricePerDay: 3500.0,
      pricePerHour: 300.0,
      rating: 4.2,
    ),

    // Chennai (v13 - v16)
    // v13
    const CarModel(
      id: 'car25',
      vendorId: 'v13',
      make: 'Maruti Suzuki',
      model: 'Baleno',
      year: 2022,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 12.0,
      pricePerDay: 1500.0,
      pricePerHour: 120.0,
      rating: 4.5,
    ),
    const CarModel(
      id: 'car26',
      vendorId: 'v13',
      make: 'Toyota',
      model: 'Fortuner',
      year: 2022,
      type: 'SUV',
      fuelType: 'Diesel',
      seating: 7,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 18.0,
      pricePerDay: 3500.0,
      pricePerHour: 300.0,
      rating: 4.6,
    ),
    // v14
    const CarModel(
      id: 'car27',
      vendorId: 'v14',
      make: 'Volkswagen',
      model: 'Virtus',
      year: 2022,
      type: 'Sedan',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 15.0,
      pricePerDay: 2000.0,
      pricePerHour: 180.0,
      rating: 4.3,
    ),
    const CarModel(
      id: 'car28',
      vendorId: 'v14',
      make: 'Jaguar',
      model: 'XF',
      year: 2021,
      type: 'Luxury',
      fuelType: 'Diesel',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1555215695-3004980ad54e'],
      pricePerKm: 35.0,
      pricePerDay: 8000.0,
      pricePerHour: 800.0,
      rating: 4.4,
    ),
    // v15
    const CarModel(
      id: 'car29',
      vendorId: 'v15',
      make: 'Force',
      model: 'Traveller 9S',
      year: 2021,
      type: 'Tempo Traveller',
      fuelType: 'Diesel',
      seating: 9,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 24.0,
      pricePerDay: 5000.0,
      pricePerHour: 450.0,
      rating: 4.5,
    ),
    const CarModel(
      id: 'car30',
      vendorId: 'v15',
      make: 'Ashok Leyland',
      model: 'Mitr',
      year: 2020,
      type: 'Mini Bus',
      fuelType: 'Diesel',
      seating: 18,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 30.0,
      pricePerDay: 7000.0,
      pricePerHour: 600.0,
      rating: 4.6,
    ),
    // v16
    const CarModel(
      id: 'car31',
      vendorId: 'v16',
      make: 'Hyundai',
      model: 'Grand i10',
      year: 2022,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 12.0,
      pricePerDay: 1500.0,
      pricePerHour: 120.0,
      rating: 4.7,
    ),
    const CarModel(
      id: 'car32',
      vendorId: 'v16',
      make: 'Mahindra',
      model: 'Scorpio-N',
      year: 2022,
      type: 'SUV',
      fuelType: 'Diesel',
      seating: 7,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 18.0,
      pricePerDay: 3500.0,
      pricePerHour: 300.0,
      rating: 4.8,
    ),

    // Hyderabad (v17 - v20)
    // v17
    const CarModel(
      id: 'car33',
      vendorId: 'v17',
      make: 'Maruti Suzuki',
      model: 'Alto K10',
      year: 2021,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: false,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 12.0,
      pricePerDay: 1500.0,
      pricePerHour: 120.0,
      rating: 4.5,
    ),
    const CarModel(
      id: 'car34',
      vendorId: 'v17',
      make: 'MG',
      model: 'Hector',
      year: 2022,
      type: 'SUV',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 18.0,
      pricePerDay: 3500.0,
      pricePerHour: 300.0,
      rating: 4.6,
    ),
    // v18
    const CarModel(
      id: 'car35',
      vendorId: 'v18',
      make: 'Maruti Suzuki',
      model: 'Dzire',
      year: 2022,
      type: 'Sedan',
      fuelType: 'CNG',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 15.0,
      pricePerDay: 2000.0,
      pricePerHour: 180.0,
      rating: 4.3,
    ),
    const CarModel(
      id: 'car36',
      vendorId: 'v18',
      make: 'Volvo',
      model: 'XC60',
      year: 2022,
      type: 'Luxury',
      fuelType: 'Diesel',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1555215695-3004980ad54e'],
      pricePerKm: 35.0,
      pricePerDay: 8000.0,
      pricePerHour: 800.0,
      rating: 4.4,
    ),
    // v19
    const CarModel(
      id: 'car37',
      vendorId: 'v19',
      make: 'Force',
      model: 'Traveller 15S',
      year: 2022,
      type: 'Tempo Traveller',
      fuelType: 'Diesel',
      seating: 15,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 24.0,
      pricePerDay: 5000.0,
      pricePerHour: 450.0,
      rating: 4.6,
    ),
    const CarModel(
      id: 'car38',
      vendorId: 'v19',
      make: 'Force',
      model: 'Urbania',
      year: 2023,
      type: 'Mini Bus',
      fuelType: 'Diesel',
      seating: 17,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 30.0,
      pricePerDay: 7000.0,
      pricePerHour: 600.0,
      rating: 4.5,
    ),
    // v20
    const CarModel(
      id: 'car39',
      vendorId: 'v20',
      make: 'Tata',
      model: 'Punch',
      year: 2022,
      type: 'Hatchback',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341'],
      pricePerKm: 12.0,
      pricePerDay: 1500.0,
      pricePerHour: 120.0,
      rating: 4.1,
    ),
    const CarModel(
      id: 'car40',
      vendorId: 'v20',
      make: 'Honda',
      model: 'Elevate',
      year: 2023,
      type: 'SUV',
      fuelType: 'Petrol',
      seating: 5,
      isAC: true,
      photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf'],
      pricePerKm: 18.0,
      pricePerDay: 3500.0,
      pricePerHour: 300.0,
      rating: 4.2,
    ),
  ];

  static final List<BookingModel> bookings = [
    // Completed Bookings (b1 to b30)
    BookingModel(
      id: 'b1',
      customerId: 'c1',
      vendorId: 'v1',
      carId: 'car1',
      tripType: 'Local',
      pickupLocation: 'Andheri East, Mumbai',
      dropLocation: 'Bandra West, Mumbai',
      startDate: DateTime(2026, 6, 1, 9, 0),
      endDate: DateTime(2026, 6, 1, 17, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'completed',
      createdAt: DateTime(2026, 5, 30, 10, 0),
    ),
    BookingModel(
      id: 'b2',
      customerId: 'c2',
      vendorId: 'v1',
      carId: 'car2',
      tripType: 'Self-Drive',
      pickupLocation: 'Mumbai Airport T2',
      dropLocation: 'Pune City Center',
      startDate: DateTime(2026, 6, 2, 8, 0),
      endDate: DateTime(2026, 6, 4, 20, 0),
      totalFare: 11180.0,
      platformFee: 1000.0,
      gstAmount: 180.0,
      netToVendor: 10000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 1, 14, 0),
    ),
    BookingModel(
      id: 'b3',
      customerId: 'c3',
      vendorId: 'v2',
      carId: 'car3',
      tripType: 'Airport Transfer',
      pickupLocation: 'Colaba, Mumbai',
      dropLocation: 'Mumbai Airport T1',
      startDate: DateTime(2026, 6, 3, 4, 0),
      endDate: DateTime(2026, 6, 3, 6, 0),
      totalFare: 2236.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 2000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 2, 18, 0),
    ),
    BookingModel(
      id: 'b4',
      customerId: 'c4',
      vendorId: 'v2',
      carId: 'car4',
      tripType: 'Outstation',
      pickupLocation: 'Borivali, Mumbai',
      dropLocation: 'Lonavala',
      startDate: DateTime(2026, 6, 5, 6, 0),
      endDate: DateTime(2026, 6, 6, 22, 0),
      totalFare: 22360.0,
      platformFee: 2000.0,
      gstAmount: 360.0,
      netToVendor: 20000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 3, 9, 30),
    ),
    BookingModel(
      id: 'b5',
      customerId: 'c5',
      vendorId: 'v3',
      carId: 'car5',
      tripType: 'Outstation',
      pickupLocation: 'Thane, Mumbai',
      dropLocation: 'Shirdi',
      startDate: DateTime(2026, 6, 7, 5, 0),
      endDate: DateTime(2026, 6, 8, 23, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 4, 11, 0),
    ),
    BookingModel(
      id: 'b6',
      customerId: 'c1',
      vendorId: 'v3',
      carId: 'car6',
      tripType: 'Local',
      pickupLocation: 'Dadar, Mumbai',
      dropLocation: 'Gateway of India, Mumbai',
      startDate: DateTime(2026, 6, 9, 10, 0),
      endDate: DateTime(2026, 6, 9, 18, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 8, 15, 0),
    ),
    BookingModel(
      id: 'b7',
      customerId: 'c2',
      vendorId: 'v5',
      carId: 'car9',
      tripType: 'Local',
      pickupLocation: 'Connaught Place, Delhi',
      dropLocation: 'Gurgaon Sector 21',
      startDate: DateTime(2026, 6, 10, 9, 0),
      endDate: DateTime(2026, 6, 10, 17, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 9, 12, 0),
    ),
    BookingModel(
      id: 'b8',
      customerId: 'c3',
      vendorId: 'v5',
      carId: 'car10',
      tripType: 'Outstation',
      pickupLocation: 'Noida Sector 62, Delhi',
      dropLocation: 'Agra Taj Mahal',
      startDate: DateTime(2026, 6, 12, 6, 0),
      endDate: DateTime(2026, 6, 12, 22, 0),
      totalFare: 11180.0,
      platformFee: 1000.0,
      gstAmount: 180.0,
      netToVendor: 10000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 10, 8, 0),
    ),
    BookingModel(
      id: 'b9',
      customerId: 'c4',
      vendorId: 'v6',
      carId: 'car11',
      tripType: 'Self-Drive',
      pickupLocation: 'Delhi Airport T3',
      dropLocation: 'Chandigarh Sector 17',
      startDate: DateTime(2026, 6, 13, 10, 0),
      endDate: DateTime(2026, 6, 15, 18, 0),
      totalFare: 5590.0,
      platformFee: 500.0,
      gstAmount: 90.0,
      netToVendor: 5000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 11, 20, 0),
    ),
    BookingModel(
      id: 'b10',
      customerId: 'c5',
      vendorId: 'v6',
      carId: 'car12',
      tripType: 'Local',
      pickupLocation: 'Karol Bagh, Delhi',
      dropLocation: 'South Ext, Delhi',
      startDate: DateTime(2026, 6, 16, 11, 0),
      endDate: DateTime(2026, 6, 16, 19, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 15, 9, 0),
    ),
    BookingModel(
      id: 'b11',
      customerId: 'c1',
      vendorId: 'v7',
      carId: 'car13',
      tripType: 'Outstation',
      pickupLocation: 'Dwarka, Delhi',
      dropLocation: 'Manali',
      startDate: DateTime(2026, 6, 18, 5, 0),
      endDate: DateTime(2026, 6, 21, 23, 0),
      totalFare: 27950.0,
      platformFee: 2500.0,
      gstAmount: 450.0,
      netToVendor: 25000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 15, 14, 0),
    ),
    BookingModel(
      id: 'b12',
      customerId: 'c2',
      vendorId: 'v7',
      carId: 'car14',
      tripType: 'Local',
      pickupLocation: 'Saket, Delhi',
      dropLocation: 'Rohini, Delhi',
      startDate: DateTime(2026, 6, 22, 9, 0),
      endDate: DateTime(2026, 6, 22, 17, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 21, 10, 0),
    ),
    BookingModel(
      id: 'b13',
      customerId: 'c3',
      vendorId: 'v9',
      carId: 'car17',
      tripType: 'Local',
      pickupLocation: 'Indiranagar, Bangalore',
      dropLocation: 'Whitefield, Bangalore',
      startDate: DateTime(2026, 6, 5, 9, 0),
      endDate: DateTime(2026, 6, 5, 17, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 4, 11, 0),
    ),
    BookingModel(
      id: 'b14',
      customerId: 'c4',
      vendorId: 'v9',
      carId: 'car18',
      tripType: 'Self-Drive',
      pickupLocation: 'Koramangala, Bangalore',
      dropLocation: 'Coorg',
      startDate: DateTime(2026, 6, 7, 7, 0),
      endDate: DateTime(2026, 6, 9, 21, 0),
      totalFare: 11180.0,
      platformFee: 1000.0,
      gstAmount: 180.0,
      netToVendor: 10000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 5, 16, 0),
    ),
    BookingModel(
      id: 'b15',
      customerId: 'c5',
      vendorId: 'v10',
      carId: 'car19',
      tripType: 'Airport Transfer',
      pickupLocation: 'Jayanagar, Bangalore',
      dropLocation: 'Kempegowda Airport',
      startDate: DateTime(2026, 6, 10, 14, 0),
      endDate: DateTime(2026, 6, 10, 16, 30),
      totalFare: 2236.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 2000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 9, 10, 0),
    ),
    BookingModel(
      id: 'b16',
      customerId: 'c1',
      vendorId: 'v10',
      carId: 'car20',
      tripType: 'Local',
      pickupLocation: 'Hebbal, Bangalore',
      dropLocation: 'Electronic City, Bangalore',
      startDate: DateTime(2026, 6, 12, 10, 0),
      endDate: DateTime(2026, 6, 12, 18, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 11, 8, 30),
    ),
    BookingModel(
      id: 'b17',
      customerId: 'c2',
      vendorId: 'v11',
      carId: 'car21',
      tripType: 'Outstation',
      pickupLocation: 'Malleshwaram, Bangalore',
      dropLocation: 'Mysore Palace',
      startDate: DateTime(2026, 6, 14, 6, 0),
      endDate: DateTime(2026, 6, 15, 22, 0),
      totalFare: 5590.0,
      platformFee: 500.0,
      gstAmount: 90.0,
      netToVendor: 5000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 12, 11, 0),
    ),
    BookingModel(
      id: 'b18',
      customerId: 'c3',
      vendorId: 'v11',
      carId: 'car22',
      tripType: 'Local',
      pickupLocation: 'Marathahalli, Bangalore',
      dropLocation: 'Bannerghatta National Park',
      startDate: DateTime(2026, 6, 16, 8, 0),
      endDate: DateTime(2026, 6, 16, 18, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 15, 14, 0),
    ),
    BookingModel(
      id: 'b19',
      customerId: 'c4',
      vendorId: 'v13',
      carId: 'car25',
      tripType: 'Local',
      pickupLocation: 'Adyar, Chennai',
      dropLocation: 'T Nagar, Chennai',
      startDate: DateTime(2026, 6, 8, 9, 0),
      endDate: DateTime(2026, 6, 8, 17, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 7, 10, 0),
    ),
    BookingModel(
      id: 'b20',
      customerId: 'c5',
      vendorId: 'v13',
      carId: 'car26',
      tripType: 'Outstation',
      pickupLocation: 'Velachery, Chennai',
      dropLocation: 'Pondicherry',
      startDate: DateTime(2026, 6, 10, 6, 0),
      endDate: DateTime(2026, 6, 11, 22, 0),
      totalFare: 11180.0,
      platformFee: 1000.0,
      gstAmount: 180.0,
      netToVendor: 10000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 8, 15, 0),
    ),
    BookingModel(
      id: 'b21',
      customerId: 'c1',
      vendorId: 'v14',
      carId: 'car27',
      tripType: 'Self-Drive',
      pickupLocation: 'Chennai Airport T1',
      dropLocation: 'Mahabalipuram',
      startDate: DateTime(2026, 6, 12, 10, 0),
      endDate: DateTime(2026, 6, 13, 20, 0),
      totalFare: 2236.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 2000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 10, 11, 0),
    ),
    BookingModel(
      id: 'b22',
      customerId: 'c2',
      vendorId: 'v14',
      carId: 'car28',
      tripType: 'Local',
      pickupLocation: 'Anna Nagar, Chennai',
      dropLocation: 'OMR, Chennai',
      startDate: DateTime(2026, 6, 15, 9, 0),
      endDate: DateTime(2026, 6, 15, 17, 0),
      totalFare: 22360.0,
      platformFee: 2000.0,
      gstAmount: 360.0,
      netToVendor: 20000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 14, 16, 0),
    ),
    BookingModel(
      id: 'b23',
      customerId: 'c3',
      vendorId: 'v15',
      carId: 'car29',
      tripType: 'Outstation',
      pickupLocation: 'Tambaram, Chennai',
      dropLocation: 'Tirupati',
      startDate: DateTime(2026, 6, 18, 5, 0),
      endDate: DateTime(2026, 6, 19, 23, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 16, 9, 0),
    ),
    BookingModel(
      id: 'b24',
      customerId: 'c4',
      vendorId: 'v15',
      carId: 'car30',
      tripType: 'Local',
      pickupLocation: 'Guindy, Chennai',
      dropLocation: 'Marina Beach, Chennai',
      startDate: DateTime(2026, 6, 21, 10, 0),
      endDate: DateTime(2026, 6, 21, 18, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 20, 12, 0),
    ),
    BookingModel(
      id: 'b25',
      customerId: 'c5',
      vendorId: 'v17',
      carId: 'car33',
      tripType: 'Local',
      pickupLocation: 'Gachibowli, Hyderabad',
      dropLocation: 'Secunderabad',
      startDate: DateTime(2026, 6, 10, 9, 0),
      endDate: DateTime(2026, 6, 10, 17, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 9, 11, 0),
    ),
    BookingModel(
      id: 'b26',
      customerId: 'c1',
      vendorId: 'v17',
      carId: 'car34',
      tripType: 'Outstation',
      pickupLocation: 'Jubilee Hills, Hyderabad',
      dropLocation: 'Srisailam',
      startDate: DateTime(2026, 6, 12, 6, 0),
      endDate: DateTime(2026, 6, 13, 22, 0),
      totalFare: 11180.0,
      platformFee: 1000.0,
      gstAmount: 180.0,
      netToVendor: 10000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 10, 15, 0),
    ),
    BookingModel(
      id: 'b27',
      customerId: 'c2',
      vendorId: 'v18',
      carId: 'car35',
      tripType: 'Airport Transfer',
      pickupLocation: 'Banjara Hills, Hyderabad',
      dropLocation: 'Rajiv Gandhi Airport',
      startDate: DateTime(2026, 6, 15, 13, 0),
      endDate: DateTime(2026, 6, 15, 15, 0),
      totalFare: 2236.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 2000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 14, 8, 0),
    ),
    BookingModel(
      id: 'b28',
      customerId: 'c3',
      vendorId: 'v18',
      carId: 'car36',
      tripType: 'Local',
      pickupLocation: 'Begumpet, Hyderabad',
      dropLocation: 'Charminar, Hyderabad',
      startDate: DateTime(2026, 6, 17, 10, 0),
      endDate: DateTime(2026, 6, 17, 18, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 16, 9, 30),
    ),
    BookingModel(
      id: 'b29',
      customerId: 'c4',
      vendorId: 'v19',
      carId: 'car37',
      tripType: 'Outstation',
      pickupLocation: 'Kondapur, Hyderabad',
      dropLocation: 'Warangal Fort',
      startDate: DateTime(2026, 6, 20, 6, 0),
      endDate: DateTime(2026, 6, 20, 22, 0),
      totalFare: 5590.0,
      platformFee: 500.0,
      gstAmount: 90.0,
      netToVendor: 5000.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 19, 14, 0),
    ),
    BookingModel(
      id: 'b30',
      customerId: 'c5',
      vendorId: 'v19',
      carId: 'car38',
      tripType: 'Local',
      pickupLocation: 'Kukatpally, Hyderabad',
      dropLocation: 'Ramoji Film City',
      startDate: DateTime(2026, 6, 22, 8, 0),
      endDate: DateTime(2026, 6, 22, 20, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'completed',
      createdAt: DateTime(2026, 6, 21, 10, 0),
    ),

    // Ongoing Bookings (b31 to b38) - active around July 1, 2026
    BookingModel(
      id: 'b31',
      customerId: 'c1',
      vendorId: 'v1',
      carId: 'car1',
      tripType: 'Local',
      pickupLocation: 'Bandra, Mumbai',
      dropLocation: 'Andheri, Mumbai',
      startDate: DateTime(2026, 6, 30, 9, 0),
      endDate: DateTime(2026, 7, 2, 18, 0),
      totalFare: 5590.0,
      platformFee: 500.0,
      gstAmount: 90.0,
      netToVendor: 5000.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 29, 10, 0),
    ),
    BookingModel(
      id: 'b32',
      customerId: 'c2',
      vendorId: 'v5',
      carId: 'car10',
      tripType: 'Outstation',
      pickupLocation: 'Vasant Kunj, Delhi',
      dropLocation: 'Jaipur',
      startDate: DateTime(2026, 6, 30, 6, 0),
      endDate: DateTime(2026, 7, 2, 22, 0),
      totalFare: 16770.0,
      platformFee: 1500.0,
      gstAmount: 270.0,
      netToVendor: 15000.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 28, 14, 0),
    ),
    BookingModel(
      id: 'b33',
      customerId: 'c3',
      vendorId: 'v9',
      carId: 'car18',
      tripType: 'Self-Drive',
      pickupLocation: 'HSR Layout, Bangalore',
      dropLocation: 'Ooty',
      startDate: DateTime(2026, 6, 30, 8, 0),
      endDate: DateTime(2026, 7, 3, 20, 0),
      totalFare: 22360.0,
      platformFee: 2000.0,
      gstAmount: 360.0,
      netToVendor: 20000.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 29, 11, 0),
    ),
    BookingModel(
      id: 'b34',
      customerId: 'c4',
      vendorId: 'v13',
      carId: 'car26',
      tripType: 'Local',
      pickupLocation: 'Mylapore, Chennai',
      dropLocation: 'Besant Nagar, Chennai',
      startDate: DateTime(2026, 6, 30, 10, 0),
      endDate: DateTime(2026, 7, 2, 19, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 29, 15, 0),
    ),
    BookingModel(
      id: 'b35',
      customerId: 'c5',
      vendorId: 'v17',
      carId: 'car34',
      tripType: 'Outstation',
      pickupLocation: 'Madhapur, Hyderabad',
      dropLocation: 'Vijayawada',
      startDate: DateTime(2026, 6, 30, 7, 0),
      endDate: DateTime(2026, 7, 2, 21, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 28, 9, 0),
    ),
    BookingModel(
      id: 'b36',
      customerId: 'c1',
      vendorId: 'v2',
      carId: 'car3',
      tripType: 'Airport Transfer',
      pickupLocation: 'Mumbai Airport T2',
      dropLocation: 'Ghatkopar, Mumbai',
      startDate: DateTime(2026, 7, 1, 10, 0),
      endDate: DateTime(2026, 7, 1, 14, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 30, 20, 0),
    ),
    BookingModel(
      id: 'b37',
      customerId: 'c2',
      vendorId: 'v6',
      carId: 'car11',
      tripType: 'Local',
      pickupLocation: 'Saket, Delhi',
      dropLocation: 'Connaught Place, Delhi',
      startDate: DateTime(2026, 7, 1, 11, 0),
      endDate: DateTime(2026, 7, 1, 19, 0),
      totalFare: 2236.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 2000.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 6, 30, 22, 0),
    ),
    BookingModel(
      id: 'b38',
      customerId: 'c3',
      vendorId: 'v10',
      carId: 'car19',
      tripType: 'Local',
      pickupLocation: 'Indiranagar, Bangalore',
      dropLocation: 'Malleshwaram, Bangalore',
      startDate: DateTime(2026, 7, 1, 12, 0),
      endDate: DateTime(2026, 7, 1, 20, 0),
      totalFare: 3354.0,
      platformFee: 300.0,
      gstAmount: 54.0,
      netToVendor: 3000.0,
      status: 'ongoing',
      createdAt: DateTime(2026, 7, 1, 8, 0),
    ),

    // Upcoming Bookings (b39 to b45) - starting after July 1, 2026
    BookingModel(
      id: 'b39',
      customerId: 'c1',
      vendorId: 'v1',
      carId: 'car2',
      tripType: 'Self-Drive',
      pickupLocation: 'Mumbai Airport T2',
      dropLocation: 'Goa',
      startDate: DateTime(2026, 7, 5, 8, 0),
      endDate: DateTime(2026, 7, 10, 20, 0),
      totalFare: 27950.0,
      platformFee: 2500.0,
      gstAmount: 450.0,
      netToVendor: 25000.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 6, 28, 14, 0),
    ),
    BookingModel(
      id: 'b40',
      customerId: 'c2',
      vendorId: 'v5',
      carId: 'car9',
      tripType: 'Local',
      pickupLocation: 'Delhi Airport T3',
      dropLocation: 'Noida Sector 15',
      startDate: DateTime(2026, 7, 3, 10, 0),
      endDate: DateTime(2026, 7, 3, 18, 0),
      totalFare: 2236.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 2000.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 6, 30, 9, 0),
    ),
    BookingModel(
      id: 'b41',
      customerId: 'c3',
      vendorId: 'v9',
      carId: 'car17',
      tripType: 'Local',
      pickupLocation: 'Koramangala, Bangalore',
      dropLocation: 'Whitefield, Bangalore',
      startDate: DateTime(2026, 7, 4, 9, 0),
      endDate: DateTime(2026, 7, 4, 17, 0),
      totalFare: 1677.0,
      platformFee: 150.0,
      gstAmount: 27.0,
      netToVendor: 1500.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 7, 1, 10, 0),
    ),
    BookingModel(
      id: 'b42',
      customerId: 'c4',
      vendorId: 'v13',
      carId: 'car25',
      tripType: 'Outstation',
      pickupLocation: 'Adyar, Chennai',
      dropLocation: 'Yercaud',
      startDate: DateTime(2026, 7, 8, 6, 0),
      endDate: DateTime(2026, 7, 10, 22, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 6, 30, 11, 0),
    ),
    BookingModel(
      id: 'b43',
      customerId: 'c5',
      vendorId: 'v17',
      carId: 'car33',
      tripType: 'Airport Transfer',
      pickupLocation: 'Gachibowli, Hyderabad',
      dropLocation: 'Rajiv Gandhi Airport',
      startDate: DateTime(2026, 7, 5, 4, 0),
      endDate: DateTime(2026, 7, 5, 6, 30),
      totalFare: 1118.0,
      platformFee: 100.0,
      gstAmount: 18.0,
      netToVendor: 1000.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 7, 1, 9, 0),
    ),
    BookingModel(
      id: 'b44',
      customerId: 'c1',
      vendorId: 'v2',
      carId: 'car4',
      tripType: 'Self-Drive',
      pickupLocation: 'Bandra West, Mumbai',
      dropLocation: 'Mahabaleshwar',
      startDate: DateTime(2026, 7, 12, 7, 0),
      endDate: DateTime(2026, 7, 14, 21, 0),
      totalFare: 22360.0,
      platformFee: 2000.0,
      gstAmount: 360.0,
      netToVendor: 20000.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 6, 29, 16, 0),
    ),
    BookingModel(
      id: 'b45',
      customerId: 'c2',
      vendorId: 'v6',
      carId: 'car12',
      tripType: 'Outstation',
      pickupLocation: 'South Ext, Delhi',
      dropLocation: 'Mussoorie',
      startDate: DateTime(2026, 7, 15, 5, 0),
      endDate: DateTime(2026, 7, 18, 23, 0),
      totalFare: 27950.0,
      platformFee: 2500.0,
      gstAmount: 450.0,
      netToVendor: 25000.0,
      status: 'confirmed',
      createdAt: DateTime(2026, 6, 28, 12, 0),
    ),

    // Cancelled Bookings (b46 to b50)
    BookingModel(
      id: 'b46',
      customerId: 'c3',
      vendorId: 'v3',
      carId: 'car5',
      tripType: 'Outstation',
      pickupLocation: 'Thane, Mumbai',
      dropLocation: 'Mahabaleshwar',
      startDate: DateTime(2026, 6, 18, 6, 0),
      endDate: DateTime(2026, 6, 20, 22, 0),
      totalFare: 13416.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 12000.0,
      status: 'cancelled',
      createdAt: DateTime(2026, 6, 15, 10, 0),
    ),
    BookingModel(
      id: 'b47',
      customerId: 'c4',
      vendorId: 'v7',
      carId: 'car13',
      tripType: 'Outstation',
      pickupLocation: 'Gurgaon, Delhi',
      dropLocation: 'Nainital',
      startDate: DateTime(2026, 6, 20, 5, 0),
      endDate: DateTime(2026, 6, 22, 23, 0),
      totalFare: 22360.0,
      platformFee: 2000.0,
      gstAmount: 360.0,
      netToVendor: 20000.0,
      status: 'cancelled',
      createdAt: DateTime(2026, 6, 18, 9, 0),
    ),
    BookingModel(
      id: 'b48',
      customerId: 'c5',
      vendorId: 'v11',
      carId: 'car21',
      tripType: 'Local',
      pickupLocation: 'Jayanagar, Bangalore',
      dropLocation: 'Nandi Hills',
      startDate: DateTime(2026, 6, 22, 8, 0),
      endDate: DateTime(2026, 6, 22, 18, 0),
      totalFare: 5590.0,
      platformFee: 500.0,
      gstAmount: 90.0,
      netToVendor: 5000.0,
      status: 'cancelled',
      createdAt: DateTime(2026, 6, 20, 11, 0),
    ),
    BookingModel(
      id: 'b49',
      customerId: 'c1',
      vendorId: 'v15',
      carId: 'car29',
      tripType: 'Outstation',
      pickupLocation: 'Adyar, Chennai',
      dropLocation: 'Bangalore',
      startDate: DateTime(2026, 6, 25, 6, 0),
      endDate: DateTime(2026, 6, 27, 22, 0),
      totalFare: 16770.0,
      platformFee: 1500.0,
      gstAmount: 270.0,
      netToVendor: 15000.0,
      status: 'cancelled',
      createdAt: DateTime(2026, 6, 22, 14, 0),
    ),
    BookingModel(
      id: 'b50',
      customerId: 'c2',
      vendorId: 'v19',
      carId: 'car37',
      tripType: 'Local',
      pickupLocation: 'Gachibowli, Hyderabad',
      dropLocation: 'Ramoji Film City',
      startDate: DateTime(2026, 6, 26, 8, 0),
      endDate: DateTime(2026, 6, 26, 20, 0),
      totalFare: 8385.0,
      platformFee: 750.0,
      gstAmount: 135.0,
      netToVendor: 7500.0,
      status: 'cancelled',
      createdAt: DateTime(2026, 6, 24, 16, 0),
    ),
    BookingModel(
      id: 'b_pending_1',
      customerId: 'c1',
      vendorId: 'v1',
      carId: 'car1',
      tripType: 'Local',
      pickupLocation: 'Andheri West, Mumbai',
      dropLocation: 'Bandra, Mumbai',
      startDate: DateTime(2026, 7, 2, 9, 0),
      endDate: DateTime(2026, 7, 2, 18, 0),
      totalFare: 2000.0,
      platformFee: 200.0,
      gstAmount: 36.0,
      netToVendor: 1764.0,
      status: 'pending',
      createdAt: DateTime(2026, 7, 1, 10, 0),
    ),
    BookingModel(
      id: 'b_pending_2',
      customerId: 'c2',
      vendorId: 'v1',
      carId: 'car2',
      tripType: 'Outstation',
      pickupLocation: 'Mumbai T2 Airport',
      dropLocation: 'Pune Center',
      startDate: DateTime(2026, 7, 3, 7, 0),
      endDate: DateTime(2026, 7, 5, 23, 0),
      totalFare: 12000.0,
      platformFee: 1200.0,
      gstAmount: 216.0,
      netToVendor: 10584.0,
      status: 'pending',
      createdAt: DateTime(2026, 7, 1, 11, 0),
    ),
    BookingModel(
      id: 'b_pending_3',
      customerId: 'c3',
      vendorId: 'v1',
      carId: 'car1',
      tripType: 'Local',
      pickupLocation: 'Bandra West, Mumbai',
      dropLocation: 'Colaba, Mumbai',
      startDate: DateTime(2026, 7, 4, 10, 0),
      endDate: DateTime(2026, 7, 4, 18, 0),
      totalFare: 1800.0,
      platformFee: 180.0,
      gstAmount: 32.4,
      netToVendor: 1587.6,
      status: 'pending',
      createdAt: DateTime(2026, 7, 1, 12, 0),
    ),
  ];

  static final List<ReviewModel> reviews = [
    ReviewModel(
      id: 'r1',
      bookingId: 'b1',
      customerId: 'c1',
      vendorId: 'v1',
      rating: 4.5,
      comment: 'Excellent car condition, clean interiors and smooth ride!',
      createdAt: DateTime(2026, 6, 1, 18, 0),
    ),
    ReviewModel(
      id: 'r2',
      bookingId: 'b2',
      customerId: 'c2',
      vendorId: 'v1',
      rating: 5.0,
      comment: 'Absolutely loved the XUV700. The self-drive experience was top-notch.',
      createdAt: DateTime(2026, 6, 4, 21, 0),
    ),
    ReviewModel(
      id: 'r3',
      bookingId: 'b3',
      customerId: 'c3',
      vendorId: 'v2',
      rating: 4.0,
      comment: 'Punctual service and polite driver for airport drop-off.',
      createdAt: DateTime(2026, 6, 3, 7, 0),
    ),
    ReviewModel(
      id: 'r4',
      bookingId: 'b4',
      customerId: 'c4',
      vendorId: 'v2',
      rating: 4.5,
      comment: 'The BMW was clean and drove beautifully. Perfect weekend getaway.',
      createdAt: DateTime(2026, 6, 6, 23, 0),
    ),
    ReviewModel(
      id: 'r5',
      bookingId: 'b5',
      customerId: 'c5',
      vendorId: 'v3',
      rating: 5.0,
      comment: 'Force Traveller was spacious and clean. Highly recommended for families.',
      createdAt: DateTime(2026, 6, 8, 23, 30),
    ),
    ReviewModel(
      id: 'r6',
      bookingId: 'b6',
      customerId: 'c1',
      vendorId: 'v3',
      rating: 4.0,
      comment: 'Decent experience. Bus was on time but AC could have been cooler.',
      createdAt: DateTime(2026, 6, 9, 19, 0),
    ),
    ReviewModel(
      id: 'r7',
      bookingId: 'b7',
      customerId: 'c2',
      vendorId: 'v5',
      rating: 4.0,
      comment: 'Affordable hatchback booking, neat car and polite vendor.',
      createdAt: DateTime(2026, 6, 10, 18, 0),
    ),
    ReviewModel(
      id: 'r8',
      bookingId: 'b8',
      customerId: 'c3',
      vendorId: 'v5',
      rating: 4.5,
      comment: 'Clean Innova, very comfortable for our family trip to Agra.',
      createdAt: DateTime(2026, 6, 12, 23, 0),
    ),
    ReviewModel(
      id: 'r9',
      bookingId: 'b9',
      customerId: 'c4',
      vendorId: 'v6',
      rating: 4.5,
      comment: 'Self drive Verna was awesome. Pick up process was swift and easy.',
      createdAt: DateTime(2026, 6, 15, 19, 0),
    ),
    ReviewModel(
      id: 'r10',
      bookingId: 'b10',
      customerId: 'c5',
      vendorId: 'v6',
      rating: 3.5,
      comment: 'The ride was okay, but there was a slight delay in delivery.',
      createdAt: DateTime(2026, 6, 16, 20, 0),
    ),
    ReviewModel(
      id: 'r11',
      bookingId: 'b11',
      customerId: 'c1',
      vendorId: 'v7',
      rating: 5.0,
      comment: 'Force Traveller was in great condition, driver was very experienced in hills.',
      createdAt: DateTime(2026, 6, 21, 23, 30),
    ),
    ReviewModel(
      id: 'r12',
      bookingId: 'b12',
      customerId: 'c2',
      vendorId: 'v7',
      rating: 4.5,
      comment: 'Spacious mini bus, very comfortable for corporate local commute.',
      createdAt: DateTime(2026, 6, 22, 18, 30),
    ),
    ReviewModel(
      id: 'r13',
      bookingId: 'b13',
      customerId: 'c3',
      vendorId: 'v9',
      rating: 5.0,
      comment: 'Extremely clean Tiago. Great mileage and hassle-free pickup.',
      createdAt: DateTime(2026, 6, 5, 18, 0),
    ),
    ReviewModel(
      id: 'r14',
      bookingId: 'b14',
      customerId: 'c4',
      vendorId: 'v9',
      rating: 4.8,
      comment: 'Loved driving the Thar in Coorg. Amazing experience!',
      createdAt: DateTime(2026, 6, 9, 22, 0),
    ),
    ReviewModel(
      id: 'r15',
      bookingId: 'b15',
      customerId: 'c5',
      vendorId: 'v10',
      rating: 4.5,
      comment: 'Timely airport transfer, clean sedan and polite driver.',
      createdAt: DateTime(2026, 6, 10, 17, 30),
    ),
    ReviewModel(
      id: 'r16',
      bookingId: 'b16',
      customerId: 'c1',
      vendorId: 'v10',
      rating: 4.0,
      comment: 'Excellent luxury car, very professional service.',
      createdAt: DateTime(2026, 6, 12, 19, 0),
    ),
    ReviewModel(
      id: 'r17',
      bookingId: 'b17',
      customerId: 'c2',
      vendorId: 'v11',
      rating: 4.0,
      comment: 'Good trip to Mysore. Traveller was clean and comfortable.',
      createdAt: DateTime(2026, 6, 15, 23, 0),
    ),
    ReviewModel(
      id: 'r18',
      bookingId: 'b19',
      customerId: 'c4',
      vendorId: 'v13',
      rating: 4.5,
      comment: 'Smooth Baleno, great for navigating Chennai traffic. Neat car.',
      createdAt: DateTime(2026, 6, 8, 18, 0),
    ),
    ReviewModel(
      id: 'r19',
      bookingId: 'b20',
      customerId: 'c5',
      vendorId: 'v13',
      rating: 4.6,
      comment: 'The Fortuner was a beast! Smooth ride to Pondicherry.',
      createdAt: DateTime(2026, 6, 11, 23, 0),
    ),
    ReviewModel(
      id: 'r20',
      bookingId: 'b25',
      customerId: 'c5',
      vendorId: 'v17',
      rating: 4.5,
      comment: 'Clean Alto, ideal for short errands in Hyderabad.',
      createdAt: DateTime(2026, 6, 10, 18, 0),
    ),
  ];

  static final List<EarningsModel> earnings = _generateMockEarnings();

  static List<EarningsModel> _generateMockEarnings() {
    final List<EarningsModel> list = [];
    final List<double> baseAmounts = [5000.0, 7500.0, 10000.0, 12000.0, 15000.0];

    // For each of the 20 vendors
    for (int i = 1; i <= 20; i++) {
      final vendorId = 'v$i';

      // Create 3 entries in the last 30 days: June 10, June 20, June 28
      final dates = [
        DateTime(2026, 6, 10),
        DateTime(2026, 6, 20),
        DateTime(2026, 6, 28),
      ];

      for (int d = 0; d < dates.length; d++) {
        final base = baseAmounts[(i + d) % baseAmounts.length];
        final platformFee = base * 0.10;
        final gst = platformFee * 0.18;
        final total = base + platformFee + gst;

        list.add(EarningsModel(
          vendorId: vendorId,
          date: dates[d],
          grossAmount: total,
          platformFee: platformFee,
          gstAmount: gst,
          netAmount: base,
        ));
      }
    }
    return list;
  }

  static final List<NotificationModel> notifications = [
    // Customers (c1 to c5)
    NotificationModel(
      id: 'n1',
      userId: 'c1',
      title: 'Booking Confirmed',
      body: 'Your booking b1 has been confirmed by the vendor.',
      type: 'booking',
      isRead: false,
      createdAt: DateTime(2026, 6, 30, 10, 30),
    ),
    NotificationModel(
      id: 'n2',
      userId: 'c1',
      title: 'Offer Active',
      body: 'Get 15% off on your next luxury car ride!',
      type: 'promotion',
      isRead: true,
      createdAt: DateTime(2026, 6, 28, 9, 0),
    ),
    NotificationModel(
      id: 'n3',
      userId: 'c2',
      title: 'Payment Successful',
      body: 'Payment of ₹11,180 for booking b2 was successful.',
      type: 'payment',
      isRead: true,
      createdAt: DateTime(2026, 6, 1, 14, 5),
    ),
    NotificationModel(
      id: 'n4',
      userId: 'c3',
      title: 'Trip Started',
      body: 'Your trip b3 has started. Have a safe journey!',
      type: 'trip',
      isRead: false,
      createdAt: DateTime(2026, 6, 30, 8, 15),
    ),
    NotificationModel(
      id: 'n5',
      userId: 'c4',
      title: 'Rate Your Trip',
      body: 'How was your trip with Gateway Self Drive? Rate now!',
      type: 'review',
      isRead: true,
      createdAt: DateTime(2026, 6, 22, 10, 0),
    ),
    NotificationModel(
      id: 'n6',
      userId: 'c5',
      title: 'Refund Initiated',
      body: 'Refund of ₹8,385 for booking b50 has been initiated.',
      type: 'payment',
      isRead: false,
      createdAt: DateTime(2026, 6, 25, 17, 0),
    ),

    // Vendors (v1 to v20)
    NotificationModel(
      id: 'n7',
      userId: 'v1',
      title: 'New Booking Request',
      body: 'You have a new booking b1 for Maruti Suzuki Swift.',
      type: 'booking',
      isRead: false,
      createdAt: DateTime(2026, 6, 30, 10, 0),
    ),
    NotificationModel(
      id: 'n8',
      userId: 'v1',
      title: 'Payout Disbursed',
      body: 'Your weekly payout of ₹15,000 has been transferred.',
      type: 'payout',
      isRead: true,
      createdAt: DateTime(2026, 6, 25, 18, 0),
    ),
    NotificationModel(
      id: 'n9',
      userId: 'v2',
      title: 'Document Verified',
      body: 'Your business GST details have been verified successfully.',
      type: 'verification',
      isRead: true,
      createdAt: DateTime(2026, 6, 10, 11, 0),
    ),
    NotificationModel(
      id: 'n10',
      userId: 'v5',
      title: 'Review Received',
      body: 'Customer left a 4.5 star review for your Toyota Innova.',
      type: 'review',
      isRead: false,
      createdAt: DateTime(2026, 6, 12, 23, 10),
    ),

    // Admins
    NotificationModel(
      id: 'n11',
      userId: 'admin1',
      title: 'Pending Vendor Verification',
      body: 'Vendor v4 (Gateway Self Drive) is waiting for verification.',
      type: 'admin_action',
      isRead: false,
      createdAt: DateTime(2026, 7, 1, 9, 0),
    ),
    NotificationModel(
      id: 'n12',
      userId: 'admin1',
      title: 'System Performance',
      body: 'Database backup completed successfully.',
      type: 'system',
      isRead: true,
      createdAt: DateTime(2026, 7, 1, 1, 0),
    ),
  ];

  static final List<CommissionConfigModel> commissionConfigs = [
    CommissionConfigModel(
      id: 'cc1',
      tripType: 'All',
      city: 'All',
      carCategory: 'All',
      percentage: 10.0,
      effectiveFrom: DateTime(2026, 1, 1),
    ),
    CommissionConfigModel(
      id: 'cc2',
      tripType: 'All',
      city: 'All',
      carCategory: 'Luxury',
      percentage: 12.0,
      effectiveFrom: DateTime(2026, 1, 1),
    ),
    CommissionConfigModel(
      id: 'cc3',
      tripType: 'Outstation',
      city: 'All',
      carCategory: 'All',
      percentage: 8.0,
      effectiveFrom: DateTime(2026, 1, 1),
    ),
  ];

  static final List<BannerModel> banners = [
    const BannerModel(
      id: 'banner1',
      title: 'Super Summer Sale',
      imageUrl: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e',
      ctaLink: '/promotions/summer',
      displayOrder: 1,
      isActive: true,
    ),
    const BannerModel(
      id: 'banner2',
      title: 'Explore Luxury Drives',
      imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e',
      ctaLink: '/search?category=Luxury',
      displayOrder: 2,
      isActive: true,
    ),
    const BannerModel(
      id: 'banner3',
      title: 'Outstation Getaways',
      imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800',
      ctaLink: '/search?tripType=Outstation',
      displayOrder: 3,
      isActive: true,
    ),
    const BannerModel(
      id: 'banner4',
      title: 'List Your Car & Earn',
      imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994',
      ctaLink: '/vendor/register',
      displayOrder: 4,
      isActive: true,
    ),
  ];
}
