import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Logger,
  Optional,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { WalletsService } from '../wallets/wallets.service';
import { AuditLogService } from '../admin/audit-log.service';
import { NotificationsService } from '../notifications/notifications.service';
import { ApmMonitoringService } from '../common/apm-monitoring.service';
import {
  ReferralStatus,
  LedgerEntryType,
  WalletBucketType,
  Prisma,
  BookingStatus,
} from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';
import { ApplyReferralCodeDto } from './dto/apply-referral-code.dto';
import { CreateReferralCampaignDto } from './dto/create-referral-campaign.dto';
import { UpdateReferralCampaignDto } from './dto/update-referral-campaign.dto';
import { SystemConfigService } from '../config-engine/system-config.service';
import * as crypto from 'crypto';

export const DEFAULT_REFERRER_REWARD = 250;
export const DEFAULT_REFEREE_DISCOUNT = 250;
export const DEFAULT_MIN_BOOKING_AMOUNT = 1000;
export const DEFAULT_MAX_REFERRALS_PER_USER = 20;

@Injectable()
export class ReferralsService {
  private readonly logger = new Logger(ReferralsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly walletsService: WalletsService,
    private readonly auditLogService: AuditLogService,
    private readonly notificationsService: NotificationsService,
    @Optional() private readonly apmMonitoringService?: ApmMonitoringService,
    @Optional() private readonly systemConfigService?: SystemConfigService,
  ) {}

  /**
   * Helper to ensure an active global referral campaign exists in DB.
   */
  async getOrCreateDefaultCampaign(tx?: Prisma.TransactionClient) {
    const client = tx || this.prisma;
    let campaign = await client.referralCampaign.findFirst({
      where: { code: 'DEFAULT_GLOBAL', isActive: true },
    });

    const refConfig = this.systemConfigService
      ? await this.systemConfigService.getReferralConfig()
      : {
          defaultReferrerReward: DEFAULT_REFERRER_REWARD,
          defaultRefereeReward: DEFAULT_REFEREE_DISCOUNT,
          minBookingAmount: DEFAULT_MIN_BOOKING_AMOUNT,
          maxReferralsPerUser: DEFAULT_MAX_REFERRALS_PER_USER,
          isReferralsEnabled: true,
        };

    if (!campaign) {
      campaign = await client.referralCampaign.create({
        data: {
          name: 'DriveGo Standard Referral Program',
          code: 'DEFAULT_GLOBAL',
          referrerRewardAmount: new Decimal(refConfig.defaultReferrerReward),
          refereeRewardAmount: new Decimal(refConfig.defaultRefereeReward),
          minBookingAmount: new Decimal(refConfig.minBookingAmount),
          maxReferralsPerUser: refConfig.maxReferralsPerUser,
          isActive: refConfig.isReferralsEnabled,
        },
      });
      this.logger.log(`Initialized default ReferralCampaign: ${campaign.id}`);
    }

    return campaign;
  }

  /**
   * Generates a stable, non-sensitive unique referral code for a user if absent.
   */
  async getOrCreateUserReferralCode(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { id: true, referralCode: true, name: true },
    });

    if (!user) {
      throw new NotFoundException(`User not found: ${userId}`);
    }

    let referralCode = user.referralCode;

    if (!referralCode) {
      // Generate clean 8-char uppercase code (e.g. DG7F92A1)
      const randomSuffix = crypto.randomBytes(3).toString('hex').toUpperCase();
      referralCode = `DG${randomSuffix}`;

      // Check collision
      const existing = await this.prisma.user.findUnique({
        where: { referralCode },
      });
      if (existing) {
        referralCode = `DG${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
      }

      await this.prisma.user.update({
        where: { id: userId },
        data: { referralCode },
      });
      this.logger.log(`Generated new referral code for user ${userId}: ${referralCode}`);
    }

    const campaign = await this.getOrCreateDefaultCampaign();

    return {
      referralCode,
      shareUrl: `https://drivego.in/invite?code=${referralCode}`,
      referrerReward: campaign.referrerRewardAmount.toNumber(),
      refereeDiscount: campaign.refereeRewardAmount.toNumber(),
      minBookingAmount: campaign.minBookingAmount.toNumber(),
      maxReferralsPerUser: campaign.maxReferralsPerUser,
    };
  }

  /**
   * Retrieves summary and list of all attributions generated by the user's referral code.
   */
  async getReferralHistory(userId: string) {
    const [attributions, totalRewardedCount] = await Promise.all([
      this.prisma.referralAttribution.findMany({
        where: { referrerId: userId },
        include: {
          referee: {
            select: {
              id: true,
              name: true,
              phone: true,
              createdAt: true,
            },
          },
        },
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.referralAttribution.count({
        where: { referrerId: userId, status: ReferralStatus.REWARDED },
      }),
    ]);

    let totalEarnings = 0;
    const items = attributions.map((a) => {
      if (a.status === ReferralStatus.REWARDED) {
        totalEarnings += a.referrerRewardAmount.toNumber();
      }

      // Mask referee phone for privacy (e.g., +91 98*** **321)
      const rawPhone = a.referee.phone || '';
      const maskedPhone =
        rawPhone.length > 6
          ? `${rawPhone.slice(0, 4)}****${rawPhone.slice(-2)}`
          : 'Customer';

      return {
        id: a.id,
        refereeName: a.referee.name || 'DriveGo User',
        refereePhone: maskedPhone,
        status: a.status,
        rewardAmount: a.referrerRewardAmount.toNumber(),
        createdAt: a.createdAt,
        qualifiedAt: a.qualifiedAt,
        rewardedAt: a.rewardedAt,
      };
    });

    const totalRegistered = attributions.filter(
      (a) => a.status === ReferralStatus.REGISTERED || a.status === ReferralStatus.QUALIFIED || a.status === ReferralStatus.REWARDED,
    ).length;

    const totalCompleted = attributions.filter(
      (a) => a.status === ReferralStatus.REWARDED,
    ).length;

    return {
      summary: {
        totalInvited: attributions.length,
        totalRegistered,
        totalCompleted,
        totalRewardedCount,
        totalEarnings,
      },
      referrals: items,
    };
  }

  /**
   * Applies a referral code for a new customer with multi-layer fraud protection.
   */
  async applyReferralCode(refereeId: string, dto: ApplyReferralCodeDto) {
    const cleanCode = dto.referralCode.trim().toUpperCase();

    // 1. Find Referrer by code
    const referrer = await this.prisma.user.findUnique({
      where: { referralCode: cleanCode },
      include: { customerKyc: true },
    });

    if (!referrer) {
      throw new BadRequestException('Invalid referral code. Please check and try again.');
    }

    // 2. Fetch Referee
    const referee = await this.prisma.user.findUnique({
      where: { id: refereeId },
      include: { customerKyc: true },
    });

    if (!referee) {
      throw new NotFoundException('Customer profile not found.');
    }

    // Fraud Check 1: Self-referral
    if (referrer.id === referee.id) {
      throw new BadRequestException('Self-referral is strictly prohibited.');
    }

    // Fraud Check 2: Same phone identity
    if (referrer.phone && referee.phone && referrer.phone.trim() === referee.phone.trim()) {
      throw new BadRequestException('Referral code cannot be shared between the same phone identity.');
    }

    // Fraud Check 3: Same verified KYC / Driving License number
    if (
      referrer.customerKyc?.licenceNumber &&
      referee.customerKyc?.licenceNumber &&
      referrer.customerKyc.licenceNumber.trim().toUpperCase() === referee.customerKyc.licenceNumber.trim().toUpperCase()
    ) {
      throw new BadRequestException('Referral code cannot be shared with the same verified KYC identity.');
    }

    // Fraud Check 4: Referee already referred
    const existingAttribution = await this.prisma.referralAttribution.findUnique({
      where: { refereeId },
    });
    if (existingAttribution) {
      throw new ConflictException('You have already applied a referral code.');
    }

    // Fraud Check 5: Referee already has prior completed bookings
    const priorCompletedBookings = await this.prisma.booking.count({
      where: {
        customerId: refereeId,
        status: BookingStatus.COMPLETED,
      },
    });
    if (priorCompletedBookings > 0) {
      throw new BadRequestException('Referral benefits are only applicable for first-time customers.');
    }

    // 3. Resolve Campaign & Validate City / Date
    let campaign = await this.prisma.referralCampaign.findFirst({
      where: {
        isActive: true,
        ...(dto.city ? { OR: [{ city: dto.city }, { city: null }] } : { city: null }),
      },
      orderBy: { city: 'desc' }, // prioritize city-specific campaign over global
    });

    if (!campaign) {
      campaign = await this.getOrCreateDefaultCampaign();
    }

    if (!campaign.isActive) {
      throw new BadRequestException('This referral campaign is currently inactive.');
    }

    const now = new Date();
    if (campaign.startDate && campaign.startDate > now) {
      throw new BadRequestException('This referral campaign has not started yet.');
    }
    if (campaign.endDate && campaign.endDate < now) {
      throw new BadRequestException('This referral campaign has expired.');
    }

    if (campaign.city && dto.city && campaign.city.toLowerCase() !== dto.city.toLowerCase()) {
      throw new BadRequestException(`This referral campaign is only applicable in ${campaign.city}.`);
    }

    // Fraud Check 6: Maximum rewarded referrals cap
    const rewardedCount = await this.prisma.referralAttribution.count({
      where: {
        referrerId: referrer.id,
        campaignId: campaign.id,
        status: ReferralStatus.REWARDED,
      },
    });

    if (rewardedCount >= campaign.maxReferralsPerUser) {
      throw new BadRequestException(
        `Referrer has reached the maximum rewarded referrals limit (${campaign.maxReferralsPerUser}) for this campaign.`,
      );
    }

    // 4. Create Referral Attribution atomically
    const attribution = await this.prisma.referralAttribution.create({
      data: {
        referrerId: referrer.id,
        refereeId: referee.id,
        campaignId: campaign.id,
        referralCodeUsed: cleanCode,
        status: ReferralStatus.REGISTERED,
        referrerRewardAmount: campaign.referrerRewardAmount,
        refereeRewardAmount: campaign.refereeRewardAmount,
      },
    });

    this.logger.log(
      `[REFERRAL ATTRIBUTION] Referee ${referee.id} linked to Referrer ${referrer.id} via code ${cleanCode} (Attribution: ${attribution.id})`,
    );

    return {
      success: true,
      message: `Referral code applied! You will get ₹${campaign.refereeRewardAmount.toFixed(0)} off on your first qualifying booking of ₹${campaign.minBookingAmount.toFixed(0)} or more.`,
      discountAmount: campaign.refereeRewardAmount.toNumber(),
      minBookingAmount: campaign.minBookingAmount.toNumber(),
    };
  }

  /**
   * Evaluates whether a customer is eligible for the first-booking referral checkout discount.
   */
  async getRefereeEligibility(refereeId: string) {
    const attribution = await this.prisma.referralAttribution.findUnique({
      where: { refereeId },
      include: { campaign: true },
    });

    if (!attribution || attribution.status !== ReferralStatus.REGISTERED) {
      return { eligible: false, discountAmount: 0, minBookingAmount: 0 };
    }

    const completedBookings = await this.prisma.booking.count({
      where: {
        customerId: refereeId,
        status: BookingStatus.COMPLETED,
      },
    });

    if (completedBookings > 0) {
      return { eligible: false, discountAmount: 0, minBookingAmount: 0 };
    }

    const minAmount = attribution.campaign
      ? attribution.campaign.minBookingAmount.toNumber()
      : DEFAULT_MIN_BOOKING_AMOUNT;

    return {
      eligible: true,
      attributionId: attribution.id,
      discountAmount: attribution.refereeRewardAmount.toNumber(),
      minBookingAmount: minAmount,
      referralCodeUsed: attribution.referralCodeUsed,
    };
  }

  /**
   * Authoritative Qualification Event: Triggered when referee completes their first booking.
   * Atomically verifies qualification, locks attribution, credits ₹250 wallet promo to referrer.
   */
  async handleBookingCompleted(bookingId: string, externalTx?: Prisma.TransactionClient) {
    const executeQualification = async (tx: Prisma.TransactionClient) => {
      const booking = await tx.booking.findUnique({
        where: { id: bookingId },
        include: { payment: true, customer: true },
      });

      if (!booking || booking.status !== BookingStatus.COMPLETED) {
        return null;
      }

      // Check attribution for this referee
      const attribution = await tx.referralAttribution.findUnique({
        where: { refereeId: booking.customerId },
        include: { campaign: true },
      });

      if (!attribution) {
        return null; // Not a referred user
      }

      // If already rewarded or fraud-blocked, do nothing (idempotent safeguard)
      if (attribution.status === ReferralStatus.REWARDED) {
        this.logger.log(`Referral attribution ${attribution.id} is already REWARDED. Skipping.`);
        return { alreadyRewarded: true, attributionId: attribution.id };
      }

      if (
        attribution.status === ReferralStatus.FRAUD_BLOCKED ||
        attribution.status === ReferralStatus.CANCELLED ||
        attribution.status === ReferralStatus.EXPIRED
      ) {
        this.logger.warn(`Referral attribution ${attribution.id} is in non-rewardable status: ${attribution.status}`);
        return null;
      }

      const minQualifyingAmount = attribution.campaign
        ? attribution.campaign.minBookingAmount
        : new Decimal(DEFAULT_MIN_BOOKING_AMOUNT);

      // Check minimum qualifying booking fare
      if (booking.totalFare.lt(minQualifyingAmount)) {
        this.logger.log(
          `Booking ${bookingId} total fare ₹${booking.totalFare} is below min qualifying amount ₹${minQualifyingAmount}. Referral not qualified.`,
        );
        return null;
      }

      // Check booking payment validity (must be paid and not refunded)
      if (!booking.payment || booking.payment.status !== 'PAID' || booking.payment.refundStatus !== 'NONE') {
        this.logger.warn(`Booking ${bookingId} payment is invalid or refunded. Referral qualification aborted.`);
        return null;
      }

      // 1. Lock Attribution row
      const lockedRows: any[] = await tx.$queryRaw`
        SELECT id, status, "referrerId", "refereeId", "referrerRewardAmount"
        FROM "ReferralAttribution"
        WHERE id = ${attribution.id}
        FOR UPDATE
      `;

      if (!lockedRows || lockedRows.length === 0) {
        return null;
      }

      const lockedAttribution = lockedRows[0];
      if (lockedAttribution.status === ReferralStatus.REWARDED) {
        return { alreadyRewarded: true, attributionId: attribution.id };
      }

      // 2. Mark Attribution QUALIFIED
      await tx.referralAttribution.update({
        where: { id: attribution.id },
        data: {
          status: ReferralStatus.QUALIFIED,
          qualifyingBookingId: booking.id,
          qualifiedAt: new Date(),
        },
      });

      // 3. Ensure Referrer Wallet exists
      const referrerWallet = await this.walletsService.getOrCreateWallet(attribution.referrerId, tx);

      // 4. Issue Authoritative Wallet Credit to Referrer
      const idempotencyKey = `ref_reward_${attribution.id}_referrer`;
      const rewardAmount = attribution.referrerRewardAmount;

      const ledgerEntry = await this.walletsService.creditWallet(
        referrerWallet.id,
        rewardAmount,
        LedgerEntryType.REFERRAL_REWARD,
        WalletBucketType.PROMOTIONAL,
        'REFERRAL',
        attribution.id,
        idempotencyKey,
        `Referral reward for inviting ${booking.customer.name || 'a friend'}`,
        undefined,
        {
          attributionId: attribution.id,
          qualifyingBookingId: booking.id,
          refereeId: booking.customerId,
        },
        tx,
      );

      // 5. Mark Attribution REWARDED
      const updatedAttribution = await tx.referralAttribution.update({
        where: { id: attribution.id },
        data: {
          status: ReferralStatus.REWARDED,
          referrerLedgerEntryId: ledgerEntry.id,
          rewardedAt: new Date(),
        },
      });

      this.logger.log(
        `[REFERRAL REWARDED] Credited ₹${rewardAmount.toFixed(2)} to Referrer ${attribution.referrerId} | Ledger: ${ledgerEntry.id}`,
      );

      // 6. Notify Referrer
      try {
        await this.notificationsService.notifyUser(
          attribution.referrerId,
          'Referral Reward Earned! 🎉',
          `You earned ₹${rewardAmount.toFixed(0)} DriveGo Wallet credit! Your referred friend completed their first trip.`,
        );
      } catch (err: any) {
        this.logger.warn(`Failed to dispatch referral notification: ${err.message}`);
      }

      return {
        success: true,
        attributionId: updatedAttribution.id,
        rewardAmount: rewardAmount.toNumber(),
        ledgerEntryId: ledgerEntry.id,
      };
    };

    if (externalTx) {
      return executeQualification(externalTx);
    }
    return this.prisma.$transaction(executeQualification);
  }

  // ── Admin Campaign Management ─────────────────────────────────────────────

  /**
   * Retrieves all referral campaigns with performance metrics.
   */
  async getAdminCampaigns() {
    const campaigns = await this.prisma.referralCampaign.findMany({
      orderBy: { createdAt: 'desc' },
      include: {
        attributions: {
          select: { status: true },
        },
      },
    });

    return campaigns.map((c) => {
      const registered = c.attributions.filter((a) => a.status === ReferralStatus.REGISTERED).length;
      const qualified = c.attributions.filter((a) => a.status === ReferralStatus.QUALIFIED).length;
      const rewarded = c.attributions.filter((a) => a.status === ReferralStatus.REWARDED).length;
      const cancelled = c.attributions.filter((a) => a.status === ReferralStatus.CANCELLED).length;
      const fraudBlocked = c.attributions.filter((a) => a.status === ReferralStatus.FRAUD_BLOCKED).length;

      return {
        id: c.id,
        name: c.name,
        code: c.code,
        referrerRewardAmount: c.referrerRewardAmount.toNumber(),
        refereeRewardAmount: c.refereeRewardAmount.toNumber(),
        minBookingAmount: c.minBookingAmount.toNumber(),
        city: c.city,
        startDate: c.startDate,
        endDate: c.endDate,
        isActive: c.isActive,
        maxReferralsPerUser: c.maxReferralsPerUser,
        createdAt: c.createdAt,
        updatedAt: c.updatedAt,
        stats: {
          total: c.attributions.length,
          registered,
          qualified,
          rewarded,
          cancelled,
          fraudBlocked,
        },
      };
    });
  }

  /**
   * Creates a new referral campaign with AuditLog.
   */
  async createAdminCampaign(adminUserId: string, dto: CreateReferralCampaignDto) {
    const existing = await this.prisma.referralCampaign.findUnique({
      where: { code: dto.code.toUpperCase() },
    });

    if (existing) {
      throw new ConflictException(`Campaign code '${dto.code}' already exists.`);
    }

    const campaign = await this.prisma.referralCampaign.create({
      data: {
        name: dto.name,
        code: dto.code.toUpperCase(),
        referrerRewardAmount: new Decimal(dto.referrerRewardAmount),
        refereeRewardAmount: new Decimal(dto.refereeRewardAmount),
        minBookingAmount: new Decimal(dto.minBookingAmount),
        city: dto.city || null,
        startDate: dto.startDate ? new Date(dto.startDate) : null,
        endDate: dto.endDate ? new Date(dto.endDate) : null,
        isActive: dto.isActive !== undefined ? dto.isActive : true,
        maxReferralsPerUser: dto.maxReferralsPerUser || DEFAULT_MAX_REFERRALS_PER_USER,
      },
    });

    await this.auditLogService.log(
      adminUserId,
      'CREATE_REFERRAL_CAMPAIGN',
      'ReferralCampaign',
      campaign.id,
      dto,
    );

    return campaign;
  }

  /**
   * Updates an existing referral campaign with AuditLog.
   */
  async updateAdminCampaign(adminUserId: string, id: string, dto: UpdateReferralCampaignDto) {
    const campaign = await this.prisma.referralCampaign.findUnique({
      where: { id },
    });

    if (!campaign) {
      throw new NotFoundException(`Referral campaign not found: ${id}`);
    }

    const updated = await this.prisma.referralCampaign.update({
      where: { id },
      data: {
        ...(dto.name && { name: dto.name }),
        ...(dto.referrerRewardAmount !== undefined && { referrerRewardAmount: new Decimal(dto.referrerRewardAmount) }),
        ...(dto.refereeRewardAmount !== undefined && { refereeRewardAmount: new Decimal(dto.refereeRewardAmount) }),
        ...(dto.minBookingAmount !== undefined && { minBookingAmount: new Decimal(dto.minBookingAmount) }),
        ...(dto.city !== undefined && { city: dto.city }),
        ...(dto.startDate !== undefined && { startDate: dto.startDate ? new Date(dto.startDate) : null }),
        ...(dto.endDate !== undefined && { endDate: dto.endDate ? new Date(dto.endDate) : null }),
        ...(dto.isActive !== undefined && { isActive: dto.isActive }),
        ...(dto.maxReferralsPerUser !== undefined && { maxReferralsPerUser: dto.maxReferralsPerUser }),
      },
    });

    await this.auditLogService.log(
      adminUserId,
      'UPDATE_REFERRAL_CAMPAIGN',
      'ReferralCampaign',
      id,
      dto,
    );

    return updated;
  }

  /**
   * Toggles active state of a campaign with AuditLog.
   */
  async toggleAdminCampaign(adminUserId: string, id: string) {
    const campaign = await this.prisma.referralCampaign.findUnique({
      where: { id },
    });

    if (!campaign) {
      throw new NotFoundException(`Referral campaign not found: ${id}`);
    }

    const updated = await this.prisma.referralCampaign.update({
      where: { id },
      data: { isActive: !campaign.isActive },
    });

    await this.auditLogService.log(
      adminUserId,
      'TOGGLE_REFERRAL_CAMPAIGN',
      'ReferralCampaign',
      id,
      { newStatus: updated.isActive },
    );

    return updated;
  }
}
